{
    "bm_regex_effbot_a245e0361625bbc6129c2b1ec112e9db.py": {
        "stats": {
            "total_parameters": 7,
            "parameters_with_annotations": 6
        },
        "error_count": 5,
        "isCompiled": false,
        "errors": [
            "bm_regex_effbot_a245e0361625bbc6129c2b1ec112e9db.py:43: error: Argument 1 to \"append\" of \"list\" has incompatible type \"bytes\"; expected \"str\"  [arg-type]",
            "bm_regex_effbot_a245e0361625bbc6129c2b1ec112e9db.py:84: error: \"Callable[[int], float]\" has no attribute \"data\"  [attr-defined]",
            "bm_regex_effbot_a245e0361625bbc6129c2b1ec112e9db.py:85: error: \"Callable[[int], float]\" has no attribute \"data\"  [attr-defined]",
            "bm_regex_effbot_a245e0361625bbc6129c2b1ec112e9db.py:86: error: \"Callable[[int], float]\" has no attribute \"data\"  [attr-defined]",
            "bm_regex_effbot_a245e0361625bbc6129c2b1ec112e9db.py:104: error: \"Callable[[int], float]\" has no attribute \"data\"  [attr-defined]",
            "Found 5 errors in 1 file (checked 1 source file)"
        ]
    },
    "btm_matcher_4f0ccfe480ecd407cea1b164e491bdab.py": {
        "stats": {
            "total_parameters": 12,
            "parameters_with_annotations": 6
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "btm_matcher_4f0ccfe480ecd407cea1b164e491bdab.py:7: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "btm_utils_89de4e6b444fd08def9b8ce6daebb6ce.py": {
        "stats": {
            "total_parameters": 12,
            "parameters_with_annotations": 7
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "btm_utils_89de4e6b444fd08def9b8ce6daebb6ce.py:3: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "conf_da9965b984331586a98ccf31b5479f12.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "conf_da9965b984331586a98ccf31b5479f12.py:10: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "conv_1bc4e8a8f8f49e5d7327949ef65b3e34.py": {
        "stats": {
            "total_parameters": 8,
            "parameters_with_annotations": 4
        },
        "error_count": 6,
        "isCompiled": false,
        "errors": [
            "conv_1bc4e8a8f8f49e5d7327949ef65b3e34.py:30: error: Item \"None\" of \"Optional[Match[str]]\" has no attribute \"groups\"  [union-attr]",
            "conv_1bc4e8a8f8f49e5d7327949ef65b3e34.py:38: error: Missing return statement  [return]",
            "conv_1bc4e8a8f8f49e5d7327949ef65b3e34.py:125: error: Incompatible types in assignment (expression has type \"Union[str, Any]\", variable has type \"int\")  [assignment]",
            "conv_1bc4e8a8f8f49e5d7327949ef65b3e34.py:128: error: Incompatible types in assignment (expression has type \"None\", variable has type \"int\")  [assignment]",
            "conv_1bc4e8a8f8f49e5d7327949ef65b3e34.py:130: error: Argument 1 to \"eval\" has incompatible type \"int\"; expected \"Union[str, Buffer, CodeType]\"  [arg-type]",
            "conv_1bc4e8a8f8f49e5d7327949ef65b3e34.py:131: error: Argument 1 to \"append\" of \"list\" has incompatible type \"Tuple[int, int]\"; expected \"Tuple[int, Optional[str]]\"  [arg-type]",
            "Found 6 errors in 1 file (checked 1 source file)"
        ]
    },
    "driver_3aabcaf38ec34819d53840a6d8011e52.py": {
        "stats": {
            "total_parameters": 30,
            "parameters_with_annotations": 24
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "driver_3aabcaf38ec34819d53840a6d8011e52.py:10: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fixer_base_85dc36bb56186b3c5d4a5ff7bd806974.py": {
        "stats": {
            "total_parameters": 30,
            "parameters_with_annotations": 10
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fixer_base_85dc36bb56186b3c5d4a5ff7bd806974.py:4: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fixer_util_3abd089b71f391b9fbcc1279a5103b06.py": {
        "stats": {
            "total_parameters": 54,
            "parameters_with_annotations": 54
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fixer_util_3abd089b71f391b9fbcc1279a5103b06.py:5: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_apply_b16e3ffb9d7076892b1bf5bf775adbe3.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "fix_apply_b16e3ffb9d7076892b1bf5bf775adbe3.py:3: error: No parent module -- cannot perform relative import",
            "fix_apply_b16e3ffb9d7076892b1bf5bf775adbe3.py:5: error: No parent module -- cannot perform relative import",
            "Found 2 errors in 1 file (errors prevented further checking)"
        ]
    },
    "fix_asserts_4f68a58c5bfe9899342f37ae6be10efb.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "fix_asserts_4f68a58c5bfe9899342f37ae6be10efb.py:2: error: Relative import climbs too many namespaces  [misc]",
            "fix_asserts_4f68a58c5bfe9899342f37ae6be10efb.py:3: error: Relative import climbs too many namespaces  [misc]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "fix_basestring_84e7b7d66f65f34af7dad68be8649969.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_basestring_84e7b7d66f65f34af7dad68be8649969.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_buffer_0297747e2fb863eb527f0296b4e04c1d.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_buffer_0297747e2fb863eb527f0296b4e04c1d.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_dict_26321b67f43cc9e91f518d3409058c17.py": {
        "stats": {
            "total_parameters": 6,
            "parameters_with_annotations": 4
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "fix_dict_26321b67f43cc9e91f518d3409058c17.py:2: error: No parent module -- cannot perform relative import",
            "fix_dict_26321b67f43cc9e91f518d3409058c17.py:3: error: No parent module -- cannot perform relative import",
            "fix_dict_26321b67f43cc9e91f518d3409058c17.py:4: error: No parent module -- cannot perform relative import",
            "fix_dict_26321b67f43cc9e91f518d3409058c17.py:6: error: No parent module -- cannot perform relative import",
            "Found 4 errors in 1 file (errors prevented further checking)"
        ]
    },
    "fix_except_dc2a3518b6572d9df36c7c6a9e7d185c.py": {
        "stats": {
            "total_parameters": 4,
            "parameters_with_annotations": 3
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "fix_except_dc2a3518b6572d9df36c7c6a9e7d185c.py:2: error: No parent module -- cannot perform relative import",
            "fix_except_dc2a3518b6572d9df36c7c6a9e7d185c.py:4: error: No parent module -- cannot perform relative import",
            "Found 2 errors in 1 file (errors prevented further checking)"
        ]
    },
    "fix_execfile_23c0aea8521d5905ef574849a1199c42.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_execfile_23c0aea8521d5905ef574849a1199c42.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_exec_c2495e4b98c855ef8e4bb6b499835916.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_exec_c2495e4b98c855ef8e4bb6b499835916.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py": {
        "stats": {
            "total_parameters": 7,
            "parameters_with_annotations": 4
        },
        "error_count": 13,
        "isCompiled": false,
        "errors": [
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:8: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:9: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:10: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:16: error: Argument 2 of \"start_tree\" is incompatible with supertype \"BaseFix\"; supertype defines the argument type as \"Union[str, PathLike[str]]\"  [override]",
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:16: note: This violates the Liskov substitution principle",
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:16: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides",
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:20: error: Argument 1 of \"transform\" is incompatible with supertype \"BaseFix\"; supertype defines the argument type as \"Base\"  [override]",
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:20: note: This violates the Liskov substitution principle",
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:20: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides",
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:20: error: \"dict\" is not subscriptable, use \"typing.Dict\" instead  [misc]",
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:33: error: Incompatible types in assignment (expression has type \"Union[Node, Leaf]\", variable has type \"Node\")  [assignment]",
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:38: error: Incompatible types in assignment (expression has type \"Optional[Node]\", variable has type \"Node\")  [assignment]",
            "fix_exitfunc_4c0e023d6233f367f6bbb22f72abff19.py:40: error: Incompatible types in assignment (expression has type \"Optional[Node]\", variable has type \"Node\")  [assignment]",
            "Found 9 errors in 1 file (checked 1 source file)"
        ]
    },
    "fix_filter_0d6c2a2f1d6dc89e448a17d7d1859c3a.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_filter_0d6c2a2f1d6dc89e448a17d7d1859c3a.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_funcattrs_b0872da875aad669f1282398989d9c89.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_funcattrs_b0872da875aad669f1282398989d9c89.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_future_23a687d0e9b1a05680b4c5ab0decab24.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_future_23a687d0e9b1a05680b4c5ab0decab24.py:3: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_getcwdu_4c7a9a4fe905d6e1ec1a1f745fc07e92.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_getcwdu_4c7a9a4fe905d6e1ec1a1f745fc07e92.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_has_key_3d19bb5809047e970a7a7694f342c22f.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "fix_has_key_3d19bb5809047e970a7a7694f342c22f.py:2: error: No parent module -- cannot perform relative import",
            "fix_has_key_3d19bb5809047e970a7a7694f342c22f.py:3: error: No parent module -- cannot perform relative import",
            "Found 2 errors in 1 file (errors prevented further checking)"
        ]
    },
    "fix_idioms_f2fc0fac4f3e5f15360819a753c8ce8d.py": {
        "stats": {
            "total_parameters": 14,
            "parameters_with_annotations": 9
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_idioms_f2fc0fac4f3e5f15360819a753c8ce8d.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_imports2_990f0acae87e29ae9492418a41754ee9.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_imports2_990f0acae87e29ae9492418a41754ee9.py:1: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_imports_c928b33522d728da5c7972ba72bd5d6b.py": {
        "stats": {
            "total_parameters": 12,
            "parameters_with_annotations": 3
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_imports_c928b33522d728da5c7972ba72bd5d6b.py:3: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_import_f23058f61e15a73e76de69f135bf5f6f.py": {
        "stats": {
            "total_parameters": 9,
            "parameters_with_annotations": 6
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_import_f23058f61e15a73e76de69f135bf5f6f.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_input_dfe10ba83564ecc0d92ce3fe3f7469f6.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "fix_input_dfe10ba83564ecc0d92ce3fe3f7469f6.py:2: error: No parent module -- cannot perform relative import",
            "fix_input_dfe10ba83564ecc0d92ce3fe3f7469f6.py:4: error: No parent module -- cannot perform relative import",
            "Found 2 errors in 1 file (errors prevented further checking)"
        ]
    },
    "fix_intern_293f735a6b785b784192f0be1636168a.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_intern_293f735a6b785b784192f0be1636168a.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_isinstance_ddf41b92f0feef3fdda51bb5aa571b20.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_isinstance_ddf41b92f0feef3fdda51bb5aa571b20.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_itertools_4f695aa383ccd1d83a24563d5dfb7466.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_itertools_4f695aa383ccd1d83a24563d5dfb7466.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 15,
        "isCompiled": false,
        "errors": [
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:8: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:9: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:9: error: Not all arguments converted during string formatting  [str-format]",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:11: error: Argument 1 of \"transform\" is incompatible with supertype \"BaseFix\"; supertype defines the argument type as \"Base\"  [override]",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:11: note: This violates the Liskov substitution principle",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:11: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:11: error: Argument 2 of \"transform\" is incompatible with supertype \"BaseFix\"; supertype defines the argument type as \"Dict[str, Base]\"  [override]",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:12: error: Incompatible types in assignment (expression has type \"Optional[Node]\", variable has type \"Node\")  [assignment]",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:16: error: Incompatible types in assignment (expression has type \"List[Union[Node, Leaf]]\", variable has type \"List[Node]\")  [assignment]",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:19: error: \"Node\" has no attribute \"value\"  [attr-defined]",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:25: error: Incompatible types in assignment (expression has type \"Union[Node, Leaf]\", variable has type \"Node\")  [assignment]",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:26: error: \"Node\" has no attribute \"value\"  [attr-defined]",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:28: error: \"Node\" has no attribute \"value\"  [attr-defined]",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:32: error: \"Node\" has no attribute \"value\"  [attr-defined]",
            "fix_itertools_imports_1ff0945ccfa029ee1e633d3b0c38dca8.py:33: error: Incompatible types in assignment (expression has type \"List[Union[Node, Leaf]]\", variable has type \"List[Node]\")  [assignment]",
            "Found 13 errors in 1 file (checked 1 source file)"
        ]
    },
    "fix_long_c9fe2d241de1cc017034e4f7bc2217cb.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 6,
        "isCompiled": false,
        "errors": [
            "fix_long_c9fe2d241de1cc017034e4f7bc2217cb.py:6: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_long_c9fe2d241de1cc017034e4f7bc2217cb.py:7: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_long_c9fe2d241de1cc017034e4f7bc2217cb.py:9: error: Argument 1 of \"transform\" is incompatible with supertype \"BaseFix\"; supertype defines the argument type as \"Base\"  [override]",
            "fix_long_c9fe2d241de1cc017034e4f7bc2217cb.py:9: note: This violates the Liskov substitution principle",
            "fix_long_c9fe2d241de1cc017034e4f7bc2217cb.py:9: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides",
            "fix_long_c9fe2d241de1cc017034e4f7bc2217cb.py:11: error: \"Node\" has no attribute \"value\"  [attr-defined]",
            "Found 4 errors in 1 file (checked 1 source file)"
        ]
    },
    "fix_map_923c607ffa53d4554c8b2f301b449ede.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_map_923c607ffa53d4554c8b2f301b449ede.py:3: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_metaclass_c0624dc69dbc6726b21bb4af3b427e71.py": {
        "stats": {
            "total_parameters": 11,
            "parameters_with_annotations": 10
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_metaclass_c0624dc69dbc6726b21bb4af3b427e71.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_methodattrs_6a42825e2099caece0bd5f7c288ff26d.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_methodattrs_6a42825e2099caece0bd5f7c288ff26d.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_next_804cb524bc47688ff19276d35ba9a378.py": {
        "stats": {
            "total_parameters": 10,
            "parameters_with_annotations": 8
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_next_804cb524bc47688ff19276d35ba9a378.py:5: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_ne_99cb992e21ba5c9cdd4ed2465485a813.py": {
        "stats": {
            "total_parameters": 5,
            "parameters_with_annotations": 3
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "fix_ne_99cb992e21ba5c9cdd4ed2465485a813.py:2: error: No parent module -- cannot perform relative import",
            "fix_ne_99cb992e21ba5c9cdd4ed2465485a813.py:4: error: No parent module -- cannot perform relative import",
            "Found 2 errors in 1 file (errors prevented further checking)"
        ]
    },
    "fix_nonzero_1692b34cd0de1184d67c1e62cc8d6ec7.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_nonzero_1692b34cd0de1184d67c1e62cc8d6ec7.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_numliterals_98271bbcfbd011fb007cd3a1ad98359d.py": {
        "stats": {
            "total_parameters": 5,
            "parameters_with_annotations": 3
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_numliterals_98271bbcfbd011fb007cd3a1ad98359d.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_operator_41eec7e7f93f16bad1cfd1a8ce899fbd.py": {
        "stats": {
            "total_parameters": 38,
            "parameters_with_annotations": 27
        },
        "error_count": 6,
        "isCompiled": false,
        "errors": [
            "fix_operator_41eec7e7f93f16bad1cfd1a8ce899fbd.py:8: error: \"Callable[..., Any]\" has no attribute \"invocation\"  [attr-defined]",
            "fix_operator_41eec7e7f93f16bad1cfd1a8ce899fbd.py:13: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_operator_41eec7e7f93f16bad1cfd1a8ce899fbd.py:14: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_operator_41eec7e7f93f16bad1cfd1a8ce899fbd.py:14: error: Incompatible types in assignment (expression has type \"str\", base class \"BaseFix\" defined the type as \"Literal['post', 'pre']\")  [assignment]",
            "fix_operator_41eec7e7f93f16bad1cfd1a8ce899fbd.py:17: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_operator_41eec7e7f93f16bad1cfd1a8ce899fbd.py:67: error: Argument 2 to \"isinstance\" has incompatible type \"<typing special form>\"; expected \"_ClassInfo\"  [arg-type]",
            "Found 6 errors in 1 file (checked 1 source file)"
        ]
    },
    "fix_paren_353b6cf540d829d4cb86fcdf6b1c3685.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_paren_353b6cf540d829d4cb86fcdf6b1c3685.py:3: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_print_aca65419859f1ac0135d2ad32457f8e8.py": {
        "stats": {
            "total_parameters": 7,
            "parameters_with_annotations": 5
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "fix_print_aca65419859f1ac0135d2ad32457f8e8.py:2: error: No parent module -- cannot perform relative import",
            "fix_print_aca65419859f1ac0135d2ad32457f8e8.py:3: error: No parent module -- cannot perform relative import",
            "fix_print_aca65419859f1ac0135d2ad32457f8e8.py:5: error: No parent module -- cannot perform relative import",
            "Found 3 errors in 1 file (errors prevented further checking)"
        ]
    },
    "fix_raise_495345fa6dfbfe2a576ace6d7c035c51.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "fix_raise_495345fa6dfbfe2a576ace6d7c035c51.py:2: error: No parent module -- cannot perform relative import",
            "fix_raise_495345fa6dfbfe2a576ace6d7c035c51.py:4: error: No parent module -- cannot perform relative import",
            "Found 2 errors in 1 file (errors prevented further checking)"
        ]
    },
    "fix_raw_input_b30be6e6f6b371c5d0cc4238916aaac7.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_raw_input_b30be6e6f6b371c5d0cc4238916aaac7.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_reduce_4024a50c8ce9def06d8aabec27d605d4.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 7,
        "isCompiled": false,
        "errors": [
            "fix_reduce_4024a50c8ce9def06d8aabec27d605d4.py:8: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_reduce_4024a50c8ce9def06d8aabec27d605d4.py:9: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_reduce_4024a50c8ce9def06d8aabec27d605d4.py:9: error: Incompatible types in assignment (expression has type \"str\", base class \"BaseFix\" defined the type as \"Literal['post', 'pre']\")  [assignment]",
            "fix_reduce_4024a50c8ce9def06d8aabec27d605d4.py:10: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_reduce_4024a50c8ce9def06d8aabec27d605d4.py:12: error: Argument 1 of \"transform\" is incompatible with supertype \"BaseFix\"; supertype defines the argument type as \"Base\"  [override]",
            "fix_reduce_4024a50c8ce9def06d8aabec27d605d4.py:12: note: This violates the Liskov substitution principle",
            "fix_reduce_4024a50c8ce9def06d8aabec27d605d4.py:12: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides",
            "Found 5 errors in 1 file (checked 1 source file)"
        ]
    },
    "fix_reload_c7113cf30125ff3fd4e963b1761da463.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_reload_c7113cf30125ff3fd4e963b1761da463.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_renames_1eb568db217ff15c2b4004ccd75dd169.py": {
        "stats": {
            "total_parameters": 6,
            "parameters_with_annotations": 4
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_renames_1eb568db217ff15c2b4004ccd75dd169.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_repr_4c23954f65d7efb15afeef1f4931d3d3.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_repr_4c23954f65d7efb15afeef1f4931d3d3.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_set_literal_4c0da782a04c8b621da519425739911b.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 10,
        "isCompiled": false,
        "errors": [
            "fix_set_literal_4c0da782a04c8b621da519425739911b.py:7: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_set_literal_4c0da782a04c8b621da519425739911b.py:8: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_set_literal_4c0da782a04c8b621da519425739911b.py:9: error: Cannot override class variable (previously declared on base class \"BaseFix\") with instance variable  [misc]",
            "fix_set_literal_4c0da782a04c8b621da519425739911b.py:20: error: Argument 1 of \"transform\" is incompatible with supertype \"BaseFix\"; supertype defines the argument type as \"Base\"  [override]",
            "fix_set_literal_4c0da782a04c8b621da519425739911b.py:20: note: This violates the Liskov substitution principle",
            "fix_set_literal_4c0da782a04c8b621da519425739911b.py:20: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides",
            "fix_set_literal_4c0da782a04c8b621da519425739911b.py:28: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]",
            "fix_set_literal_4c0da782a04c8b621da519425739911b.py:29: error: Generator has incompatible item type \"Union[Node, Leaf]\"; expected \"Leaf\"  [misc]",
            "fix_set_literal_4c0da782a04c8b621da519425739911b.py:31: error: Item \"None\" of \"Union[Node, Leaf, None]\" has no attribute \"prefix\"  [union-attr]",
            "fix_set_literal_4c0da782a04c8b621da519425739911b.py:35: error: Incompatible types in assignment (expression has type \"Union[Node, Leaf]\", variable has type \"Leaf\")  [assignment]",
            "Found 8 errors in 1 file (checked 1 source file)"
        ]
    },
    "fix_standarderror_6354be6de21e5d0ae8243cc615985cae.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_standarderror_6354be6de21e5d0ae8243cc615985cae.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_sys_exc_38efdf62222966e271d0328ae81e4b2f.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_sys_exc_38efdf62222966e271d0328ae81e4b2f.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_throw_9223bab1596f455827d0ca24d2cb4b8a.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "fix_throw_9223bab1596f455827d0ca24d2cb4b8a.py:2: error: No parent module -- cannot perform relative import",
            "fix_throw_9223bab1596f455827d0ca24d2cb4b8a.py:4: error: No parent module -- cannot perform relative import",
            "Found 2 errors in 1 file (errors prevented further checking)"
        ]
    },
    "fix_tuple_params_08235f2c848bdeb79dabf448ca7b343e.py": {
        "stats": {
            "total_parameters": 15,
            "parameters_with_annotations": 13
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "fix_tuple_params_08235f2c848bdeb79dabf448ca7b343e.py:2: error: No parent module -- cannot perform relative import",
            "fix_tuple_params_08235f2c848bdeb79dabf448ca7b343e.py:4: error: No parent module -- cannot perform relative import",
            "Found 2 errors in 1 file (errors prevented further checking)"
        ]
    },
    "fix_types_6de0a2197b78900ec88ac8b7b3545921.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_types_6de0a2197b78900ec88ac8b7b3545921.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_unicode_ea7cfd666cad0427f50e6bb2fe1a479d.py": {
        "stats": {
            "total_parameters": 6,
            "parameters_with_annotations": 4
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_unicode_ea7cfd666cad0427f50e6bb2fe1a479d.py:3: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_urllib_e4836c50388897297cf89c61693daed3.py": {
        "stats": {
            "total_parameters": 15,
            "parameters_with_annotations": 10
        },
        "error_count": 12,
        "isCompiled": false,
        "errors": [
            "fix_urllib_e4836c50388897297cf89c61693daed3.py:19: error: Need type annotation for \"bare\" (hint: \"bare: Set[<type>] = ...\")  [var-annotated]",
            "fix_urllib_e4836c50388897297cf89c61693daed3.py:37: error: Item \"None\" of \"Optional[Any]\" has no attribute \"prefix\"  [union-attr]",
            "fix_urllib_e4836c50388897297cf89c61693daed3.py:39: error: Item \"None\" of \"Optional[Any]\" has no attribute \"value\"  [union-attr]",
            "fix_urllib_e4836c50388897297cf89c61693daed3.py:41: error: Item \"None\" of \"Optional[Any]\" has no attribute \"value\"  [union-attr]",
            "fix_urllib_e4836c50388897297cf89c61693daed3.py:42: error: Item \"None\" of \"Optional[Any]\" has no attribute \"replace\"  [union-attr]",
            "fix_urllib_e4836c50388897297cf89c61693daed3.py:46: error: Item \"None\" of \"Optional[Any]\" has no attribute \"prefix\"  [union-attr]",
            "fix_urllib_e4836c50388897297cf89c61693daed3.py:52: error: Item \"None\" of \"Optional[Any]\" has no attribute \"value\"  [union-attr]",
            "fix_urllib_e4836c50388897297cf89c61693daed3.py:57: error: Item \"None\" of \"Optional[Any]\" has no attribute \"replace\"  [union-attr]",
            "fix_urllib_e4836c50388897297cf89c61693daed3.py:72: error: Item \"None\" of \"Optional[Any]\" has no attribute \"value\"  [union-attr]",
            "fix_urllib_e4836c50388897297cf89c61693daed3.py:114: error: Item \"None\" of \"Optional[Any]\" has no attribute \"value\"  [union-attr]",
            "fix_urllib_e4836c50388897297cf89c61693daed3.py:119: error: Item \"None\" of \"Optional[Any]\" has no attribute \"replace\"  [union-attr]",
            "fix_urllib_e4836c50388897297cf89c61693daed3.py:119: error: Item \"None\" of \"Optional[Any]\" has no attribute \"prefix\"  [union-attr]",
            "Found 12 errors in 1 file (checked 1 source file)"
        ]
    },
    "fix_ws_comma_3c3b2f49eeb26b8d75079583accc8d3c.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "fix_ws_comma_3c3b2f49eeb26b8d75079583accc8d3c.py:2: error: No parent module -- cannot perform relative import",
            "fix_ws_comma_3c3b2f49eeb26b8d75079583accc8d3c.py:4: error: No parent module -- cannot perform relative import",
            "Found 2 errors in 1 file (errors prevented further checking)"
        ]
    },
    "fix_xrange_b7597d1a2dcf484c9def32299bab0389.py": {
        "stats": {
            "total_parameters": 17,
            "parameters_with_annotations": 5
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "fix_xrange_b7597d1a2dcf484c9def32299bab0389.py:2: error: No parent module -- cannot perform relative import",
            "fix_xrange_b7597d1a2dcf484c9def32299bab0389.py:4: error: No parent module -- cannot perform relative import",
            "Found 2 errors in 1 file (errors prevented further checking)"
        ]
    },
    "fix_xreadlines_336d1f82c56a878207062958ce346079.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_xreadlines_336d1f82c56a878207062958ce346079.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "fix_zip_8deafd1b0091d77b3a4b65e272fcdb39.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "fix_zip_8deafd1b0091d77b3a4b65e272fcdb39.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "generate_data_7422c52c22b8c15ab496c22f64433879.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "generate_data_7422c52c22b8c15ab496c22f64433879.py:3: error: Library stubs not installed for \"toml\"  [import]",
            "generate_data_7422c52c22b8c15ab496c22f64433879.py:3: note: Hint: \"python3 -m pip install types-toml\"",
            "generate_data_7422c52c22b8c15ab496c22f64433879.py:3: note: (or run \"mypy --install-types\" to install all missing stub packages)",
            "generate_data_7422c52c22b8c15ab496c22f64433879.py:3: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "Generate_no_type_version_147101a8e98a675af12167080b175470.py": {
        "stats": {
            "total_parameters": 7,
            "parameters_with_annotations": 5
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "grammar_0ee226e126c4ae4d1f4233f1a436b1ad.py": {
        "stats": {
            "total_parameters": 9,
            "parameters_with_annotations": 3
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "grammar_0ee226e126c4ae4d1f4233f1a436b1ad.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "literals_51e85ba6bc607dc435c2756415e18998.py": {
        "stats": {
            "total_parameters": 2,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "literals_51e85ba6bc607dc435c2756415e18998.py:4: error: \"dict\" is not subscriptable, use \"typing.Dict\" instead  [misc]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "main_18e06710863c6ff46857d6e5f5e3193a.py": {
        "stats": {
            "total_parameters": 27,
            "parameters_with_annotations": 23
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "main_18e06710863c6ff46857d6e5f5e3193a.py:9: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "parse_16d2dea206b527e5e6f274f72e54d079.py": {
        "stats": {
            "total_parameters": 30,
            "parameters_with_annotations": 21
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "parse_16d2dea206b527e5e6f274f72e54d079.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "patcomp_39f9f5e83f63a35080e3487619196bab.py": {
        "stats": {
            "total_parameters": 18,
            "parameters_with_annotations": 13
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "patcomp_39f9f5e83f63a35080e3487619196bab.py:6: error: No parent module -- cannot perform relative import",
            "patcomp_39f9f5e83f63a35080e3487619196bab.py:7: error: No parent module -- cannot perform relative import",
            "Found 2 errors in 1 file (errors prevented further checking)"
        ]
    },
    "pgen_eba48e8b0455077a205d1dda049755b8.py": {
        "stats": {
            "total_parameters": 55,
            "parameters_with_annotations": 31
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "pgen_eba48e8b0455077a205d1dda049755b8.py:2: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "pygram_a5391fb5dc3ff905dab45ee155e42ff9.py": {
        "stats": {
            "total_parameters": 2,
            "parameters_with_annotations": 1
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "pygram_a5391fb5dc3ff905dab45ee155e42ff9.py:5: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "pyspecific_5869ad860916164ee81485b5281bc3c9.py": {
        "stats": {
            "total_parameters": 37,
            "parameters_with_annotations": 23
        },
        "error_count": 10,
        "isCompiled": false,
        "errors": [
            "pyspecific_5869ad860916164ee81485b5281bc3c9.py:3: error: Library stubs not installed for \"docutils\"  [import]",
            "pyspecific_5869ad860916164ee81485b5281bc3c9.py:4: error: Library stubs not installed for \"docutils.parsers.rst\"  [import]",
            "pyspecific_5869ad860916164ee81485b5281bc3c9.py:5: error: Library stubs not installed for \"docutils.utils\"  [import]",
            "pyspecific_5869ad860916164ee81485b5281bc3c9.py:11: error: Library stubs not installed for \"docutils.parsers.rst.states\"  [import]",
            "pyspecific_5869ad860916164ee81485b5281bc3c9.py:11: note: Hint: \"python3 -m pip install types-docutils\"",
            "pyspecific_5869ad860916164ee81485b5281bc3c9.py:11: note: (or run \"mypy --install-types\" to install all missing stub packages)",
            "pyspecific_5869ad860916164ee81485b5281bc3c9.py:11: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports",
            "pyspecific_5869ad860916164ee81485b5281bc3c9.py:63: error: \"handle_signature\" undefined in superclass  [misc]",
            "pyspecific_5869ad860916164ee81485b5281bc3c9.py:85: error: \"handle_signature\" undefined in superclass  [misc]",
            "pyspecific_5869ad860916164ee81485b5281bc3c9.py:92: error: \"handle_signature\" undefined in superclass  [misc]",
            "Found 7 errors in 1 file (checked 1 source file)"
        ]
    },
    "pytree_b5c9498d48307fc20f4016a12676f355.py": {
        "stats": {
            "total_parameters": 122,
            "parameters_with_annotations": 61
        },
        "error_count": 49,
        "isCompiled": false,
        "errors": [
            "pytree_b5c9498d48307fc20f4016a12676f355.py:17: error: Argument 2 to \"setdefault\" of \"MutableMapping\" has incompatible type \"int\"; expected \"str\"  [arg-type]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:35: error: Incompatible types in assignment (expression has type \"None\", base class \"object\" defined the type as \"Callable[[object], int]\")  [assignment]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:89: error: \"Tuple[Base, ...]\" has no attribute \"__delitem__\"; maybe \"__getitem__\"?  [attr-defined]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:130: error: \"Base\" has no attribute \"prefix\"  [attr-defined]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:140: error: Incompatible types in assignment (expression has type \"List[Base]\", variable has type \"Tuple[Base, ...]\")  [assignment]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:149: error: Incompatible types in assignment (expression has type \"None\", variable has type \"List[Any]\")  [assignment]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:152: error: Argument 1 to \"type_repr\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:160: error: Argument 1 of \"_eq\" is incompatible with supertype \"Base\"; supertype defines the argument type as \"Base\"  [override]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:160: note: This violates the Liskov substitution principle",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:160: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:164: error: Argument 1 to \"Node\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:180: error: \"Base\" has no attribute \"prefix\"  [attr-defined]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:185: error: \"Base\" has no attribute \"prefix\"  [attr-defined]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:190: error: Unsupported target for indexed assignment (\"Tuple[Base, ...]\")  [index]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:195: error: \"Tuple[Base, ...]\" has no attribute \"insert\"  [attr-defined]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:200: error: \"Tuple[Base, ...]\" has no attribute \"append\"  [attr-defined]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:227: error: Argument 1 of \"_eq\" is incompatible with supertype \"Base\"; supertype defines the argument type as \"Base\"  [override]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:227: note: This violates the Liskov substitution principle",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:227: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:231: error: Argument 1 to \"Leaf\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:270: error: Argument 1 to \"type_repr\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:285: error: \"BasePattern\" has no attribute \"_submatch\"  [attr-defined]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:288: error: Item \"None\" of \"Optional[Dict[str, Base]]\" has no attribute \"update\"  [union-attr]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:319: error: \"Base\" has no attribute \"value\"  [attr-defined]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:340: error: Argument 1 to \"generate_matches\" has incompatible type \"Optional[Any]\"; expected \"List[BasePattern]\"  [arg-type]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:340: error: Argument 2 to \"generate_matches\" has incompatible type \"Tuple[Base, ...]\"; expected \"List[Base]\"  [arg-type]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:346: error: Argument 1 to \"len\" has incompatible type \"Optional[Any]\"; expected \"Sized\"  [arg-type]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:348: error: Argument 1 to \"zip\" has incompatible type \"Optional[Any]\"; expected \"Iterable[Any]\"  [arg-type]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:357: error: Incompatible types in assignment (expression has type \"Tuple[Tuple[_T_co, ...], ...]\", variable has type \"Optional[List[List[BasePattern]]]\")  [assignment]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:357: error: Argument 1 to \"map\" has incompatible type \"Type[Tuple[Any, ...]]\"; expected \"Callable[[List[BasePattern]], Tuple[_T_co, ...]]\"  [arg-type]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:388: error: Incompatible types in assignment (expression has type \"List[Base]\", target has type \"Base\")  [assignment]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:397: error: Incompatible types in assignment (expression has type \"List[Base]\", target has type \"Base\")  [assignment]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:408: error: Incompatible types in assignment (expression has type \"List[Base]\", target has type \"Base\")  [assignment]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:413: error: Incompatible types in assignment (expression has type \"List[Base]\", target has type \"Base\")  [assignment]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:424: error: Item \"None\" of \"Optional[Any]\" has no attribute \"__iter__\" (not iterable)  [union-attr]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:432: error: Item \"None\" of \"Optional[Any]\" has no attribute \"__iter__\" (not iterable)  [union-attr]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:449: error: Item \"None\" of \"Optional[Any]\" has no attribute \"__iter__\" (not iterable)  [union-attr]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:454: error: Invalid index type \"Optional[str]\" for \"Dict[str, Base]\"; expected type \"str\"  [index]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:454: error: Incompatible types in assignment (expression has type \"List[Base]\", target has type \"Base\")  [assignment]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:476: error: Signature of \"match\" incompatible with supertype \"BasePattern\"  [override]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:476: note:      Superclass:",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:476: note:          def match(self, node: Base, results: Optional[Dict[str, Base]] = ...) -> bool",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:476: note:      Subclass:",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:476: note:          def match(self, node: Base) -> bool",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:479: error: Signature of \"match_seq\" incompatible with supertype \"BasePattern\"  [override]",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:479: note:      Superclass:",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:479: note:          def match_seq(self, nodes: List[Base], results: Optional[Dict[str, Base]] = ...) -> bool",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:479: note:      Subclass:",
            "pytree_b5c9498d48307fc20f4016a12676f355.py:479: note:          def match_seq(self, nodes: List[Base]) -> bool",
            "Found 37 errors in 1 file (checked 1 source file)"
        ]
    },
    "refactor_ba19b34abce9dfcf909394be809bc04a.py": {
        "stats": {
            "total_parameters": 87,
            "parameters_with_annotations": 61
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "refactor_ba19b34abce9dfcf909394be809bc04a.py:14: error: No parent module -- cannot perform relative import",
            "refactor_ba19b34abce9dfcf909394be809bc04a.py:15: error: No parent module -- cannot perform relative import",
            "Found 2 errors in 1 file (errors prevented further checking)"
        ]
    },
    "run_benchmark_05192c0c8d5a8999a8c094b2ecf40473.py": {
        "stats": {
            "total_parameters": 63,
            "parameters_with_annotations": 29
        },
        "error_count": 8,
        "isCompiled": false,
        "errors": [
            "run_benchmark_05192c0c8d5a8999a8c094b2ecf40473.py:129: error: \"set\" is not subscriptable, use \"typing.Set\" instead  [misc]",
            "run_benchmark_05192c0c8d5a8999a8c094b2ecf40473.py:211: error: \"Square\" has no attribute \"temp_ledges\"  [attr-defined]",
            "run_benchmark_05192c0c8d5a8999a8c094b2ecf40473.py:212: error: \"Square\" has no attribute \"temp_ledges\"  [attr-defined]",
            "run_benchmark_05192c0c8d5a8999a8c094b2ecf40473.py:213: error: \"Square\" has no attribute \"temp_ledges\"  [attr-defined]",
            "run_benchmark_05192c0c8d5a8999a8c094b2ecf40473.py:223: error: Incompatible return value type (got \"int\", expected \"bool\")  [return-value]",
            "run_benchmark_05192c0c8d5a8999a8c094b2ecf40473.py:359: error: Item \"None\" of \"Optional[UCTNode]\" has no attribute \"wins\"  [union-attr]",
            "run_benchmark_05192c0c8d5a8999a8c094b2ecf40473.py:359: error: Item \"None\" of \"Optional[UCTNode]\" has no attribute \"losses\"  [union-attr]",
            "run_benchmark_05192c0c8d5a8999a8c094b2ecf40473.py:394: error: Item \"None\" of \"Optional[UCTNode]\" has no attribute \"pos\"  [union-attr]",
            "Found 8 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_079afee64b38f3e4ec499d6009906612.py": {
        "stats": {
            "total_parameters": 2,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "run_benchmark_079afee64b38f3e4ec499d6009906612.py:20: error: Incompatible types in assignment (expression has type \"BytesIO\", variable has type \"BufferedReader\")  [assignment]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_083fc82df7d9596c7ee0e92cd5ab86ea.py": {
        "stats": {
            "total_parameters": 1,
            "parameters_with_annotations": 1
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_0ae4d57c5b86320985ca055ab916dace.py": {
        "stats": {
            "total_parameters": 5,
            "parameters_with_annotations": 5
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "run_benchmark_0ae4d57c5b86320985ca055ab916dace.py:15: error: \"object\" has no attribute \"generate\"  [attr-defined]",
            "run_benchmark_0ae4d57c5b86320985ca055ab916dace.py:20: error: \"object\" has no attribute \"benchmark\"  [attr-defined]",
            "run_benchmark_0ae4d57c5b86320985ca055ab916dace.py:21: error: \"object\" has no attribute \"benchmark\"  [attr-defined]",
            "run_benchmark_0ae4d57c5b86320985ca055ab916dace.py:36: error: Incompatible types in assignment (expression has type \"List[str]\", variable has type \"Tuple[Any]\")  [assignment]",
            "Found 4 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py": {
        "stats": {
            "total_parameters": 83,
            "parameters_with_annotations": 57
        },
        "error_count": 27,
        "isCompiled": false,
        "errors": [
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:29: error: Value of type \"Optional[List[List[int]]]\" is not indexable  [index]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:33: error: Value of type \"Optional[List[List[int]]]\" is not indexable  [index]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:36: error: Unsupported target for indexed assignment (\"Optional[List[List[int]]]\")  [index]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:39: error: Value of type \"Optional[List[List[int]]]\" is not indexable  [index]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:42: error: Value of type \"Optional[List[List[int]]]\" is not indexable  [index]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:43: error: Value of type \"Optional[List[List[int]]]\" is not indexable  [index]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:69: error: Value of type \"Optional[List[List[int]]]\" is not indexable  [index]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:70: error: Value of type \"Optional[List[List[int]]]\" is not indexable  [index]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:78: error: Value of type \"Optional[List[List[int]]]\" is not indexable  [index]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:79: error: Value of type \"Optional[List[List[int]]]\" is not indexable  [index]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:88: error: Value of type \"Optional[List[List[int]]]\" is not indexable  [index]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:158: error: No overload variant of \"__setitem__\" of \"list\" matches argument types \"int\", \"Node\"  [call-overload]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:158: note: Possible overload variants:",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:158: note:     def __setitem__(self, SupportsIndex, None, /) -> None",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:158: note:     def __setitem__(self, slice, Iterable[None], /) -> None",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:166: error: No overload variant of \"__setitem__\" of \"list\" matches argument types \"int\", \"Node\"  [call-overload]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:166: note: Possible overload variants:",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:166: note:     def __setitem__(self, SupportsIndex, None, /) -> None",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:166: note:     def __setitem__(self, slice, Iterable[None], /) -> None",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:171: error: \"None\" has no attribute \"pos\"  [attr-defined]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:176: error: \"None\" has no attribute \"links\"  [attr-defined]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:185: error: Incompatible return value type (got \"None\", expected \"Node\")  [return-value]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:217: error: Item \"None\" of \"Optional[List[List[int]]]\" has no attribute \"__iter__\" (not iterable)  [union-attr]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:225: error: Generator has incompatible item type \"int\"; expected \"bool\"  [misc]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:225: error: Item \"None\" of \"Optional[List[List[int]]]\" has no attribute \"__iter__\" (not iterable)  [union-attr]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:228: error: Value of type \"Optional[List[List[int]]]\" is not indexable  [index]",
            "run_benchmark_101bb04648591f38cbb42eaf6aba3288.py:456: error: Incompatible types in assignment (expression has type \"None\", variable has type \"StringIO\")  [assignment]",
            "Found 21 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_14b1aad8ef40880d34ce019b57e1dd81.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "run_benchmark_14b1aad8ef40880d34ce019b57e1dd81.py:37: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "run_benchmark_17dc7effd52ebd41c89a16fb84ba976e.py": {
        "stats": {
            "total_parameters": 17,
            "parameters_with_annotations": 13
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "run_benchmark_17dc7effd52ebd41c89a16fb84ba976e.py:62: error: Need type annotation for \"stats\"  [var-annotated]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_1be7503fa8723e91833eb80f31228737.py": {
        "stats": {
            "total_parameters": 2,
            "parameters_with_annotations": 2
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_1efa63cfa255cc633c18f7dce4818351.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 3
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_21026ff8f81b122e6c9cfbf8c29a27cb.py": {
        "stats": {
            "total_parameters": 5,
            "parameters_with_annotations": 4
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "run_benchmark_21026ff8f81b122e6c9cfbf8c29a27cb.py:29: error: Item \"None\" of \"Optional[Tree]\" has no attribute \"__aiter__\" (not async iterable)  [union-attr]",
            "run_benchmark_21026ff8f81b122e6c9cfbf8c29a27cb.py:29: error: Argument 1 to \"tree\" has incompatible type \"range\"; expected \"List[int]\"  [arg-type]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_26727fba89826eeafa7ccc4e1e90c284.py": {
        "stats": {
            "total_parameters": 4,
            "parameters_with_annotations": 3
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_268e2f631afb81a04deab49d7cf3fb46.py": {
        "stats": {
            "total_parameters": 4,
            "parameters_with_annotations": 4
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "run_benchmark_268e2f631afb81a04deab49d7cf3fb46.py:36: error: \"object\" has no attribute \"benchmark\"  [attr-defined]",
            "run_benchmark_268e2f631afb81a04deab49d7cf3fb46.py:37: error: \"object\" has no attribute \"benchmark\"  [attr-defined]",
            "run_benchmark_268e2f631afb81a04deab49d7cf3fb46.py:49: error: Incompatible types in assignment (expression has type \"Tuple[str, ...]\", variable has type \"Tuple[Any]\")  [assignment]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_293989a6d5e7f93e90fe279a3c2f7db9.py": {
        "stats": {
            "total_parameters": 5,
            "parameters_with_annotations": 5
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_2d2b8b8374ccfc0f944485cd5da03ebc.py": {
        "stats": {
            "total_parameters": 1,
            "parameters_with_annotations": 1
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_34494d3bb60355e7d1a04faddcfffc1d.py": {
        "stats": {
            "total_parameters": 8,
            "parameters_with_annotations": 8
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "run_benchmark_34494d3bb60355e7d1a04faddcfffc1d.py:17: error: Incompatible return value type (got \"Optional[Match[str]]\", expected \"Match[Any]\")  [return-value]",
            "run_benchmark_34494d3bb60355e7d1a04faddcfffc1d.py:23: error: Incompatible types in assignment (expression has type \"Callable[[str, int], Pattern[Any]]\", variable has type overloaded function)  [assignment]",
            "run_benchmark_34494d3bb60355e7d1a04faddcfffc1d.py:24: error: Incompatible types in assignment (expression has type \"Callable[[str, str, int], Match[Any]]\", variable has type overloaded function)  [assignment]",
            "run_benchmark_34494d3bb60355e7d1a04faddcfffc1d.py:25: error: Incompatible types in assignment (expression has type \"Callable[[str, VarArg(Any)], str]\", variable has type overloaded function)  [assignment]",
            "Found 4 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_35477730ea622662cb6c95ff69a68e99.py": {
        "stats": {
            "total_parameters": 25,
            "parameters_with_annotations": 17
        },
        "error_count": 14,
        "isCompiled": false,
        "errors": [
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:12: error: Name \"etree\" is not defined  [name-defined]",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:27: error: Name \"etree\" is not defined  [name-defined]",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:64: error: Need type annotation for \"d\"  [var-annotated]",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:83: error: Name \"etree\" is not defined  [name-defined]",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:93: error: Name \"etree\" is not defined  [name-defined]",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:102: error: Name \"etree\" is not defined  [name-defined]",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:108: error: Name \"etree\" is not defined  [name-defined]",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:167: error: Incompatible types in assignment (expression has type \"None\", target has type Module)  [assignment]",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:175: error: All conditional function variants must have identical signatures  [misc]",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:175: note: Original:",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:175: note:     def import_module(name: str, package: Optional[str] = ...) -> Module",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:175: note: Redefinition:",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:175: note:     def import_module(module_name: str) -> Any",
            "run_benchmark_35477730ea622662cb6c95ff69a68e99.py:199: error: Incompatible types in assignment (expression has type \"List[str]\", variable has type \"Tuple[Any]\")  [assignment]",
            "Found 10 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_41759fdf0401f89c962cc7b114aa3e42.py": {
        "stats": {
            "total_parameters": 1,
            "parameters_with_annotations": 1
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_432ac9707ee16dffc2f2fe3f1c6bf76c.py": {
        "stats": {
            "total_parameters": 20,
            "parameters_with_annotations": 20
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "run_benchmark_432ac9707ee16dffc2f2fe3f1c6bf76c.py:213: error: Incompatible types in assignment (expression has type \"None\", target has type Module)  [assignment]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py": {
        "stats": {
            "total_parameters": 115,
            "parameters_with_annotations": 53
        },
        "error_count": 46,
        "isCompiled": false,
        "errors": [
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:65: error: \"Constraint\" has no attribute \"add_to_graph\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:66: error: Item \"None\" of \"Optional[Planner]\" has no attribute \"incremental_add\"  [union-attr]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:70: error: \"Constraint\" has no attribute \"choose_method\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:71: error: \"Constraint\" has no attribute \"is_satisfied\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:75: error: \"Constraint\" has no attribute \"mark_inputs\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:76: error: \"Constraint\" has no attribute \"output\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:81: error: Item \"None\" of \"Optional[Planner]\" has no attribute \"add_propagate\"  [union-attr]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:88: error: \"Constraint\" has no attribute \"is_satisfied\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:89: error: Item \"None\" of \"Optional[Planner]\" has no attribute \"incremental_remove\"  [union-attr]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:91: error: \"Constraint\" has no attribute \"remove_from_graph\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:108: error: Argument 2 to \"stronger\" of \"Strength\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:126: error: \"UrnaryConstraint\" has no attribute \"execute\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:171: error: Argument 2 to \"stronger\" of \"Strength\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:176: error: Argument 2 to \"stronger\" of \"Strength\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:180: error: Argument 1 to \"weaker\" of \"Strength\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:180: error: Argument 2 to \"weaker\" of \"Strength\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:181: error: Argument 2 to \"stronger\" of \"Strength\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:185: error: Argument 2 to \"stronger\" of \"Strength\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:214: error: Argument 2 to \"weakest_of\" of \"Strength\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:217: error: \"BinaryConstraint\" has no attribute \"execute\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:261: error: Incompatible types in assignment (expression has type \"float\", variable has type \"int\")  [assignment]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:266: error: Argument 2 to \"weakest_of\" of \"Strength\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:307: error: \"Constraint\" has no attribute \"output\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:308: error: \"Constraint\" has no attribute \"mark_unsatisfied\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:309: error: \"Constraint\" has no attribute \"remove_from_graph\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:317: error: Item \"None\" of \"Optional[Strength]\" has no attribute \"next_weaker\"  [union-attr]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:330: error: \"Constraint\" has no attribute \"output\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:330: error: \"Constraint\" has no attribute \"inputs_known\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:332: error: \"Constraint\" has no attribute \"output\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:333: error: \"Constraint\" has no attribute \"output\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:339: error: \"Constraint\" has no attribute \"is_satisfied\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:378: error: \"Constraint\" has no attribute \"is_satisfied\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:396: error: \"Constraint\" has no attribute \"execute\"  [attr-defined]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:408: error: Argument 3 to \"EqualityConstraint\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:414: error: Argument 1 to \"StayConstraint\" has incompatible type \"Optional[Variable]\"; expected \"Variable\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:414: error: Argument 2 to \"StayConstraint\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:415: error: Argument 1 to \"EditConstraint\" has incompatible type \"Optional[Variable]\"; expected \"Variable\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:415: error: Argument 2 to \"EditConstraint\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:420: error: Item \"None\" of \"Optional[Variable]\" has no attribute \"value\"  [union-attr]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:422: error: Item \"None\" of \"Optional[Variable]\" has no attribute \"value\"  [union-attr]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:436: error: Argument 2 to \"StayConstraint\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:437: error: Argument 5 to \"ScaleConstraint\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:438: error: Argument 1 to \"change\" has incompatible type \"Optional[Variable]\"; expected \"Variable\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:442: error: Item \"None\" of \"Optional[Variable]\" has no attribute \"value\"  [union-attr]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:455: error: Argument 2 to \"EditConstraint\" has incompatible type \"Optional[Strength]\"; expected \"Strength\"  [arg-type]",
            "run_benchmark_54d6e19c1743b019edc613e74d8321ba.py:458: error: Item \"None\" of \"Optional[Planner]\" has no attribute \"extract_plan_from_constraints\"  [union-attr]",
            "Found 46 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_5f738045810f54167c085e1c7e0b35b8.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 3
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_6021b120af897a98b208540880d31fa1.py": {
        "stats": {
            "total_parameters": 7,
            "parameters_with_annotations": 7
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_64e361fd1586e053709bd8ec787fefaf.py": {
        "stats": {
            "total_parameters": 4,
            "parameters_with_annotations": 4
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_64f067051f53db8fe8e69329b3e087ed.py": {
        "stats": {
            "total_parameters": 1,
            "parameters_with_annotations": 1
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_6c16d199d98991cfd04b86f116962777.py": {
        "stats": {
            "total_parameters": 1,
            "parameters_with_annotations": 1
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "run_benchmark_6c16d199d98991cfd04b86f116962777.py:29: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py": {
        "stats": {
            "total_parameters": 73,
            "parameters_with_annotations": 48
        },
        "error_count": 33,
        "isCompiled": false,
        "errors": [
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:13: error: Cannot determine type of \"f\"  [has-type]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:14: error: Cannot determine type of \"bits\"  [has-type]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:15: error: Cannot determine type of \"bitfield\"  [has-type]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:26: error: Exception must be derived from BaseException  [misc]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:32: error: \"BitfieldBase\" has no attribute \"_more\"  [attr-defined]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:41: error: \"BitfieldBase\" has no attribute \"readbits\"  [attr-defined]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:49: error: \"BitfieldBase\" has no attribute \"readbits\"  [attr-defined]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:171: error: Incompatible types in assignment (expression has type \"int\", variable has type \"None\")  [assignment]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:172: error: Incompatible types in assignment (expression has type \"int\", variable has type \"None\")  [assignment]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:175: error: Need type annotation for \"d\" (hint: \"d: Dict[<type>, <type>] = ...\")  [var-annotated]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:201: error: \"BitfieldBase\" has no attribute \"snoopbits\"  [attr-defined]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:204: error: \"BitfieldBase\" has no attribute \"readbits\"  [attr-defined]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:237: error: Exception must be derived from BaseException  [misc]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:245: error: Exception must be derived from BaseException  [misc]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:297: error: Exception must be derived from BaseException  [misc]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:310: error: Exception must be derived from BaseException  [misc]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:326: error: Exception must be derived from BaseException  [misc]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:348: error: Item \"None\" of \"Optional[OrderedHuffmanTable]\" has no attribute \"find_next_symbol\"  [union-attr]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:362: error: Argument 1 to \"move_to_front\" has incompatible type \"List[bytes]\"; expected \"List[int]\"  [arg-type]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:385: error: Need type annotation for \"out\" (hint: \"out: List[<type>] = ...\")  [var-annotated]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:446: error: Need type annotation for \"code_lengths\" (hint: \"code_lengths: List[<type>] = ...\")  [var-annotated]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:468: error: Item \"None\" of \"Optional[HuffmanTable]\" has no attribute \"populate_huffman_symbols\"  [union-attr]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:469: error: Item \"None\" of \"Optional[HuffmanTable]\" has no attribute \"populate_huffman_symbols\"  [union-attr]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:470: error: Item \"None\" of \"Optional[HuffmanTable]\" has no attribute \"min_max_bits\"  [union-attr]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:471: error: Item \"None\" of \"Optional[HuffmanTable]\" has no attribute \"min_max_bits\"  [union-attr]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:474: error: Item \"None\" of \"Optional[HuffmanTable]\" has no attribute \"find_next_symbol\"  [union-attr]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:487: error: Item \"None\" of \"Optional[HuffmanTable]\" has no attribute \"find_next_symbol\"  [union-attr]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:508: error: Argument 1 to \"join\" of \"str\" has incompatible type \"List[bytes]\"; expected \"Iterable[str]\"  [arg-type]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:516: error: Argument 1 to \"RBitfield\" has incompatible type \"BufferedReader\"; expected \"Union[BitfieldBase, bytes]\"  [arg-type]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:519: error: Argument 1 to \"gzip_main\" has incompatible type \"RBitfield\"; expected \"bytes\"  [arg-type]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:521: error: Incompatible types in assignment (expression has type \"bytes\", variable has type \"str\")  [assignment]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:521: error: Argument 1 to \"bzip2_main\" has incompatible type \"RBitfield\"; expected \"bytes\"  [arg-type]",
            "run_benchmark_735d8e18ff99fd95e3e85b3a045a96ff.py:526: error: Argument 1 to \"md5\" has incompatible type \"str\"; expected \"Buffer\"  [arg-type]",
            "Found 33 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_7465a3358d6be0a308ff0dba1c019896.py": {
        "stats": {
            "total_parameters": 2,
            "parameters_with_annotations": 2
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_74e46dc7e24ad277a3ffd520c33499c2.py": {
        "stats": {
            "total_parameters": 4,
            "parameters_with_annotations": 3
        },
        "error_count": 6,
        "isCompiled": false,
        "errors": [
            "run_benchmark_74e46dc7e24ad277a3ffd520c33499c2.py:10: error: Variable \"run_benchmark_74e46dc7e24ad277a3ffd520c33499c2.Base\" is not valid as a type  [valid-type]",
            "run_benchmark_74e46dc7e24ad277a3ffd520c33499c2.py:10: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases",
            "run_benchmark_74e46dc7e24ad277a3ffd520c33499c2.py:10: error: Invalid base class \"Base\"  [misc]",
            "run_benchmark_74e46dc7e24ad277a3ffd520c33499c2.py:15: error: Variable \"run_benchmark_74e46dc7e24ad277a3ffd520c33499c2.Base\" is not valid as a type  [valid-type]",
            "run_benchmark_74e46dc7e24ad277a3ffd520c33499c2.py:15: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases",
            "run_benchmark_74e46dc7e24ad277a3ffd520c33499c2.py:15: error: Invalid base class \"Base\"  [misc]",
            "Found 4 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_79b0563155ae7c19376dd17a256bd4c9.py": {
        "stats": {
            "total_parameters": 4,
            "parameters_with_annotations": 2
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "run_benchmark_79b0563155ae7c19376dd17a256bd4c9.py:21: error: The return type of a generator function should be \"Generator\" or one of its supertypes  [misc]",
            "run_benchmark_79b0563155ae7c19376dd17a256bd4c9.py:47: error: The return type of a generator function should be \"Generator\" or one of its supertypes  [misc]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_7e52e6cf6b6ac0c8c20602f1713d3f9e.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_9196e0e1a8569bc4d538f9e91f44380b.py": {
        "stats": {
            "total_parameters": 7,
            "parameters_with_annotations": 5
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "run_benchmark_9196e0e1a8569bc4d538f9e91f44380b.py:27: error: Argument 1 to \"list\" has incompatible type \"Optional[Tree]\"; expected \"Iterable[int]\"  [arg-type]",
            "run_benchmark_9196e0e1a8569bc4d538f9e91f44380b.py:27: error: Argument 1 to \"tree\" has incompatible type \"range\"; expected \"List[int]\"  [arg-type]",
            "run_benchmark_9196e0e1a8569bc4d538f9e91f44380b.py:29: error: Argument 1 to \"tree\" has incompatible type \"range\"; expected \"List[int]\"  [arg-type]",
            "run_benchmark_9196e0e1a8569bc4d538f9e91f44380b.py:32: error: Item \"None\" of \"Optional[Tree]\" has no attribute \"__iter__\" (not iterable)  [union-attr]",
            "Found 4 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_9473d82c1ad213cf726be7d21540b9f3.py": {
        "stats": {
            "total_parameters": 6,
            "parameters_with_annotations": 5
        },
        "error_count": 6,
        "isCompiled": false,
        "errors": [
            "run_benchmark_9473d82c1ad213cf726be7d21540b9f3.py:37: error: Module has no attribute \"TaskGroup\"  [attr-defined]",
            "run_benchmark_9473d82c1ad213cf726be7d21540b9f3.py:52: error: \"run\" undefined in superclass  [misc]",
            "run_benchmark_9473d82c1ad213cf726be7d21540b9f3.py:69: error: Return type \"Coroutine[Any, Any, int]\" of \"workload_func\" incompatible with return type \"Coroutine[Any, Any, None]\" in supertype \"AsyncTree\"  [override]",
            "run_benchmark_9473d82c1ad213cf726be7d21540b9f3.py:82: error: Return type \"Coroutine[Any, Any, int]\" of \"workload_func\" incompatible with return type \"Coroutine[Any, Any, None]\" in supertype \"AsyncTree\"  [override]",
            "run_benchmark_9473d82c1ad213cf726be7d21540b9f3.py:101: error: Name \"argparse\" is not defined  [name-defined]",
            "run_benchmark_9473d82c1ad213cf726be7d21540b9f3.py:106: error: Name \"argparse\" is not defined  [name-defined]",
            "Found 6 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_958ac12d9a928de9aad6c1b814c51ef7.py": {
        "stats": {
            "total_parameters": 51,
            "parameters_with_annotations": 28
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "run_benchmark_958ac12d9a928de9aad6c1b814c51ef7.py:103: error: Incompatible types in assignment (expression has type \"float\", variable has type \"int\")  [assignment]",
            "run_benchmark_958ac12d9a928de9aad6c1b814c51ef7.py:146: error: Incompatible types in assignment (expression has type \"float\", variable has type \"int\")  [assignment]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_95edf135ddae7bd47dbd5e98374098f5.py": {
        "stats": {
            "total_parameters": 1,
            "parameters_with_annotations": 1
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_97b7db16323aeacce0598574c19d7dc4.py": {
        "stats": {
            "total_parameters": 4,
            "parameters_with_annotations": 4
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_a245e0361625bbc6129c2b1ec112e9db.py": {
        "stats": {
            "total_parameters": 7,
            "parameters_with_annotations": 6
        },
        "error_count": 5,
        "isCompiled": false,
        "errors": [
            "run_benchmark_a245e0361625bbc6129c2b1ec112e9db.py:45: error: Argument 1 to \"append\" of \"list\" has incompatible type \"str\"; expected \"bytes\"  [arg-type]",
            "run_benchmark_a245e0361625bbc6129c2b1ec112e9db.py:84: error: \"Callable[[int], float]\" has no attribute \"data\"  [attr-defined]",
            "run_benchmark_a245e0361625bbc6129c2b1ec112e9db.py:85: error: \"Callable[[int], float]\" has no attribute \"data\"  [attr-defined]",
            "run_benchmark_a245e0361625bbc6129c2b1ec112e9db.py:86: error: \"Callable[[int], float]\" has no attribute \"data\"  [attr-defined]",
            "run_benchmark_a245e0361625bbc6129c2b1ec112e9db.py:103: error: \"Callable[[int], float]\" has no attribute \"data\"  [attr-defined]",
            "Found 5 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_a28c6e02f54a08e0b801c4930e06d67b.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "run_benchmark_a28c6e02f54a08e0b801c4930e06d67b.py:11: error: X | Y syntax for unions requires Python 3.10  [syntax]",
            "run_benchmark_a28c6e02f54a08e0b801c4930e06d67b.py:16: error: Item \"None\" of \"Optional[Event]\" has no attribute \"set\"  [union-attr]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_a33097bd5241761d2d3d046b36d9afd4.py": {
        "stats": {
            "total_parameters": 10,
            "parameters_with_annotations": 6
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "run_benchmark_a33097bd5241761d2d3d046b36d9afd4.py:31: error: Incompatible return value type (got \"Optional[bool]\", expected \"bool\")  [return-value]",
            "run_benchmark_a33097bd5241761d2d3d046b36d9afd4.py:36: error: Item \"None\" of \"Optional[List[int]]\" has no attribute \"__iter__\" (not iterable)  [union-attr]",
            "run_benchmark_a33097bd5241761d2d3d046b36d9afd4.py:49: error: Argument 3 to \"Widget\" has incompatible type \"List[Optional[int]]\"; expected \"Optional[List[int]]\"  [arg-type]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_a55d3dd13b512cfe214145c5e92afdc6.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 3
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_a98f596fc7b09c623910e5db7e8f8ffc.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_ad565b18eba62edc0cc5a53f755fbc29.py": {
        "stats": {
            "total_parameters": 7,
            "parameters_with_annotations": 7
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_b26b9b306d7c5987b898c17b5ef45275.py": {
        "stats": {
            "total_parameters": 5,
            "parameters_with_annotations": 2
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "run_benchmark_b26b9b306d7c5987b898c17b5ef45275.py:29: error: Argument 3 to \"create_aggregate\" of \"Connection\" has incompatible type \"Type[AvgLength]\"; expected \"Callable[[], _AggregateProtocol]\"  [arg-type]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py": {
        "stats": {
            "total_parameters": 114,
            "parameters_with_annotations": 60
        },
        "error_count": 33,
        "isCompiled": false,
        "errors": [
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:77: error: \"Type[Vector]\" has no attribute \"ZERO\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:78: error: \"Type[Vector]\" has no attribute \"RIGHT\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:79: error: \"Type[Vector]\" has no attribute \"UP\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:80: error: \"Type[Vector]\" has no attribute \"OUT\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:81: error: \"Type[Vector]\" has no attribute \"RIGHT\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:81: error: \"Type[Vector]\" has no attribute \"UP\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:82: error: \"Type[Vector]\" has no attribute \"UP\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:136: error: Item \"Point\" of \"Union[Vector, Point]\" has no attribute \"dot\"  [union-attr]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:137: error: Item \"Point\" of \"Union[Vector, Point]\" has no attribute \"dot\"  [union-attr]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:137: error: Argument 1 to \"dot\" of \"Vector\" has incompatible type \"Union[Vector, Point]\"; expected \"Vector\"  [arg-type]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:144: error: Item \"Point\" of \"Union[Vector, Point]\" has no attribute \"normalized\"  [union-attr]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:181: error: \"Type[Point]\" has no attribute \"ZERO\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:214: error: Incompatible return value type (got \"Optional[Tuple[object, Optional[float], object]]\", expected \"Optional[Tuple[object, float, object]]\")  [return-value]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:228: error: \"Type[Point]\" has no attribute \"ZERO\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:252: error: Argument 2 to \"Ray\" has incompatible type \"Union[Vector, Point]\"; expected \"Vector\"  [arg-type]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:253: error: \"Type[Vector]\" has no attribute \"UP\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:259: error: Argument 2 to \"Ray\" has incompatible type \"Union[Vector, Point]\"; expected \"Vector\"  [arg-type]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:268: error: \"object\" has no attribute \"intersectionTime\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:275: error: \"object\" has no attribute \"colourAt\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:275: error: \"object\" has no attribute \"normalAt\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:281: error: \"object\" has no attribute \"intersectionTime\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:281: error: Argument 2 to \"Ray\" has incompatible type \"Union[Vector, Point]\"; expected \"Vector\"  [arg-type]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:317: error: Incompatible types in assignment (expression has type \"Tuple[float, float, float]\", variable has type \"Tuple[int, int, int]\")  [assignment]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:321: error: Item \"Point\" of \"Union[Vector, Point]\" has no attribute \"normalized\"  [union-attr]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:323: error: Incompatible types in assignment (expression has type \"Union[float, Any]\", variable has type \"int\")  [assignment]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:325: error: Incompatible types in assignment (expression has type \"Tuple[float, float, float]\", variable has type \"Tuple[int, int, int]\")  [assignment]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:327: error: Incompatible types in assignment (expression has type \"Tuple[float, float, float]\", variable has type \"Tuple[int, int, int]\")  [assignment]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:340: error: \"Type[Point]\" has no attribute \"ZERO\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:359: error: \"Type[Vector]\" has no attribute \"UP\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:367: error: \"object\" has no attribute \"width\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:368: error: \"object\" has no attribute \"height\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:369: error: \"object\" has no attribute \"filename\"  [attr-defined]",
            "run_benchmark_b89518a404d01c8afa20b38d197e3f9a.py:370: error: \"object\" has no attribute \"filename\"  [attr-defined]",
            "Found 33 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_ba302be588b03433d3833330ef334694.py": {
        "stats": {
            "total_parameters": 1,
            "parameters_with_annotations": 1
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "run_benchmark_ba302be588b03433d3833330ef334694.py:14: error: Incompatible types in assignment (expression has type \"Coroutine[Any, Any, int]\", variable has type \"Generator[None, None, int]\")  [assignment]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_bbaface73b5271d284816da26ab45a2e.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 3
        },
        "error_count": 5,
        "isCompiled": false,
        "errors": [
            "run_benchmark_bbaface73b5271d284816da26ab45a2e.py:4: error: Library stubs not installed for \"docutils\"  [import]",
            "run_benchmark_bbaface73b5271d284816da26ab45a2e.py:10: error: Library stubs not installed for \"docutils.utils.math.math2html\"  [import]",
            "run_benchmark_bbaface73b5271d284816da26ab45a2e.py:10: note: Hint: \"python3 -m pip install types-docutils\"",
            "run_benchmark_bbaface73b5271d284816da26ab45a2e.py:10: note: (or run \"mypy --install-types\" to install all missing stub packages)",
            "run_benchmark_bbaface73b5271d284816da26ab45a2e.py:10: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_c193048bf6974d42edd1a8e1d38d51fa.py": {
        "stats": {
            "total_parameters": 16,
            "parameters_with_annotations": 15
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_ca073e899d60ce995a3685d97078e2ed.py": {
        "stats": {
            "total_parameters": 2,
            "parameters_with_annotations": 1
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "run_benchmark_ca073e899d60ce995a3685d97078e2ed.py:31: error: Incompatible types in assignment (expression has type \"None\", variable has type \"SSLContext\")  [assignment]",
            "run_benchmark_ca073e899d60ce995a3685d97078e2ed.py:32: error: Incompatible types in assignment (expression has type \"None\", variable has type \"SSLContext\")  [assignment]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_cca3b64b92d026f4feb24fcec90fe159.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "run_benchmark_cca3b64b92d026f4feb24fcec90fe159.py:12: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "run_benchmark_ce0e39f2be42224684270a194a2fe3b4.py": {
        "stats": {
            "total_parameters": 18,
            "parameters_with_annotations": 17
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "run_benchmark_ce0e39f2be42224684270a194a2fe3b4.py:36: error: Incompatible types in assignment (expression has type \"List[Tuple[Any, ...]]\", variable has type \"List[Tuple[Tuple[List[float], List[float], float], Tuple[List[float], List[float], float]]]\")  [assignment]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_d0531dbcb196b002efdeaa7a81b1fd9c.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_d55e5927075139a1ac0cc6dbe7fee59b.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 3
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py": {
        "stats": {
            "total_parameters": 13,
            "parameters_with_annotations": 12
        },
        "error_count": 13,
        "isCompiled": false,
        "errors": [
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:17: error: Incompatible types in assignment (expression has type \"bytes\", target has type \"Union[BytesIO, StringIO]\")  [assignment]",
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:19: error: Incompatible default for argument \"encoding\" (default has type \"None\", argument has type \"str\")  [assignment]",
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:19: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True",
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:19: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase",
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:19: error: Incompatible default for argument \"errors\" (default has type \"None\", argument has type \"str\")  [assignment]",
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:19: error: Incompatible default for argument \"newline\" (default has type \"None\", argument has type \"str\")  [assignment]",
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:25: error: Argument 1 to \"BytesIO\" has incompatible type \"Union[BytesIO, StringIO]\"; expected \"Buffer\"  [arg-type]",
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:27: error: Item \"BytesIO\" of \"Union[BytesIO, StringIO]\" has no attribute \"decode\"  [union-attr]",
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:27: error: Item \"StringIO\" of \"Union[BytesIO, StringIO]\" has no attribute \"decode\"  [union-attr]",
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:32: error: Incompatible types in assignment (expression has type \"StringIO\", variable has type \"BytesIO\")  [assignment]",
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:35: error: Incompatible return value type (got \"IO[Any]\", expected \"Union[BytesIO, StringIO, TextIOWrapper]\")  [return-value]",
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:36: error: Incompatible types in assignment (expression has type \"Callable[[Union[str, Path], str, int, str, str, str, bool, Any], Union[BytesIO, StringIO, TextIOWrapper]]\", variable has type overloaded function)  [assignment]",
            "run_benchmark_d5780ee905aac0d8545a6b5d3e1c3af6.py:40: error: Incompatible types in assignment (expression has type \"Callable[[str, str], None]\", variable has type \"Callable[[Union[str, bytes, PathLike[str], PathLike[bytes]], Union[str, bytes, PathLike[str], PathLike[bytes]], DefaultNamedArg(Optional[int], 'src_dir_fd'), DefaultNamedArg(Optional[int], 'dst_dir_fd')], None]\")  [assignment]",
            "Found 11 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_d7485f1540815ff9846e47c93bb7b997.py": {
        "stats": {
            "total_parameters": 85,
            "parameters_with_annotations": 48
        },
        "error_count": 6,
        "isCompiled": false,
        "errors": [
            "run_benchmark_d7485f1540815ff9846e47c93bb7b997.py:21: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]",
            "run_benchmark_d7485f1540815ff9846e47c93bb7b997.py:126: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]",
            "run_benchmark_d7485f1540815ff9846e47c93bb7b997.py:163: error: Item \"None\" of \"Optional[Packet]\" has no attribute \"link\"  [union-attr]",
            "run_benchmark_d7485f1540815ff9846e47c93bb7b997.py:219: error: Argument 1 to \"trace\" has incompatible type \"int\"; expected \"str\"  [arg-type]",
            "run_benchmark_d7485f1540815ff9846e47c93bb7b997.py:308: error: Argument 3 to \"IdleTask\" has incompatible type \"int\"; expected \"Optional[Packet]\"  [arg-type]",
            "run_benchmark_d7485f1540815ff9846e47c93bb7b997.py:320: error: Incompatible types in assignment (expression has type \"None\", variable has type \"Packet\")  [assignment]",
            "Found 6 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_db768e7124854f442d014d84437038ed.py": {
        "stats": {
            "total_parameters": 85,
            "parameters_with_annotations": 48
        },
        "error_count": 7,
        "isCompiled": false,
        "errors": [
            "run_benchmark_db768e7124854f442d014d84437038ed.py:21: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]",
            "run_benchmark_db768e7124854f442d014d84437038ed.py:126: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]",
            "run_benchmark_db768e7124854f442d014d84437038ed.py:148: error: Missing return statement  [return]",
            "run_benchmark_db768e7124854f442d014d84437038ed.py:164: error: Item \"None\" of \"Optional[Packet]\" has no attribute \"link\"  [union-attr]",
            "run_benchmark_db768e7124854f442d014d84437038ed.py:221: error: Argument 1 to \"trace\" has incompatible type \"int\"; expected \"str\"  [arg-type]",
            "run_benchmark_db768e7124854f442d014d84437038ed.py:313: error: Argument 3 to \"IdleTask\" has incompatible type \"int\"; expected \"Optional[Packet]\"  [arg-type]",
            "run_benchmark_db768e7124854f442d014d84437038ed.py:325: error: Incompatible types in assignment (expression has type \"None\", variable has type \"Packet\")  [assignment]",
            "Found 7 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_dc3dd40536a1de9023f8266cf6fdbfe8.py": {
        "stats": {
            "total_parameters": 49,
            "parameters_with_annotations": 41
        },
        "error_count": 9,
        "isCompiled": false,
        "errors": [
            "run_benchmark_dc3dd40536a1de9023f8266cf6fdbfe8.py:104: error: The return type of a generator function should be \"Generator\" or one of its supertypes  [misc]",
            "run_benchmark_dc3dd40536a1de9023f8266cf6fdbfe8.py:116: error: Incompatible types in assignment (expression has type \"Tuple[int, Tuple[halfstate_t, halfstate_t, int], int, str]\", variable has type \"Tuple[int, bool]\")  [assignment]",
            "run_benchmark_dc3dd40536a1de9023f8266cf6fdbfe8.py:143: error: Incompatible types in assignment (expression has type \"Tuple[int, Tuple[halfstate_t, halfstate_t, int]]\", variable has type \"Tuple[int, bool]\")  [assignment]",
            "run_benchmark_dc3dd40536a1de9023f8266cf6fdbfe8.py:153: error: Argument 1 to \"_getSuccessorsA\" of \"Battle\" has incompatible type \"Tuple[Any, ...]\"; expected \"Tuple[int, Tuple[halfstate_t, halfstate_t, int]]\"  [arg-type]",
            "run_benchmark_dc3dd40536a1de9023f8266cf6fdbfe8.py:156: error: Argument 1 to \"_getSuccessorsB\" of \"Battle\" has incompatible type \"Tuple[Any, ...]\"; expected \"Tuple[int, Tuple[halfstate_t, halfstate_t, int], str]\"  [arg-type]",
            "run_benchmark_dc3dd40536a1de9023f8266cf6fdbfe8.py:158: error: Argument 1 to \"_getSuccessorsC\" of \"Battle\" has incompatible type \"Tuple[Any, ...]\"; expected \"Tuple[int, Tuple[halfstate_t, halfstate_t, int], int, str]\"  [arg-type]",
            "run_benchmark_dc3dd40536a1de9023f8266cf6fdbfe8.py:159: error: Argument 1 to \"sorted\" has incompatible type \"dict_items[Tuple[Any, ...], float]\"; expected \"Iterable[Tuple[int, Tuple[halfstate_t, halfstate_t, int], str]]\"  [arg-type]",
            "run_benchmark_dc3dd40536a1de9023f8266cf6fdbfe8.py:159: error: Unsupported operand type for unary - (\"Tuple[halfstate_t, halfstate_t, int]\")  [operator]",
            "run_benchmark_dc3dd40536a1de9023f8266cf6fdbfe8.py:169: error: Incompatible return value type (got \"Union[List[Any], Dict[Any, Any]]\", expected \"List[Any]\")  [return-value]",
            "Found 9 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_dff26d535b0e89b50097c808066750ec.py": {
        "stats": {
            "total_parameters": 31,
            "parameters_with_annotations": 28
        },
        "error_count": 5,
        "isCompiled": false,
        "errors": [
            "run_benchmark_dff26d535b0e89b50097c808066750ec.py:34: error: Argument 1 to \"append\" of \"list\" has incompatible type \"float\"; expected \"int\"  [arg-type]",
            "run_benchmark_dff26d535b0e89b50097c808066750ec.py:38: error: Need type annotation for \"fps\"  [var-annotated]",
            "run_benchmark_dff26d535b0e89b50097c808066750ec.py:42: error: Invalid index type \"float\" for \"Dict[int, int]\"; expected type \"int\"  [index]",
            "run_benchmark_dff26d535b0e89b50097c808066750ec.py:52: error: Invalid index type \"float\" for \"Dict[int, int]\"; expected type \"int\"  [index]",
            "run_benchmark_dff26d535b0e89b50097c808066750ec.py:96: error: Need type annotation for \"solutions\" (hint: \"solutions: List[<type>] = ...\")  [var-annotated]",
            "Found 5 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_e13886742d29f7347d4ce5fd3df9e7ac.py": {
        "stats": {
            "total_parameters": 1,
            "parameters_with_annotations": 1
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_e36e06e08b165fd948b9fec76a0d5acf.py": {
        "stats": {
            "total_parameters": 12,
            "parameters_with_annotations": 12
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "run_benchmark_e36e06e08b165fd948b9fec76a0d5acf.py:79: error: Name \"argparse\" is not defined  [name-defined]",
            "run_benchmark_e36e06e08b165fd948b9fec76a0d5acf.py:104: error: Incompatible types in assignment (expression has type \"List[str]\", variable has type \"Tuple[Any]\")  [assignment]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_e40666714496fa08885bd7c6883de76b.py": {
        "stats": {
            "total_parameters": 25,
            "parameters_with_annotations": 1
        },
        "error_count": 11,
        "isCompiled": false,
        "errors": [
            "run_benchmark_e40666714496fa08885bd7c6883de76b.py:8: error: All protocol members must have explicitly declared types  [misc]",
            "run_benchmark_e40666714496fa08885bd7c6883de76b.py:13: error: All protocol members must have explicitly declared types  [misc]",
            "run_benchmark_e40666714496fa08885bd7c6883de76b.py:14: error: All protocol members must have explicitly declared types  [misc]",
            "run_benchmark_e40666714496fa08885bd7c6883de76b.py:15: error: All protocol members must have explicitly declared types  [misc]",
            "run_benchmark_e40666714496fa08885bd7c6883de76b.py:16: error: All protocol members must have explicitly declared types  [misc]",
            "run_benchmark_e40666714496fa08885bd7c6883de76b.py:17: error: All protocol members must have explicitly declared types  [misc]",
            "run_benchmark_e40666714496fa08885bd7c6883de76b.py:48: error: All protocol members must have explicitly declared types  [misc]",
            "run_benchmark_e40666714496fa08885bd7c6883de76b.py:134: error: Incompatible types in assignment (expression has type \"int\", variable has type \"None\")  [assignment]",
            "run_benchmark_e40666714496fa08885bd7c6883de76b.py:146: error: Incompatible types in assignment (expression has type \"int\", variable has type \"None\")  [assignment]",
            "run_benchmark_e40666714496fa08885bd7c6883de76b.py:149: error: Variable \"typing.Protocol\" is not valid as a type  [valid-type]",
            "run_benchmark_e40666714496fa08885bd7c6883de76b.py:149: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases",
            "Found 10 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_e77a04005a6abbca76058ef014ab41a6.py": {
        "stats": {
            "total_parameters": 4,
            "parameters_with_annotations": 4
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "run_benchmark_e77a04005a6abbca76058ef014ab41a6.py:8: error: Incompatible types in assignment (expression has type \"None\", target has type Module)  [assignment]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_e93163c78613c4410d2fe21b2a81f7a2.py": {
        "stats": {
            "total_parameters": 10,
            "parameters_with_annotations": 8
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "run_benchmark_e93163c78613c4410d2fe21b2a81f7a2.py:10: error: X | Y syntax for unions requires Python 3.10  [syntax]",
            "run_benchmark_e93163c78613c4410d2fe21b2a81f7a2.py:11: error: X | Y syntax for unions requires Python 3.10  [syntax]",
            "run_benchmark_e93163c78613c4410d2fe21b2a81f7a2.py:44: error: X | Y syntax for unions requires Python 3.10  [syntax]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_ed36b868873c9ca9cb835088629996b5.py": {
        "stats": {
            "total_parameters": 7,
            "parameters_with_annotations": 4
        },
        "error_count": 5,
        "isCompiled": false,
        "errors": [
            "run_benchmark_ed36b868873c9ca9cb835088629996b5.py:7: error: Incompatible types in assignment (expression has type \"None\", variable has type \"str\")  [assignment]",
            "run_benchmark_ed36b868873c9ca9cb835088629996b5.py:8: error: Incompatible types in assignment (expression has type \"None\", variable has type \"List[Any]\")  [assignment]",
            "run_benchmark_ed36b868873c9ca9cb835088629996b5.py:9: error: Incompatible types in assignment (expression has type \"None\", variable has type \"bool\")  [assignment]",
            "run_benchmark_ed36b868873c9ca9cb835088629996b5.py:17: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]",
            "run_benchmark_ed36b868873c9ca9cb835088629996b5.py:18: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_ef50c0004e4c63b45751afdedd20f922.py": {
        "stats": {
            "total_parameters": 7,
            "parameters_with_annotations": 7
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_f4779276baee1e691111c58f163c03a0.py": {
        "stats": {
            "total_parameters": 4,
            "parameters_with_annotations": 4
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py": {
        "stats": {
            "total_parameters": 82,
            "parameters_with_annotations": 66
        },
        "error_count": 24,
        "isCompiled": false,
        "errors": [
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:114: error: Incompatible types in assignment (expression has type \"List[array[float]]\", variable has type \"array[float]\")  [assignment]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:120: error: Value of type \"float\" is not indexable  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:126: error: Unsupported target for indexed assignment (\"float\")  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:130: error: Argument 1 of \"copy_data_from\" is incompatible with supertype \"Array2D\"; supertype defines the argument type as \"Array2D\"  [override]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:130: note: This violates the Liskov substitution principle",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:130: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:132: error: Unsupported target for indexed assignment (\"float\")  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:200: error: Value of type \"float\" is not indexable  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:200: error: Invalid index type \"int\" for \"ArrayList\"; expected type \"Tuple[int, int]\"  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:202: error: Value of type \"float\" is not indexable  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:202: error: Invalid index type \"int\" for \"ArrayList\"; expected type \"Tuple[int, int]\"  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:207: error: Value of type \"float\" is not indexable  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:207: error: Invalid index type \"int\" for \"ArrayList\"; expected type \"Tuple[int, int]\"  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:210: error: Invalid index type \"int\" for \"ArrayList\"; expected type \"Tuple[int, int]\"  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:212: error: Value of type \"float\" is not indexable  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:212: error: Invalid index type \"int\" for \"ArrayList\"; expected type \"Tuple[int, int]\"  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:214: error: Value of type \"float\" is not indexable  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:214: error: Unsupported target for indexed assignment (\"float\")  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:214: error: Invalid index type \"int\" for \"ArrayList\"; expected type \"Tuple[int, int]\"  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:218: error: Value of type \"float\" is not indexable  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:218: error: Unsupported target for indexed assignment (\"float\")  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:218: error: Invalid index type \"int\" for \"ArrayList\"; expected type \"Tuple[int, int]\"  [index]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:232: error: Argument 2 to \"LU\" has incompatible type \"Array2D\"; expected \"ArrayList\"  [arg-type]",
            "run_benchmark_f4909fc93f2b77fbaa7a1a62f396ad97.py:356: error: Incompatible types in assignment (expression has type \"List[str]\", variable has type \"Tuple[Any]\")  [assignment]",
            "Found 22 errors in 1 file (checked 1 source file)"
        ]
    },
    "run_benchmark_fe7e80f88187eee851b45d280f1d907a.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "run_benchmark_ff55a410a7f31c4a3ea3646528a81cb1.py": {
        "stats": {
            "total_parameters": 2,
            "parameters_with_annotations": 2
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "tokenize_b7662d3f564d80fcd8b53af809f8752a.py": {
        "stats": {
            "total_parameters": 22,
            "parameters_with_annotations": 18
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "tokenize_b7662d3f564d80fcd8b53af809f8752a.py:6: error: No parent module -- cannot perform relative import",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "token_5adf5a279650e10ecd71aed939a26b65.py": {
        "stats": {
            "total_parameters": 3,
            "parameters_with_annotations": 3
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "token_5adf5a279650e10ecd71aed939a26b65.py:64: error: \"dict\" is not subscriptable, use \"typing.Dict\" instead  [misc]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "Unix_file_Path.py": {
        "stats": {
            "total_parameters": 1,
            "parameters_with_annotations": 1
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "__init___5f53cb190f7f70b5109965ef06d59e91.py": {
        "stats": {
            "total_parameters": 4,
            "parameters_with_annotations": 4
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "__init___5f53cb190f7f70b5109965ef06d59e91.py:5: error: Missing return statement  [empty-body]",
            "__init___5f53cb190f7f70b5109965ef06d59e91.py:8: error: Missing return statement  [empty-body]",
            "__init___5f53cb190f7f70b5109965ef06d59e91.py:11: error: Missing return statement  [empty-body]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "__init___68b329da9893e34099c7d8ad5cb9c940.py": {
        "stats": {
            "total_parameters": 8,
            "parameters_with_annotations": 8
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "__main___ec49d82b59fd16b0aa7ad9e9096a35e2.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    }
}