model,file,flip_direction,run1_status,run2_status,run1_error_top,run2_error_top
gpt4o,__init___3f6268.py,fail->success,fail,success,"__init___3f6268.py:376: error: Name ""cast"" is not defined [name-defined]",
gpt4o,__init___9a6f7a.py,success->fail,success,fail,,"__init___9a6f7a.py:290: error: Name ""final"" is not defined [name-defined]"
gpt4o,__init___c1477c.py,success->fail,success,fail,,"__init___c1477c.py:287: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
gpt4o,__init___c7b03c.py,fail->success,fail,success,"__init___c7b03c.py:93: error: Need type annotation for ""listeners"" (hint: ""listeners: List[<type>] = ..."") [var-annotated]",
gpt4o,__init___d2d86c.py,success->fail,success,fail,,__init___d2d86c.py:302: error: Cast target is not a type [misc]
gpt4o,accessors_5aa969.py,fail->success,fail,success,"accessors_5aa969.py:110: error: Name ""cast"" is not defined [name-defined]",
gpt4o,adversarial_bias_mitigator_3ad2a0.py,success->fail,success,fail,,"adversarial_bias_mitigator_3ad2a0.py:88: error: ""None"" not callable [misc]"
gpt4o,base_6a0ea7.py,success->fail,success,fail,,"base_6a0ea7.py:33: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
gpt4o,base_a0b3af.py,success->fail,success,fail,,"base_a0b3af.py:23: error: Incompatible default for argument ""numbers"" (default has type ""None"", argument has type ""List[str]"") [assignment]"
gpt4o,binary_sensor_d63eaf.py,fail->success,fail,success,"binary_sensor_d63eaf.py:97: error: Incompatible return value type (got ""Optional[bool]"", expected ""bool"") [return-value]",
gpt4o,blocks_a65ab4.py,fail->success,fail,success,"blocks_a65ab4.py:35: error: Incompatible types in assignment (expression has type ""List[Tuple[str, Any]]"", variable has type ""List[Tuple[Any, ...]]"") [assignment]",
gpt4o,boxplot_f690b9.py,success->fail,success,fail,,"boxplot_f690b9.py:14: error: Name ""Tuple"" is not defined [name-defined]"
gpt4o,bybit_f190ec.py,fail->success,fail,success,"bybit_f190ec.py:47: error: Dict entry 0 has incompatible type ""str"": ""bool""; expected ""str"": ""str"" [dict-item]",
gpt4o,calendar_819d29.py,fail->success,fail,success,"calendar_819d29.py:95: error: Dict entry 0 has incompatible type ""str"": ""None""; expected ""str"": ""Union[str, int]"" [dict-item]",
gpt4o,calibration_d3fe81.py,success->fail,success,fail,,"calibration_d3fe81.py:53: error: Function ""builtins.any"" is not valid as a type [valid-type]"
gpt4o,channel_771f46.py,success->fail,success,fail,,"channel_771f46.py:30: error: ""deque"" is not subscriptable, use ""typing.Deque"" instead [misc]"
gpt4o,conftest_0f5d02.py,success->fail,success,fail,,"conftest_0f5d02.py:42: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
gpt4o,converter_489a6d.py,success->fail,success,fail,,"converter_489a6d.py:141: error: List item 0 has incompatible type ""Union[str, List[str], None]""; expected ""str"" [list-item]"
gpt4o,copartitioned_assignor_d68f8c.py,fail->success,fail,success,"copartitioned_assignor_d68f8c.py:90: error: Name ""Iterator"" is not defined [name-defined]",
gpt4o,dataprovider_a0d211.py,fail->success,fail,success,"dataprovider_a0d211.py:35: error: ""deque"" is not subscriptable, use ""typing.Deque"" instead [misc]",
gpt4o,datetimelike_f48bd1.py,success->fail,success,fail,,"datetimelike_f48bd1.py:145: error: Incompatible return value type (got ""str"", expected ""List[str]"") [return-value]"
gpt4o,elmo_indexer_111385.py,success->fail,success,fail,,"elmo_indexer_111385.py:76: error: Incompatible return value type (got ""Dict[str, LongTensor]"", expected ""Dict[str, Tensor]"") [return-value]"
gpt4o,entity_8bb532.py,success->fail,success,fail,,"entity_8bb532.py:180: error: Name ""cast"" is not defined [name-defined]"
gpt4o,event_schema_4d75fe.py,fail->success,fail,success,"event_schema_4d75fe.py:284: error: Argument 2 to ""isinstance"" has incompatible type ""object""; expected ""_ClassInfo"" [arg-type]",
gpt4o,exchange_ws_9ca098.py,fail->success,fail,success,"exchange_ws_9ca098.py:22: error: ""set"" is not subscriptable, use ""typing.Set"" instead [misc]",
gpt4o,expected_catalog_04b2bc.py,fail->success,fail,success,"expected_catalog_04b2bc.py:48: error: Dict entry 2 has incompatible type ""str"": ""Dict[str, Union[str, int, float]]""; expected ""str"": ""Union[str, int, float, Dict[str, Union[str, int, None]]]"" [dict-item]",
gpt4o,funcdef_return_type_trailing_comma_6ef842.py,success->fail,success,fail,,"funcdef_return_type_trailing_comma_6ef842.py:64: error: Function ""builtins.callable"" is not valid as a type [valid-type]"
gpt4o,invites_f24478.py,success->fail,success,fail,,"invites_f24478.py:194: error: Dict entry 3 has incompatible type ""str"": ""Optional[int]""; expected ""str"": ""Union[str, int]"" [dict-item]"
gpt4o,lazy_value_18eb7d.py,fail->success,fail,success,"lazy_value_18eb7d.py:37: error: Name ""Context"" is not defined [name-defined]",
gpt4o,meta_learners_cdb80e.py,success->fail,success,fail,,"meta_learners_cdb80e.py:80: error: Incompatible default for argument ""learner_transformers"" (default has type ""None"", argument has type ""List[Callable[..., Any]]"") [assignment]"
gpt4o,note_76679d.py,fail->success,fail,success,note_76679d.py:92: error: Missing return statement [return],
gpt4o,number_c8a6fb.py,success->fail,success,fail,,"number_c8a6fb.py:281: error: Incompatible types in assignment (expression has type ""float"", variable has type ""int"") [assignment]"
gpt4o,online_f12d20.py,fail->success,fail,success,"online_f12d20.py:24: error: Name ""TYPE_CHECKING"" is not defined [name-defined]",
gpt4o,optimize_reports_05f23c.py,success->fail,success,fail,,"optimize_reports_05f23c.py:350: error: Need type annotation for ""result"" [var-annotated]"
gpt4o,postgres_09c46c.py,fail->success,fail,success,"postgres_09c46c.py:22: error: Name ""TYPE_CHECKING"" is not defined [name-defined]",
gpt4o,run_b777ab.py,success->fail,success,fail,,"run_b777ab.py:55: error: Name ""Iterable"" is not defined [name-defined]"
gpt4o,schemas_1abb49.py,success->fail,success,fail,,"schemas_1abb49.py:51: error: Unexpected keyword argument ""serializer"" [call-arg]"
gpt4o,screenshots_949c9a.py,fail->success,fail,success,screenshots_949c9a.py:25: error: invalid syntax [syntax],
gpt4o,sensor_48e774.py,success->fail,success,fail,,"sensor_48e774.py:78: error: Incompatible types in assignment (expression has type ""Type[MyUplinkDevicePointSensor]"", variable has type ""Union[MyUplinkDevicePointSensor, MyUplinkEnumSensor]"") [assignment]"
gpt4o,sensor_e47032.py,fail->success,fail,success,"sensor_e47032.py:28: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]",
gpt4o,signals_ff12b9.py,fail->success,fail,success,"signals_ff12b9.py:11: error: Name ""typing"" is not defined [name-defined]",
gpt4o,sparse_a2c123.py,success->fail,success,fail,,"sparse_a2c123.py:20: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
gpt4o,storage_ecdafa.py,success->fail,success,fail,,"storage_ecdafa.py:14: error: Dict entry 0 has incompatible type ""str"": ""Dict[str, str]""; expected ""str"": ""Union[Dict[str, Union[str, int, List[Dict[str, Union[str, int]]]]], List[Dict[str, Union[str, List[int]]]], Dict[int, Dict[str, Union[str, int]]]]"" [dict-item]"
gpt4o,stream_subscription_0a3612.py,success->fail,success,fail,,"stream_subscription_0a3612.py:51: error: Need type annotation for ""result"" [var-annotated]"
gpt4o,string__8c20b1.py,fail->success,fail,success,"string__8c20b1.py:472: error: Name ""BooleanArray"" is not defined [name-defined]",
gpt4o,switch_8d0b59.py,success->fail,success,fail,,switch_8d0b59.py:69: error: X | Y syntax for unions requires Python 3.10 [syntax]
gpt4o,tables_379478.py,success->fail,success,fail,,tables_379478.py:292: error: A function returning TypeVar should receive at least one argument containing the same TypeVar [type-var]
gpt4o,tensorboard_c446d9.py,fail->success,fail,success,"tensorboard_c446d9.py:36: error: Item ""None"" of ""Optional[Any]"" has no attribute ""close"" [union-attr]",
gpt4o,test_arithmetic_f016de.py,fail->success,fail,success,"test_arithmetic_f016de.py:58: error: Function ""builtins.callable"" is not valid as a type [valid-type]",
gpt4o,test_arrays_9fefe1.py,fail->success,fail,success,"test_arrays_9fefe1.py:11: error: Function ""builtins.any"" is not valid as a type [valid-type]",
gpt4o,test_blackouts_53e928.py,success->fail,success,fail,,"test_blackouts_53e928.py:309: error: Dict entry 1 has incompatible type ""str"": ""List[str]""; expected ""str"": ""str"" [dict-item]"
gpt4o,test_cat_c39959.py,success->fail,success,fail,,"test_cat_c39959.py:19: error: Incompatible types in assignment (expression has type ""List[str]"", variable has type ""Optional[Callable[..., Union[Any, Any]]]"") [assignment]"
gpt4o,test_clipboard_d0a3e6.py,success->fail,success,fail,,"test_clipboard_d0a3e6.py:142: error: Argument 2 to ""build_kwargs"" has incompatible type ""Union[bool, None, str]""; expected ""Optional[str]"" [arg-type]"
gpt4o,test_common_basic_a8eb4c.py,success->fail,success,fail,,"test_common_basic_a8eb4c.py:232: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
gpt4o,test_conversion_928a39.py,fail->success,fail,success,"test_conversion_928a39.py:32: error: Argument 1 to ""issubclass"" has incompatible type ""Union[type, Callable[..., Any]]""; expected ""type"" [arg-type]",
gpt4o,test_core_08030e.py,success->fail,success,fail,,"test_core_08030e.py:10: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
gpt4o,test_deposit_93dc29.py,fail->success,fail,success,"test_deposit_93dc29.py:27: error: Function ""builtins.callable"" is not valid as a type [valid-type]",
gpt4o,test_drop_duplicates_d918e0.py,fail->success,fail,success,"test_drop_duplicates_d918e0.py:45: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]",
gpt4o,test_env_var_deprecations_894c4e.py,success->fail,success,fail,,"test_env_var_deprecations_894c4e.py:10: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
gpt4o,test_feather_09566a.py,fail->success,fail,success,"test_feather_09566a.py:17: error: No overload variant of ""raises"" matches argument types ""Exception"", ""str"" [call-overload]",
gpt4o,test_index_d51bbf.py,success->fail,success,fail,,"test_index_d51bbf.py:24: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
gpt4o,test_interval_tree_05bf63.py,fail->success,fail,success,"test_interval_tree_05bf63.py:101: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]",
gpt4o,test_json_table_schema_ext_dtype_03d9d8.py,fail->success,fail,success,"test_json_table_schema_ext_dtype_03d9d8.py:89: error: Invalid index type ""str"" for ""str""; expected type ""Union[SupportsIndex, slice]"" [index]",
gpt4o,test_merge_ordered_3a00fd.py,success->fail,success,fail,,"test_merge_ordered_3a00fd.py:48: error: Incompatible return value type (got ""Type[NotADataFrame]"", expected ""NotADataFrame"") [return-value]"
gpt4o,test_notify_74a852.py,success->fail,success,fail,,"test_notify_74a852.py:92: error: Incompatible types in assignment (expression has type ""str"", variable has type ""List[str]"") [assignment]"
gpt4o,test_overlaps_cda380.py,fail->success,fail,success,"test_overlaps_cda380.py:10: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]",
gpt4o,test_package_4421e1.py,fail->success,fail,success,"test_package_4421e1.py:65: error: Incompatible return value type (got ""List[Tuple[str, Sequence[str]]]"", expected ""List[Tuple[str, List[str]]]"") [return-value]",
gpt4o,test_process_execution_payload_bd0176.py,success->fail,success,fail,,"test_process_execution_payload_bd0176.py:14: error: ""tuple"" is not subscriptable, use ""typing.Tuple"" instead [misc]"
gpt4o,test_process_voluntary_exit_d70212.py,success->fail,success,fail,,"test_process_voluntary_exit_d70212.py:19: error: ""object"" has no attribute ""get_current_epoch"" [attr-defined]"
gpt4o,test_regression_05a4bf.py,success->fail,success,fail,,"test_regression_05a4bf.py:105: error: Function ""builtins.any"" is not valid as a type [valid-type]"
gpt4o,test_set_index_3c0de8.py,fail->success,fail,success,"test_set_index_3c0de8.py:130: error: List item 0 has incompatible type ""Union[str, Tuple[Any, ...]]""; expected ""str"" [list-item]",
gpt4o,test_setitem_a50d5b.py,success->fail,success,fail,,"test_setitem_a50d5b.py:7: error: Function ""builtins.any"" is not valid as a type [valid-type]"
gpt4o,test_sort_index_15410c.py,success->fail,success,fail,,"test_sort_index_15410c.py:321: error: Function ""builtins.any"" is not valid as a type [valid-type]"
gpt4o,test_sort_index_efa5b2.py,fail->success,fail,success,"test_sort_index_efa5b2.py:177: error: Function ""builtins.callable"" is not valid as a type [valid-type]",
gpt4o,test_sparse_d759ae.py,fail->success,fail,success,"test_sparse_d759ae.py:26: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]",
gpt4o,test_targetstate_85ad01.py,success->fail,success,fail,,"test_targetstate_85ad01.py:195: error: Item ""None"" of ""Optional[Any]"" has no attribute ""from_hop"" [union-attr]"
gpt4o,test_truncate_a84f32.py,fail->success,fail,success,test_truncate_a84f32.py:63: error: X | Y syntax for unions requires Python 3.10 [syntax],
gpt4o,test_union_categoricals_f7953f.py,success->fail,success,fail,,"test_union_categoricals_f7953f.py:72: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
gpt4o,test_web_websocket_389e12.py,success->fail,success,fail,,test_web_websocket_389e12.py:94: error: Too few arguments [call-arg]
gpt4o,test_wrappers_62b3f0.py,fail->success,fail,success,test_wrappers_62b3f0.py:226: error: Missing return statement [return],
gpt4o,tools_6a9569.py,success->fail,success,fail,,"tools_6a9569.py:106: error: Item ""Iterable[Any]"" of ""Union[Any, Iterable[Any]]"" has no attribute ""get_figure"" [union-attr]"
gpt4o,topics_fc6164.py,fail->success,fail,success,"topics_fc6164.py:38: error: Name ""Type"" is not defined [name-defined]",
gpt4o,tracing_fe42d6.py,fail->success,fail,success,"tracing_fe42d6.py:83: error: Incompatible types in assignment (expression has type ""Optional[FrameType]"", variable has type ""FrameType"") [assignment]",
gpt4o,transport_58bb8a.py,fail->success,fail,success,"transport_58bb8a.py:299: error: Item ""None"" of ""Optional[_RetryQueue]"" has no attribute ""start"" [union-attr]",
gpt4o,users_e38fbd.py,fail->success,fail,success,"users_e38fbd.py:345: error: Name ""default_token_generator"" is not defined [name-defined]",
gpt4o,util_c87ff9.py,success->fail,success,fail,,"util_c87ff9.py:7: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
gpt4o,wrappers_34ca66.py,success->fail,success,fail,,"wrappers_34ca66.py:23: error: Name ""KeysView"" is not defined [name-defined]"
o1-mini,FreqaiExampleHybridStrategy_04bd2f.py,success->fail,success,fail,,FreqaiExampleHybridStrategy_04bd2f.py:216: error: Type cannot be declared in assignment to non-self attribute [misc]
o1-mini,FreqaiExampleStrategy_4d11fd.py,success->fail,success,fail,,FreqaiExampleStrategy_4d11fd.py:266: error: only single target (not tuple) can be annotated [syntax]
o1-mini,__init___063bfe.py,fail->success,fail,success,"__init___063bfe.py:95: error: ""Callable[..., Any]"" has no attribute ""get_metric"" [attr-defined]",
o1-mini,__init___344c2e.py,success->fail,success,fail,,__init___344c2e.py:243: error: invalid syntax [syntax]
o1-mini,__init___38b704.py,success->fail,success,fail,,__init___38b704.py:208: error: Cannot assign to a method [method-assign]
o1-mini,__init___3afdb9.py,fail->success,fail,success,"__init___3afdb9.py:54: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]",
o1-mini,__init___3f6268.py,fail->success,fail,success,__init___3f6268.py:269: error: invalid syntax [syntax],
o1-mini,__init___54e0bc.py,fail->success,fail,success,"__init___54e0bc.py:16: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]",
o1-mini,__init___70582f.py,success->fail,success,fail,,"__init___70582f.py:93: error: Incompatible types in assignment (expression has type ""Optional[Any]"", variable has type ""str"") [assignment]"
o1-mini,__init___97fa7b.py,success->fail,success,fail,,"__init___97fa7b.py:70: error: Name ""KeysView"" is not defined [name-defined]"
o1-mini,__init___9e75d4.py,fail->success,fail,success,"__init___9e75d4.py:145: error: ""dict"" is not subscriptable [misc]",
o1-mini,__init___a5a747.py,success->fail,success,fail,,__init___a5a747.py:164: error: only single target (not tuple) can be annotated [syntax]
o1-mini,__init___ade613.py,success->fail,success,fail,,"__init___ade613.py:113: error: Incompatible return value type (got ""_patch[Union[MagicMock, AsyncMock]]"", expected ""MagicMock"") [return-value]"
o1-mini,__init___d2d86c.py,fail->success,fail,success,__init___d2d86c.py:526: error: Cast target is not a type [misc],
o1-mini,__init___ee7b0d.py,success->fail,success,fail,,"__init___ee7b0d.py:197: error: Unsupported right operand type for in (""Optional[str]"") [operator]"
o1-mini,_cert_chain_analyzer_dafae6.py,fail->success,fail,success,"_cert_chain_analyzer_dafae6.py:224: error: Missing positional argument ""verified_certificate_chain"" in call to ""CertificateDeploymentAnalysisResult"" [call-arg]",
o1-mini,_checklist_internal_2e9c80.py,fail->success,fail,success,"_checklist_internal_2e9c80.py:25: error: ""ArgumentParser"" has no attribute ""add_parser""; maybe ""add_subparsers""? [attr-defined]",
o1-mini,_content_aabc8a.py,fail->success,fail,success,"_content_aabc8a.py:97: error: Argument 1 to ""IteratorByteStream"" has incompatible type ""Union[bytes, str, Iterable[bytes]]""; expected ""Iterable[bytes]"" [arg-type]",
o1-mini,_doctools_2a0387.py,fail->success,fail,success,"_doctools_2a0387.py:44: error: Incompatible default for argument ""labels"" (default has type ""Tuple[]"", argument has type ""Optional[List[str]]"") [assignment]",
o1-mini,_openpyxl_60b4ed.py,success->fail,success,fail,,"_openpyxl_60b4ed.py:445: error: Incompatible types in assignment (expression has type ""Optional[Dict[str, Any]]"", variable has type ""Dict[str, Any]"") [assignment]"
o1-mini,_parser_ad554d.py,fail->success,fail,success,"_parser_ad554d.py:48: error: Incompatible types in assignment (expression has type ""str"", variable has type ""bytes"") [assignment]",
o1-mini,_robot_tester_77d42f.py,success->fail,success,fail,,_robot_tester_77d42f.py:262: error: Exception type must be derived from BaseException (or be a tuple of exception classes) [misc]
o1-mini,_types_6d212e.py,success->fail,success,fail,,"_types_6d212e.py:135: error: Unsupported argument 2 for ""super"" [misc]"
o1-mini,accessories_b90bda.py,fail->success,fail,success,"accessories_b90bda.py:422: error: Unsupported operand types for < (""str"" and ""float"") [operator]",
o1-mini,acked_by_ce084a.py,success->fail,success,fail,,"acked_by_ce084a.py:19: error: Name ""Alert"" is not defined [name-defined]"
o1-mini,actor_865029.py,fail->success,fail,success,"actor_865029.py:74: error: ""AsyncGenerator"" expects 2 type arguments, but 3 given [type-arg]",
o1-mini,agents_3f7d1d.py,success->fail,success,fail,,"agents_3f7d1d.py:107: error: Return type ""Coroutine[Any, Any, _T]"" of ""__await__"" incompatible with return type ""Generator[Any, None, _T]"" in supertype ""Awaitable"" [override]"
o1-mini,api_1f14a8.py,success->fail,success,fail,,api_1f14a8.py:120: error: X | Y syntax for unions requires Python 3.10 [syntax]
o1-mini,api_test_5baf5c.py,fail->success,fail,success,"api_test_5baf5c.py:46: error: Name ""UUID"" is not defined [name-defined]",
o1-mini,app_c89ec6.py,success->fail,success,fail,,"app_c89ec6.py:456: error: Name ""Producer"" is not defined [name-defined]"
o1-mini,attestations_9893da.py,fail->success,fail,success,attestations_9893da.py:26: error: Missing return statement [empty-body],
o1-mini,attester_slashings_270ad2.py,fail->success,fail,success,"attester_slashings_270ad2.py:6: error: Name ""Spec"" is not defined [name-defined]",
o1-mini,base_7e78cf.py,success->fail,success,fail,,"base_7e78cf.py:101: error: ""PinnedPackage"" has no attribute ""package"" [attr-defined]"
o1-mini,base_9c14fc.py,success->fail,success,fail,,"base_9c14fc.py:137: error: ""defaultdict"" is not subscriptable, use ""typing.DefaultDict"" instead [misc]"
o1-mini,base_a0b3af.py,success->fail,success,fail,,"base_a0b3af.py:63: error: Item ""None"" of ""Optional[Any]"" has no attribute ""get_all_name_numbers"" [union-attr]"
o1-mini,base_bb93b4.py,fail->success,fail,success,"base_bb93b4.py:30: error: Incompatible return value type (got ""Optional[str]"", expected ""Union[str, BaseStringArrayMethods]"") [return-value]",
o1-mini,bias_mitigator_wrappers_4e83be.py,fail->success,fail,success,"bias_mitigator_wrappers_4e83be.py:94: error: Incompatible types in assignment (expression has type ""Tensor"", variable has type ""List[Tensor]"") [assignment]",
o1-mini,binary_sensor_39cce2.py,fail->success,fail,success,"binary_sensor_39cce2.py:154: error: Incompatible types in assignment (expression has type ""None"", variable has type ""Dict[Any, Any]"") [assignment]",
o1-mini,binary_sensor_b774df.py,success->fail,success,fail,,"binary_sensor_b774df.py:56: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
o1-mini,binary_sensor_c09c5d.py,fail->success,fail,success,"binary_sensor_c09c5d.py:267: error: ""date"" has no attribute ""date"" [attr-defined]",
o1-mini,bleu_test_22d7f9.py,success->fail,success,fail,,"bleu_test_22d7f9.py:33: error: ""Counter"" is not subscriptable, use ""typing.Counter"" instead [misc]"
o1-mini,blockchain_37e43c.py,fail->success,fail,success,"blockchain_37e43c.py:106: error: ""object"" has no attribute ""get_contract"" [attr-defined]",
o1-mini,browser_8130a6.py,fail->success,fail,success,"browser_8130a6.py:190: error: Incompatible types in assignment (expression has type ""Optional[Any]"", variable has type ""str"") [assignment]",
o1-mini,cache_7cc469.py,success->fail,success,fail,,cache_7cc469.py:13: error: ClassVar can only be used for assignments in class body [misc]
o1-mini,cache_helpers_e012c1.py,success->fail,success,fail,,"cache_helpers_e012c1.py:30: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
o1-mini,calibration_d3fe81.py,fail->success,fail,success,"calibration_d3fe81.py:110: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]",
o1-mini,camera_4798a7.py,success->fail,success,fail,,camera_4798a7.py:88: error: invalid syntax [syntax]
o1-mini,checkpointer_2adffa.py,fail->success,fail,success,"checkpointer_2adffa.py:183: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]",
o1-mini,classification_92cb06.py,success->fail,success,fail,,"classification_92cb06.py:654: error: Name ""class_shap_values"" is not defined [name-defined]"
o1-mini,client_aeeaee.py,success->fail,success,fail,,client_aeeaee.py:119: error: List comprehension has incompatible type List[str]; expected List[UUID] [misc]
o1-mini,climate_588757.py,success->fail,success,fail,,"climate_588757.py:244: error: Argument 2 to ""next"" has incompatible type ""None""; expected ""float"" [arg-type]"
o1-mini,climate_8c1cee.py,fail->success,fail,success,"climate_8c1cee.py:156: error: Incompatible types in assignment (expression has type ""None"", variable has type ""float"") [assignment]",
o1-mini,common_888838.py,fail->success,fail,success,"common_888838.py:5: error: Name ""Generic"" is not defined [name-defined]",
o1-mini,common_fcbb68.py,fail->success,fail,success,common_fcbb68.py:244: error: Starred assignment target must be in a list or tuple [misc],
o1-mini,compilation_283ca2.py,fail->success,fail,success,"compilation_283ca2.py:141: error: Name ""cast"" is not defined [name-defined]",
o1-mini,compression_utils_d50545.py,fail->success,fail,success,"compression_utils_d50545.py:47: error: Function ""zlib.compressobj"" is not valid as a type [valid-type]",
o1-mini,conftest_4ecb9c.py,fail->success,fail,success,"conftest_4ecb9c.py:87: error: The return type of a generator function should be ""Generator"" or one of its supertypes [misc]",
o1-mini,conftest_db6ccc.py,success->fail,success,fail,,"conftest_db6ccc.py:126: error: Need type annotation for ""resp"" (hint: ""resp: Dict[<type>, <type>] = ..."") [var-annotated]"
o1-mini,conftest_ee8a90.py,fail->success,fail,success,"conftest_ee8a90.py:4: error: Module ""typing"" has no attribute ""Yield"" [attr-defined]",
o1-mini,conftest_f547b4.py,success->fail,success,fail,,conftest_f547b4.py:105: error: Type cannot be declared in assignment to non-self attribute [misc]
o1-mini,console_aefea3.py,success->fail,success,fail,,"console_aefea3.py:76: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
o1-mini,consumer_fa3d87.py,success->fail,success,fail,,"consumer_fa3d87.py:394: error: Name ""DefaultDict"" is not defined [name-defined]"
o1-mini,cover_860401.py,fail->success,fail,success,"cover_860401.py:172: error: Incompatible types in assignment (expression has type ""float"", variable has type ""Optional[int]"") [assignment]",
o1-mini,cover_b5d82f.py,fail->success,fail,success,"cover_b5d82f.py:70: error: Name ""Callable"" is not defined [name-defined]",
o1-mini,cover_c586a7.py,fail->success,fail,success,"cover_c586a7.py:80: error: Incompatible types in assignment (expression has type ""Optional[Any]"", variable has type ""int"") [assignment]",
o1-mini,create_user_36a545.py,fail->success,fail,success,"create_user_36a545.py:320: error: Dict entry 3 has incompatible type ""str"": ""bool""; expected ""str"": ""Collection[str]"" [dict-item]",
o1-mini,custom_profile_fields_ccef17.py,fail->success,fail,success,"custom_profile_fields_ccef17.py:34: error: ""Dict[str, Any]"" has no attribute ""name"" [attr-defined]",
o1-mini,data_9b3042.py,fail->success,fail,success,"data_9b3042.py:7: error: Incompatible types in assignment (expression has type ""Type[Dict[Any, Any]]"", variable has type ""Dict[str, Any]"") [assignment]",
o1-mini,ddp_accelerator_0b7bea.py,fail->success,fail,success,"ddp_accelerator_0b7bea.py:47: error: Name ""torch.nn.modules.module.ModuleDict"" is not defined [name-defined]",
o1-mini,deposits_09e7ec.py,success->fail,success,fail,,"deposits_09e7ec.py:13: error: Name ""Spec"" is not defined [name-defined]"
o1-mini,ecs_3fb000.py,success->fail,success,fail,,"ecs_3fb000.py:54: error: Item ""None"" of ""Optional[Module]"" has no attribute ""client"" [union-attr]"
o1-mini,entities_19afaa.py,success->fail,success,fail,,"entities_19afaa.py:37: error: Name ""Any"" is not defined [name-defined]"
o1-mini,entity_0d0e17.py,fail->success,fail,success,"entity_0d0e17.py:273: error: Name ""List"" is not defined [name-defined]",
o1-mini,entity_27a2b6.py,fail->success,fail,success,"entity_27a2b6.py:77: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]",
o1-mini,entity_3c2299.py,fail->success,fail,success,"entity_3c2299.py:120: error: Argument 1 to ""set_result"" of ""Future"" has incompatible type ""bool""; expected ""None"" [arg-type]",
o1-mini,entity_680502.py,fail->success,fail,success,"entity_680502.py:169: error: Incompatible return value type (got ""Optional[str]"", expected ""str"") [return-value]",
o1-mini,entity_8bb532.py,success->fail,success,fail,,"entity_8bb532.py:235: error: Name ""cast"" is not defined [name-defined]"
o1-mini,entity_9f065b.py,success->fail,success,fail,,"entity_9f065b.py:72: error: Incompatible return value type (got ""Optional[Any]"", expected ""bool"") [return-value]"
o1-mini,entity_a41728.py,success->fail,success,fail,,entity_a41728.py:117: error: Too few arguments [call-arg]
o1-mini,env_settings_7d6868.py,success->fail,success,fail,,"env_settings_7d6868.py:109: error: Too many arguments for ""AbstractSet"" [call-arg]"
o1-mini,evaluators_b911b8.py,success->fail,success,fail,,"evaluators_b911b8.py:827: error: Value expression in dictionary comprehension has incompatible type ""Dict[str, float]""; expected type ""float"" [misc]"
o1-mini,execution_855aa0.py,success->fail,success,fail,,"execution_855aa0.py:18: error: ""deque"" is not subscriptable, use ""typing.Deque"" instead [misc]"
o1-mini,fairscale_fsdp_accelerator_test_c1bd1f.py,success->fail,success,fail,,fairscale_fsdp_accelerator_test_c1bd1f.py:125: error: invalid syntax [syntax]
o1-mini,fan_f7fc07.py,success->fail,success,fail,,"fan_f7fc07.py:206: error: Incompatible return value type (got ""Optional[bool]"", expected ""bool"") [return-value]"
o1-mini,filters_a79ada.py,fail->success,fail,success,"filters_a79ada.py:65: error: Name ""CONNF_ENTITY_GLOBS"" is not defined [name-defined]",
o1-mini,game_1baf0c.py,success->fail,success,fail,,"game_1baf0c.py:144: error: Unsupported left operand type for + (""None"") [operator]"
o1-mini,gas_reserve_f132a8.py,success->fail,success,fail,,gas_reserve_f132a8.py:77: error: invalid syntax [syntax]
o1-mini,geo_location_c45ba4.py,success->fail,success,fail,,geo_location_c45ba4.py:153: error: Missing return statement [return]
o1-mini,google_config_4b4b29.py,success->fail,success,fail,,"google_config_4b4b29.py:98: error: Name ""split_entity_id"" is not defined [name-defined]"
o1-mini,hashing_3bf140.py,success->fail,success,fail,,"hashing_3bf140.py:129: error: Argument 1 to ""iter"" has incompatible type ""chain[Any]""; expected ""SupportsIter[Generator[Any, None, None]]"" [arg-type]"
o1-mini,header_990b83.py,fail->success,fail,success,"header_990b83.py:142: error: Incompatible return value type (got ""None"", expected ""Tuple[Tuple[Any, ...], Tuple[Any, ...]]"") [return-value]",
o1-mini,headers_8374b8.py,fail->success,fail,success,headers_8374b8.py:64: error: X | Y syntax for unions requires Python 3.10 [syntax],
o1-mini,helpers_062f96.py,fail->success,fail,success,"helpers_062f96.py:43: error: Item ""None"" of ""Optional[Iterable[str]]"" has no attribute ""__iter__"" (not iterable) [union-attr]",
o1-mini,helpers_e73aba.py,fail->success,fail,success,"helpers_e73aba.py:140: error: Name ""cast"" is not defined [name-defined]",
o1-mini,home_349a7c.py,fail->success,fail,success,"home_349a7c.py:209: error: Item ""None"" of ""Optional[List[Any]]"" has no attribute ""__iter__"" (not iterable) [union-attr]",
o1-mini,httpserver_262275.py,success->fail,success,fail,,"httpserver_262275.py:229: error: Argument 4 to ""_HTTPRequestContext"" has incompatible type ""Set[str]""; expected ""Optional[List[str]]"" [arg-type]"
o1-mini,humidifier_e2948a.py,success->fail,success,fail,,"humidifier_e2948a.py:355: error: Incompatible types in assignment (expression has type ""int"", variable has type ""Optional[str]"") [assignment]"
o1-mini,indicators_960952.py,success->fail,success,fail,,indicators_960952.py:19: error: Too few arguments [call-arg]
o1-mini,interleaving_dataset_reader_c0729d.py,success->fail,success,fail,,"interleaving_dataset_reader_c0729d.py:63: error: No overload variant of ""next"" matches argument type ""Iterable[Any]"" [call-overload]"
o1-mini,invites_f24478.py,success->fail,success,fail,,"invites_f24478.py:189: error: Name ""Set"" is not defined [name-defined]"
o1-mini,jediusages_96bc8b.py,success->fail,success,fail,,"jediusages_96bc8b.py:27: error: Argument 1 to ""_jump"" of ""JediUsages"" has incompatible type ""*Tuple[Union[str, int], Optional[int], Optional[int], Optional[Any]]""; expected ""bool"" [arg-type]"
o1-mini,lambda_dataset_8c1015.py,success->fail,success,fail,,"lambda_dataset_8c1015.py:47: error: Function ""__load"" could always be true in boolean context [truthy-function]"
o1-mini,light_3c0a4b.py,fail->success,fail,success,"light_3c0a4b.py:306: error: ""None"" object is not iterable [misc]",
o1-mini,light_ae238e.py,success->fail,success,fail,,"light_ae238e.py:62: error: Incompatible types in assignment (expression has type ""None"", variable has type ""str"") [assignment]"
o1-mini,light_d31785.py,success->fail,success,fail,,light_d31785.py:62: error: Unexpected type declaration [misc]
o1-mini,log_config_fb42e8.py,success->fail,success,fail,,"log_config_fb42e8.py:182: error: List item 2 has incompatible type ""Callable[[Any, str, Dict[str, Any]], Dict[str, Any]]""; expected ""Callable[[Any], Any]"" [list-item]"
o1-mini,log_writer_c4397a.py,fail->success,fail,success,"log_writer_c4397a.py:278: error: Item ""None"" of ""Optional[Any]"" has no attribute ""model"" [union-attr]",
o1-mini,manifest_87d3d1.py,success->fail,success,fail,,"manifest_87d3d1.py:278: error: Name ""test_name_part"" is used before definition [used-before-def]"
o1-mini,media_player_f3d659.py,fail->success,fail,success,"media_player_f3d659.py:73: error: Name ""Any"" is not defined [name-defined]",
o1-mini,media_source_5cb2e6.py,success->fail,success,fail,,"media_source_5cb2e6.py:319: error: Item ""None"" of ""Optional[Any]"" has no attribute ""identifier"" [union-attr]"
o1-mini,mediation_fee_f1a080.py,fail->success,fail,success,mediation_fee_f1a080.py:293: error: invalid syntax [syntax],
o1-mini,mediator_edd547.py,success->fail,success,fail,,"mediator_edd547.py:282: error: Name ""cast"" is not defined [name-defined]"
o1-mini,message_7557cb.py,fail->success,fail,success,"message_7557cb.py:85: error: Trying to assign name ""code_address"" that is not in ""__slots__"" of type ""message_7557cb.Message"" [misc]",
o1-mini,message_cache_dbda93.py,fail->success,fail,success,"message_cache_dbda93.py:224: error: Argument 2 to ""sew_messages_and_reactions"" has incompatible type ""List[RawReactionRow]""; expected ""Iterable[Dict[str, Any]]"" [arg-type]",
o1-mini,meta_learners_cdb80e.py,success->fail,success,fail,,"meta_learners_cdb80e.py:118: error: Name ""ulift_cols"" is not defined [name-defined]"
o1-mini,model_test_case_905237.py,fail->success,fail,success,"model_test_case_905237.py:304: error: Name ""List"" is not defined [name-defined]",
o1-mini,multitask_data_loader_4fc11f.py,success->fail,success,fail,,"multitask_data_loader_4fc11f.py:169: error: Incompatible types in assignment (expression has type ""Union[int, str, device]"", variable has type ""Optional[device]"") [assignment]"
o1-mini,node_2d78d3.py,success->fail,success,fail,,"node_2d78d3.py:456: error: Variable ""node_2d78d3.TokenNetworkStateChange"" is not valid as a type [valid-type]"
o1-mini,note_76679d.py,fail->success,fail,success,"note_76679d.py:32: error: Argument ""text"" to ""Note"" has incompatible type ""Optional[Any]""; expected ""str"" [arg-type]",
o1-mini,notify_translations_290c75.py,success->fail,success,fail,,"notify_translations_290c75.py:315: error: Argument ""discussion_number"" to ""get_graphql_translation_discussion_comments"" has incompatible type ""Optional[int]""; expected ""int"" [arg-type]"
o1-mini,numpy__844898.py,fail->success,fail,success,"numpy__844898.py:135: error: ""Callable[..., Any]"" has no attribute ""nout"" [attr-defined]",
o1-mini,oauth2_4b34aa.py,fail->success,fail,success,"oauth2_4b34aa.py:160: error: Argument 1 to ""contextmanager"" has incompatible type ""Callable[[Any], AbstractContextManager[None]]""; expected ""Callable[[Any], Iterator[<nothing>]]"" [arg-type]",
o1-mini,objects_2ea8dd.py,success->fail,success,fail,,"objects_2ea8dd.py:391: error: Name ""List"" is not defined [name-defined]"
o1-mini,ops_698940.py,success->fail,success,fail,,"ops_698940.py:220: error: Incompatible types in assignment (expression has type ""Exception"", variable has type ""Optional[Type[BaseException]]"") [assignment]"
o1-mini,optimiser_abeb97.py,success->fail,success,fail,,"optimiser_abeb97.py:133: error: Name ""Tuple"" is not defined [name-defined]"
o1-mini,optimize_reports_05f23c.py,success->fail,success,fail,,"optimize_reports_05f23c.py:205: error: No overload variant of ""__setitem__"" of ""list"" matches argument types ""str"", ""Any"" [call-overload]"
o1-mini,params_3f7432.py,fail->success,fail,success,"params_3f7432.py:23: error: Name ""_Unset"" is not defined [name-defined]",
o1-mini,parquet_a441a6.py,fail->success,fail,success,"parquet_a441a6.py:355: error: Argument ""compression"" to ""write"" of ""BaseImpl"" has incompatible type ""Optional[Literal['snappy', 'gzip', 'brotli', 'lz4', 'zstd']]""; expected ""str"" [arg-type]",
o1-mini,parquetdatahandler_7da7b1.py,success->fail,success,fail,,"parquetdatahandler_7da7b1.py:12: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
o1-mini,parser_utils_3b717f.py,success->fail,success,fail,,"parser_utils_3b717f.py:224: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
o1-mini,pin_fe5cb3.py,fail->success,fail,success,"pin_fe5cb3.py:73: error: Incompatible return value type (got ""Union[bool, int, None]"", expected ""bool"") [return-value]",
o1-mini,postgres_09c46c.py,success->fail,success,fail,,"postgres_09c46c.py:282: error: ""str"" has no attribute ""items"" [attr-defined]"
o1-mini,project_2d0af1.py,success->fail,success,fail,,"project_2d0af1.py:252: error: Incompatible return value type (got ""Iterable[Any]"", expected ""Generator[Any, None, None]"") [return-value]"
o1-mini,project_7870ca.py,success->fail,success,fail,,"project_7870ca.py:418: error: Argument ""project_name"" to ""PartialProject"" has incompatible type ""Optional[Any]""; expected ""str"" [arg-type]"
o1-mini,python_f218d0.py,fail->success,fail,success,"python_f218d0.py:729: error: ""set"" is not subscriptable, use ""typing.Set"" instead [misc]",
o1-mini,query_object_factory_d095d1.py,fail->success,fail,success,"query_object_factory_d095d1.py:18: error: Name ""TYPE_CHECKING"" is not defined [name-defined]",
o1-mini,queue_9bbba9.py,fail->success,fail,success,queue_9bbba9.py:112: error: only single target (not tuple) can be annotated [syntax],
o1-mini,realm_linkifiers_90aa4a.py,success->fail,success,fail,,"realm_linkifiers_90aa4a.py:147: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
o1-mini,realm_settings_e9d618.py,success->fail,success,fail,,"realm_settings_e9d618.py:254: error: ""set"" is not subscriptable, use ""typing.Set"" instead [misc]"
o1-mini,references_c4be98.py,success->fail,success,fail,,"references_c4be98.py:91: error: Incompatible types in assignment (expression has type ""Generator[Any, None, None]"", variable has type ""List[Any]"") [assignment]"
o1-mini,reporter_4f7bfa.py,success->fail,success,fail,,"reporter_4f7bfa.py:69: error: Name ""pyflakes"" is not defined [name-defined]"
o1-mini,reporter_7fc9be.py,fail->success,fail,success,"reporter_7fc9be.py:68: error: Name ""pyflakes"" is not defined [name-defined]",
o1-mini,run_b777ab.py,fail->success,fail,success,"run_b777ab.py:790: error: Item ""None"" of ""Optional[datetime]"" has no attribute ""isoformat"" [union-attr]",
o1-mini,sampler_d1337e.py,fail->success,fail,success,"sampler_d1337e.py:38: error: Incompatible types in assignment (expression has type ""float"", target has type ""int"") [assignment]",
o1-mini,schema_ee7352.py,fail->success,fail,success,"schema_ee7352.py:101: error: ""Callable[..., Any]"" has no attribute ""_should_curry"" [attr-defined]",
o1-mini,schemas_b7d3bb.py,fail->success,fail,success,"schemas_b7d3bb.py:68: error: Name ""Mapping"" is not defined [name-defined]",
o1-mini,sensor_1c6e89.py,fail->success,fail,success,"sensor_1c6e89.py:91: error: Incompatible types in assignment (expression has type ""Dict[<nothing>, <nothing>]"", variable has type ""Optional[Dict[str, ArwnSensor]]"") [assignment]",
o1-mini,sensor_3f0300.py,fail->success,fail,success,"sensor_3f0300.py:96: error: Argument 5 to ""AirzoneZoneSensor"" has incompatible type ""Optional[Any]""; expected ""Dict[str, Any]"" [arg-type]",
o1-mini,sensor_51937f.py,fail->success,fail,success,"sensor_51937f.py:190: error: Incompatible types in assignment (expression has type ""Optional[str]"", variable has type ""str"") [assignment]",
o1-mini,sensor_875fbc.py,fail->success,fail,success,"sensor_875fbc.py:160: error: Invalid index type ""Union[str, int]"" for ""Dict[str, str]""; expected type ""str"" [index]",
o1-mini,sensor_bd2e29.py,success->fail,success,fail,,"sensor_bd2e29.py:257: error: Incompatible types in assignment (expression has type ""FrozenSet[Any]"", variable has type ""Set[str]"") [assignment]"
o1-mini,sensor_c43e72.py,success->fail,success,fail,,"sensor_c43e72.py:313: error: Name ""Callable"" is not defined [name-defined]"
o1-mini,sensor_dd9269.py,success->fail,success,fail,,sensor_dd9269.py:33: error: Attributes without a default cannot follow attributes with one [misc]
o1-mini,sensor_e47032.py,success->fail,success,fail,,"sensor_e47032.py:103: error: Value of type ""Optional[Dict[str, Any]]"" is not indexable [index]"
o1-mini,sensor_e99c97.py,success->fail,success,fail,,"sensor_e99c97.py:182: error: Dict entry 0 has incompatible type ""str"": ""Optional[str]""; expected ""str"": ""str"" [dict-item]"
o1-mini,sensor_f28e92.py,fail->success,fail,success,"sensor_f28e92.py:82: error: Incompatible types in assignment (expression has type ""Optional[str]"", variable has type ""str"") [assignment]",
o1-mini,sensor_f43589.py,success->fail,success,fail,,"sensor_f43589.py:101: error: Item ""None"" of ""Optional[Any]"" has no attribute ""render_with_possible_json_value"" [union-attr]"
o1-mini,sensor_f8d27b.py,fail->success,fail,success,"sensor_f8d27b.py:153: error: Unsupported operand types for > (""float"" and ""None"") [operator]",
o1-mini,sentiment_analysis_suite_5e67f5.py,fail->success,fail,success,"sentiment_analysis_suite_5e67f5.py:483: error: Name ""profession"" is not defined [name-defined]",
o1-mini,sequence_accuracy_test_b352af.py,fail->success,fail,success,"sequence_accuracy_test_b352af.py:98: error: Incompatible types in assignment (expression has type ""List[Tensor]"", variable has type ""Tensor"") [assignment]",
o1-mini,service_registry_e94e0b.py,fail->success,fail,success,"service_registry_e94e0b.py:75: error: Incompatible types in assignment (expression has type ""None"", variable has type ""bool"") [assignment]",
o1-mini,shard_block_395422.py,fail->success,fail,success,"shard_block_395422.py:12: error: Name ""Spec"" is not defined [name-defined]",
o1-mini,signals_ff12b9.py,fail->success,fail,success,"signals_ff12b9.py:62: error: Item ""None"" of ""Optional[Any]"" has no attribute ""app"" [union-attr]",
o1-mini,spacy_tokenizer_edae48.py,fail->success,fail,success,"spacy_tokenizer_edae48.py:117: error: Dict entry 0 has incompatible type ""str"": ""str""; expected ""str"": ""Optional[List[str]]"" [dict-item]",
o1-mini,span_utils_b17f45.py,fail->success,fail,success,"span_utils_b17f45.py:66: error: Argument 1 to ""append"" of ""list"" has incompatible type ""Tuple[int, int]""; expected ""Tuple[int, Tuple[int, int]]"" [arg-type]",
o1-mini,sparse_a2c123.py,fail->success,fail,success,sparse_a2c123.py:243: error: closing parenthesis ')' does not match opening parenthesis '[' on line 242 [syntax],
o1-mini,sqla_models_tests_7b5225.py,success->fail,success,fail,,"sqla_models_tests_7b5225.py:221: error: Name ""Tuple"" is not defined [name-defined]"
o1-mini,states_8ed126.py,fail->success,fail,success,"states_8ed126.py:439: error: ""Counter"" expects 1 type argument, but 2 given [type-arg]",
o1-mini,staticfiles_164434.py,fail->success,fail,success,"staticfiles_164434.py:69: error: Function ""importlib.util.spec_from_loader"" is not valid as a type [valid-type]",
o1-mini,string_arrow_ce4e9d.py,success->fail,success,fail,,"string_arrow_ce4e9d.py:432: error: Name ""NoReturn"" is not defined [name-defined]"
o1-mini,switch_67758e.py,fail->success,fail,success,"switch_67758e.py:228: error: Name ""Callable"" is not defined [name-defined]",
o1-mini,switch_813f86.py,success->fail,success,fail,,"switch_813f86.py:135: error: Name ""async_generate_entity_id"" is not defined [name-defined]"
o1-mini,switch_8d0b59.py,fail->success,fail,success,switch_8d0b59.py:71: error: X | Y syntax for unions requires Python 3.10 [syntax],
o1-mini,sync_committee_b34f1b.py,success->fail,success,fail,,"sync_committee_b34f1b.py:10: error: Name ""Spec"" is not defined [name-defined]"
o1-mini,task_suite_e75451.py,success->fail,success,fail,,"task_suite_e75451.py:91: error: Incompatible return value type (got ""Type[NotImplementedError]"", expected ""Callable[[Any], Tuple[Any, Any]]"") [return-value]"
o1-mini,tcpclient_c8e77d.py,success->fail,success,fail,,"tcpclient_c8e77d.py:206: error: Incompatible types in assignment (expression has type ""None"", variable has type ""float"") [assignment]"
o1-mini,template_entity_f0503d.py,success->fail,success,fail,,"template_entity_f0503d.py:320: error: Unsupported target for indexed assignment (""Mapping[str, Any]"") [index]"
o1-mini,test_accessor_fe2995.py,success->fail,success,fail,,"test_accessor_fe2995.py:31: error: Name ""scipy_sparse.coo_matrix"" is not defined [name-defined]"
o1-mini,test_arithmetics_2d6e2b.py,fail->success,fail,success,"test_arithmetics_2d6e2b.py:65: error: Item ""bool"" of ""Union[Any, bool]"" has no attribute ""to_dense"" [union-attr]",
o1-mini,test_assert_frame_equal_d9bb56.py,success->fail,success,fail,,"test_assert_frame_equal_d9bb56.py:9: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
o1-mini,test_base_299dbf.py,fail->success,fail,success,"test_base_299dbf.py:131: error: Name ""Any"" is not defined [name-defined]",
o1-mini,test_base_indexer_9339e3.py,fail->success,fail,success,"test_base_indexer_9339e3.py:263: error: Name ""pd"" is not defined [name-defined]",
o1-mini,test_blocks_31cb5c.py,success->fail,success,fail,,test_blocks_31cb5c.py:9: error: Missing return statement [return]
o1-mini,test_btanalysis_4aed6c.py,success->fail,success,fail,,"test_btanalysis_4aed6c.py:466: error: No overload variant of ""zip"" matches argument types ""List[float]"", ""List[datetime]"", ""bool"" [call-overload]"
o1-mini,test_cat_c39959.py,fail->success,fail,success,"test_cat_c39959.py:31: error: Incompatible types in assignment (expression has type ""List[str]"", variable has type ""Optional[Callable[..., Union[Any, Any]]]"") [assignment]",
o1-mini,test_category_67f90a.py,fail->success,fail,success,"test_category_67f90a.py:268: error: Argument 2 to ""isinstance"" has incompatible type ""Callable[..., Any]""; expected ""_ClassInfo"" [arg-type]",
o1-mini,test_ccxt_compat_f96503.py,success->fail,success,fail,,test_ccxt_compat_f96503.py:23: error: Missing return statement [empty-body]
o1-mini,test_channel_622ed8.py,fail->success,fail,success,test_channel_622ed8.py:621: error: only single target (not tuple) can be annotated [syntax],
o1-mini,test_client_1103c5.py,fail->success,fail,success,"test_client_1103c5.py:148: error: Name ""Awaitable"" is not defined [name-defined]",
o1-mini,test_compilation_513485.py,fail->success,fail,success,test_compilation_513485.py:144: error: invalid syntax [syntax],
o1-mini,test_constructors_02070a.py,success->fail,success,fail,,"test_constructors_02070a.py:108: error: Name ""pa.Array"" is not defined [name-defined]"
o1-mini,test_contract_call_6ddf95.py,success->fail,success,fail,,"test_contract_call_6ddf95.py:147: error: Argument 1 to ""raises"" has incompatible type ""Union[Exception, Any]""; expected ""Union[Type[Any], Tuple[Type[Any], ...]]"" [arg-type]"
o1-mini,test_convert_dtypes_c20223.py,success->fail,success,fail,,test_convert_dtypes_c20223.py:172: error: invalid syntax [syntax]
o1-mini,test_converter_orderflow_7dad6d.py,fail->success,fail,success,"test_converter_orderflow_7dad6d.py:271: error: Unsupported left operand type for | (""Dict[str, Any]"") [operator]",
o1-mini,test_coop_settle_fd62d3.py,fail->success,fail,success,"test_coop_settle_fd62d3.py:22: error: Name ""ChannelState"" is not defined [name-defined]",
o1-mini,test_cumulative_8df6e0.py,fail->success,fail,success,"test_cumulative_8df6e0.py:15: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]",
o1-mini,test_deposit_93dc29.py,success->fail,success,fail,,"test_deposit_93dc29.py:94: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
o1-mini,test_drop_duplicates_d918e0.py,fail->success,fail,success,test_drop_duplicates_d918e0.py:54: error: X | Y syntax for unions requires Python 3.10 [syntax],
o1-mini,test_drop_duplicates_ed341e.py,success->fail,success,fail,,"test_drop_duplicates_ed341e.py:384: error: Name ""pd"" is not defined [name-defined]"
o1-mini,test_dtypes_1ace40.py,fail->success,fail,success,"test_dtypes_1ace40.py:8: error: Module ""pytest"" has no attribute ""FixtureRequest"" [attr-defined]",
o1-mini,test_dtypes_c6ad71.py,success->fail,success,fail,,"test_dtypes_c6ad71.py:366: error: Name ""pytz.BaseTzInfo"" is not defined [name-defined]"
o1-mini,test_encoding_e05f99.py,fail->success,fail,success,"test_encoding_e05f99.py:201: error: ""Callable[[Any], Any]"" has no attribute ""assert_called_with"" [attr-defined]",
o1-mini,test_entity_registry_95c378.py,success->fail,success,fail,,"test_entity_registry_95c378.py:406: error: Name ""pytest.LogCaptureFixture"" is not defined [name-defined]"
o1-mini,test_extension_socket_server_334931.py,success->fail,success,fail,,"test_extension_socket_server_334931.py:10: error: Name ""pytest.MockFixture"" is not defined [name-defined]"
o1-mini,test_filter_rewriting_c801f7.py,fail->success,fail,success,"test_filter_rewriting_c801f7.py:478: error: Name ""two"" is not defined [name-defined]",
o1-mini,test_frame_plot_matplotlib_9669ca.py,fail->success,fail,success,test_frame_plot_matplotlib_9669ca.py:124: error: X | Y syntax for unions requires Python 3.10 [syntax],
o1-mini,test_frame_plot_plotly_91dfd7.py,fail->success,fail,success,"test_frame_plot_plotly_91dfd7.py:131: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]",
o1-mini,test_freqai_interface_ca78dd.py,success->fail,success,fail,,"test_freqai_interface_ca78dd.py:245: error: Name ""pytest.LogCaptureFixture"" is not defined [name-defined]"
o1-mini,test_graph_selection_f68296.py,fail->success,fail,success,"test_graph_selection_f68296.py:14: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]",
o1-mini,test_groupby_86d3bc.py,fail->success,fail,success,"test_groupby_86d3bc.py:935: error: Argument 1 to ""update"" of ""MutableMapping"" has incompatible type ""Dict[str, List[Union[float, Any]]]""; expected ""SupportsKeysAndGetItem[str, List[str]]"" [arg-type]",
o1-mini,test_hashtable_89c8a4.py,fail->success,fail,success,"test_hashtable_89c8a4.py:220: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]",
o1-mini,test_img_util_826a0b.py,fail->success,fail,success,"test_img_util_826a0b.py:76: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]",
o1-mini,test_incremental_on_schema_change_ffcc97.py,success->fail,success,fail,,"test_incremental_on_schema_change_ffcc97.py:46: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
o1-mini,test_index_503dc5.py,fail->success,fail,success,"test_index_503dc5.py:12: error: Module ""pytest"" has no attribute ""FixtureRequest"" [attr-defined]",
o1-mini,test_index_d51bbf.py,fail->success,fail,success,"test_index_d51bbf.py:220: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]",
o1-mini,test_indexing_3e5a66.py,fail->success,fail,success,"test_indexing_3e5a66.py:72: error: Name ""pytest.MonkeyPatch"" is not defined [name-defined]",
o1-mini,test_indexing_8b3a8e.py,fail->success,fail,success,test_indexing_8b3a8e.py:46: error: X | Y syntax for unions requires Python 3.10 [syntax],
o1-mini,test_indexing_e492e0.py,success->fail,success,fail,,test_indexing_e492e0.py:22: error: X | Y syntax for unions requires Python 3.10 [syntax]
o1-mini,test_indexing_f4eafd.py,fail->success,fail,success,"test_indexing_f4eafd.py:313: error: Name ""pytest.MonkeyPatch"" is not defined [name-defined]",
o1-mini,test_indices_7db737.py,fail->success,fail,success,test_indices_7db737.py:11: error: Invalid type alias: expression is not a valid type [valid-type],
o1-mini,test_inference_f5d827.py,fail->success,fail,success,test_inference_f5d827.py:129: error: invalid syntax [syntax],
o1-mini,test_init_75a7d5.py,success->fail,success,fail,,test_init_75a7d5.py:152: error: X | Y syntax for unions requires Python 3.10 [syntax]
o1-mini,test_integration_ae2f32.py,success->fail,success,fail,,"test_integration_ae2f32.py:451: error: Name ""pytest.LogCaptureFixture"" is not defined [name-defined]"
o1-mini,test_interval_3fb811.py,fail->success,fail,success,test_interval_3fb811.py:244: error: Missing return statement [return],
o1-mini,test_invalid_arg_f69c9f.py,success->fail,success,fail,,"test_invalid_arg_f69c9f.py:146: error: Argument 1 to ""raises"" has incompatible type ""Union[Exception, Any]""; expected ""Union[Type[Any], Tuple[Type[Any], ...]]"" [arg-type]"
o1-mini,test_join_48601a.py,success->fail,success,fail,,"test_join_48601a.py:535: error: Name ""CategoricalIndex"" is not defined [name-defined]"
o1-mini,test_json_table_schema_ext_dtype_03d9d8.py,fail->success,fail,success,"test_json_table_schema_ext_dtype_03d9d8.py:106: error: Invalid index type ""str"" for ""str""; expected type ""Union[SupportsIndex, slice]"" [index]",
o1-mini,test_layers_95be9f.py,fail->success,fail,success,"test_layers_95be9f.py:75: error: No overload variant of ""__getitem__"" of ""tuple"" matches argument type ""Tuple[int, int]"" [call-overload]",
o1-mini,test_logging_8b4caf.py,fail->success,fail,success,"test_logging_8b4caf.py:84: error: Name ""pytest.CaptureFixture"" is not defined [name-defined]",
o1-mini,test_logical_ops_b270a9.py,success->fail,success,fail,,test_logical_ops_b270a9.py:23: error: X | Y syntax for unions requires Python 3.10 [syntax]
o1-mini,test_london_5cebb4.py,fail->success,fail,success,"test_london_5cebb4.py:34: error: Name ""Type"" is not defined [name-defined]",
o1-mini,test_mediatedtransfer_invalid_c11287.py,success->fail,success,fail,,test_mediatedtransfer_invalid_c11287.py:320: error: closing parenthesis '}' does not match opening parenthesis '(' on line 297 [syntax]
o1-mini,test_modular_pipeline_544bcc.py,fail->success,fail,success,"test_modular_pipeline_544bcc.py:35: error: Name ""pipeline"" is not defined [name-defined]",
o1-mini,test_moments_consistency_ewm_56b6c2.py,success->fail,success,fail,,test_moments_consistency_ewm_56b6c2.py:6: error: X | Y syntax for unions requires Python 3.10 [syntax]
o1-mini,test_moments_consistency_rolling_0c7eb0.py,success->fail,success,fail,,"test_moments_consistency_rolling_0c7eb0.py:14: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
o1-mini,test_monitor_31e01e.py,success->fail,success,fail,,"test_monitor_31e01e.py:67: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
o1-mini,test_mssql_35a1b8.py,success->fail,success,fail,,"test_mssql_35a1b8.py:217: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
o1-mini,test_numba_246dfa.py,success->fail,success,fail,,"test_numba_246dfa.py:108: error: Name ""DataFrameGroupBy"" is not defined [name-defined]"
o1-mini,test_numeric_only_37163c.py,fail->success,fail,success,"test_numeric_only_37163c.py:9: error: Module ""pytest"" has no attribute ""FixtureRequest"" [attr-defined]",
o1-mini,test_objects_7b7ddb.py,success->fail,success,fail,,test_objects_7b7ddb.py:189: error: Type cannot be declared in assignment to non-self attribute [misc]
o1-mini,test_operations_088d14.py,success->fail,success,fail,,"test_operations_088d14.py:9: error: Name ""BeaconState"" is not defined [name-defined]"
o1-mini,test_process_block_header_67cc9f.py,fail->success,fail,success,"test_process_block_header_67cc9f.py:10: error: Name ""Spec"" is not defined [name-defined]",
o1-mini,test_process_participation_flag_updates_24798c.py,fail->success,fail,success,"test_process_participation_flag_updates_24798c.py:15: error: Name ""Spec"" is not defined [name-defined]",
o1-mini,test_process_pending_consolidations_a9c6ec.py,fail->success,fail,success,"test_process_pending_consolidations_a9c6ec.py:134: error: Name ""BeaconState"" is not defined [name-defined]",
o1-mini,test_process_sync_aggregate_c588af.py,success->fail,success,fail,,test_process_sync_aggregate_c588af.py:202: error: No return value expected [return-value]
o1-mini,test_process_voluntary_exit_d70212.py,fail->success,fail,success,"test_process_voluntary_exit_d70212.py:11: error: Name ""Spec"" is not defined [name-defined]",
o1-mini,test_process_withdrawal_request_9f973e.py,fail->success,fail,success,"test_process_withdrawal_request_9f973e.py:11: error: Name ""Spec"" is not defined [name-defined]",
o1-mini,test_prometheus_2a91bc.py,fail->success,fail,success,"test_prometheus_2a91bc.py:62: error: Name ""pytest.MonkeyPatch"" is not defined [name-defined]",
o1-mini,test_protections_3ce579.py,fail->success,fail,success,"test_protections_3ce579.py:5: error: Module ""pytest"" has no attribute ""LogCaptureFixture"" [attr-defined]",
o1-mini,test_pythonapi_d455c1.py,fail->success,fail,success,"test_pythonapi_d455c1.py:174: error: ""set"" is not subscriptable, use ""typing.Set"" instead [misc]",
o1-mini,test_qcut_5ee678.py,fail->success,fail,success,test_qcut_5ee678.py:286: error: Invalid type comment or annotation [valid-type],
o1-mini,test_quantile_94afc3.py,fail->success,fail,success,"test_quantile_94afc3.py:15: error: Incompatible return value type (got ""Tuple[Any, ...]"", expected ""Tuple[str, str]"") [return-value]",
o1-mini,test_raidenservice_d5e26d.py,success->fail,success,fail,,"test_raidenservice_d5e26d.py:55: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
o1-mini,test_rank_19ec93.py,success->fail,success,fail,,"test_rank_19ec93.py:374: error: ""str"" has no attribute ""storage"" [attr-defined]"
o1-mini,test_rank_d0371a.py,fail->success,fail,success,"test_rank_d0371a.py:32: error: ""List[Any]"" has no attribute ""reindex""; maybe ""index""? [attr-defined]",
o1-mini,test_read_fwf_ec1bf4.py,success->fail,success,fail,,"test_read_fwf_ec1bf4.py:291: error: Incompatible types in assignment (expression has type ""Tuple[Tuple[int, int], Tuple[int, int], Tuple[int, int], Tuple[int, int]]"", variable has type ""List[Tuple[Optional[int], Optional[int]]]"") [assignment]"
o1-mini,test_recovery_2d8e5e.py,success->fail,success,fail,,"test_recovery_2d8e5e.py:171: error: ""Counter"" is not subscriptable, use ""typing.Counter"" instead [misc]"
o1-mini,test_regression_05a4bf.py,success->fail,success,fail,,"test_regression_05a4bf.py:225: error: Name ""Address"" is not defined [name-defined]"
o1-mini,test_rocksdb_e6756b.py,success->fail,success,fail,,"test_rocksdb_e6756b.py:68: error: The return type of a generator function should be ""Generator"" or one of its supertypes [misc]"
o1-mini,test_rolling_741e1f.py,success->fail,success,fail,,"test_rolling_741e1f.py:205: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
o1-mini,test_rolling_functions_251098.py,fail->success,fail,success,"test_rolling_functions_251098.py:124: error: Name ""pd"" is not defined [name-defined]",
o1-mini,test_round_0a4ab4.py,fail->success,fail,success,"test_round_0a4ab4.py:128: error: Unexpected keyword argument ""ambiguous"" [call-arg]",
o1-mini,test_round_faa621.py,fail->success,fail,success,"test_round_faa621.py:158: error: Name ""pd"" is not defined [name-defined]",
o1-mini,test_rpc_0215ce.py,success->fail,success,fail,,"test_rpc_0215ce.py:27: error: Name ""pytest.MockerFixture"" is not defined [name-defined]"
o1-mini,test_sas7bdat_0ac638.py,fail->success,fail,success,"test_sas7bdat_0ac638.py:224: error: Name ""Optional"" is not defined [name-defined]",
o1-mini,test_selector_29872e.py,success->fail,success,fail,,"test_selector_29872e.py:34: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
o1-mini,test_selector_bbc47d.py,success->fail,success,fail,,"test_selector_bbc47d.py:1322: error: Argument 4 to ""_test_selector"" has incompatible type ""Union[str, Any]""; expected ""Tuple[Any, ...]"" [arg-type]"
o1-mini,test_sequential_runner_021190.py,success->fail,success,fail,,"test_sequential_runner_021190.py:31: error: Name ""pytest.LogCaptureFixture"" is not defined [name-defined]"
o1-mini,test_series_5f79c1.py,fail->success,fail,success,"test_series_5f79c1.py:220: error: Name ""Optional"" is not defined [name-defined]",
o1-mini,test_series_apply_554287.py,fail->success,fail,success,"test_series_apply_554287.py:19: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]",
o1-mini,test_session_extension_hooks_7b3b93.py,success->fail,success,fail,,"test_session_extension_hooks_7b3b93.py:63: error: Name ""pytest.LogCaptureFixture"" is not defined [name-defined]"
o1-mini,test_session_hook_manager_b0d853.py,fail->success,fail,success,"test_session_hook_manager_b0d853.py:12: error: Module ""pytest"" has no attribute ""LogCaptureFixture"" [attr-defined]",
o1-mini,test_setops_3892f2.py,success->fail,success,fail,,"test_setops_3892f2.py:107: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
o1-mini,test_sort_index_efa5b2.py,success->fail,success,fail,,"test_sort_index_efa5b2.py:8: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
o1-mini,test_sorting_c07df0.py,fail->success,fail,success,"test_sorting_c07df0.py:244: error: ""defaultdict"" is not subscriptable, use ""typing.DefaultDict"" instead [misc]",
o1-mini,test_spark_0e0bdf.py,fail->success,fail,success,test_spark_0e0bdf.py:97: error: cannot use assignment expressions with attribute [syntax],
o1-mini,test_statsd_afaa78.py,fail->success,fail,success,"test_statsd_afaa78.py:20: error: Name ""pytest.MonkeyPatch"" is not defined [name-defined]",
o1-mini,test_stress_590c48.py,success->fail,success,fail,,"test_stress_590c48.py:199: error: Unsupported left operand type for + (""Sequence[Any]"") [operator]"
o1-mini,test_tables_ba47a0.py,fail->success,fail,success,"test_tables_ba47a0.py:18: error: Argument 1 to ""contextmanager"" has incompatible type ""Callable[[bool], AbstractContextManager[None]]""; expected ""Callable[[bool], Iterator[<nothing>]]"" [arg-type]",
o1-mini,test_thread_runner_e54f5d.py,fail->success,fail,success,"test_thread_runner_e54f5d.py:52: error: Name ""pytest.LogCaptureFixture"" is not defined [name-defined]",
o1-mini,test_timedelta64_f628bf.py,fail->success,fail,success,"test_timedelta64_f628bf.py:897: error: Item ""datetime"" of ""Union[Any, datetime, Any]"" has no attribute ""to_pydatetime"" [union-attr]",
o1-mini,test_to_latex_4e44c5.py,success->fail,success,fail,,test_to_latex_4e44c5.py:520: error: List comprehension has incompatible type List[Optional[str]]; expected List[str] [misc]
o1-mini,test_union_categoricals_f7953f.py,success->fail,success,fail,,"test_union_categoricals_f7953f.py:107: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
o1-mini,test_utils_014a22.py,fail->success,fail,success,test_utils_014a22.py:409: error: invalid syntax [syntax],
o1-mini,test_validate_docstrings_1ce531.py,success->fail,success,fail,,"test_validate_docstrings_1ce531.py:117: error: Name ""pytest.CaptureFixture"" is not defined [name-defined]"
o1-mini,test_validator_417f9a.py,fail->success,fail,success,"test_validator_417f9a.py:123: error: ""tuple"" is not subscriptable, use ""typing.Tuple"" instead [misc]",
o1-mini,text_classification_json_d0a412.py,fail->success,fail,success,"text_classification_json_d0a412.py:77: error: Incompatible types in assignment (expression has type ""Union[str, int]"", variable has type ""str"") [assignment]",
o1-mini,timerange_d18ed2.py,success->fail,success,fail,,"timerange_d18ed2.py:115: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
o1-mini,token_8cf4ee.py,success->fail,success,fail,,"token_8cf4ee.py:66: error: Incompatible types in assignment (expression has type ""Optional[Any]"", variable has type ""List[str]"") [assignment]"
o1-mini,token_network_3f385b.py,fail->success,fail,success,"token_network_3f385b.py:49: error: Variable ""token_network_3f385b.StateChangeWithChannelID"" is not valid as a type [valid-type]",
o1-mini,toolkit_test_11b0e6.py,success->fail,success,fail,,"toolkit_test_11b0e6.py:166: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
o1-mini,transactions_8ddaaa.py,success->fail,success,fail,,"transactions_8ddaaa.py:52: error: Incompatible default for argument ""chain_id"" (default has type ""None"", argument has type ""int"") [assignment]"
o1-mini,transfers_b8ecf0.py,fail->success,fail,success,"transfers_b8ecf0.py:182: error: Name ""ClassVar"" is not defined [name-defined]",
o1-mini,tts_59d132.py,success->fail,success,fail,,"tts_59d132.py:78: error: Function ""builtins.any"" is not valid as a type [valid-type]"
o1-mini,tts_834735.py,fail->success,fail,success,"tts_834735.py:54: error: Argument 1 to ""Path"" has incompatible type ""Optional[str]""; expected ""Union[str, PathLike[str]]"" [arg-type]",
o1-mini,type_cameras_3d7c68.py,fail->success,fail,success,type_cameras_3d7c68.py:202: error: invalid syntax [syntax],
o1-mini,type_remotes_f2ab28.py,fail->success,fail,success,type_remotes_f2ab28.py:167: error: Missing return statement [return],
o1-mini,type_var_a00119.py,success->fail,success,fail,,"type_var_a00119.py:11: error: Name ""LazyValue"" is not defined [name-defined]"
o1-mini,typing_c8a53e.py,success->fail,success,fail,,"typing_c8a53e.py:22: error: Function ""builtins.any"" is not valid as a type [valid-type]"
o1-mini,typing_fe369a.py,fail->success,fail,success,"typing_fe369a.py:36: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]",
o1-mini,user_groups_977a0b.py,success->fail,success,fail,,"user_groups_977a0b.py:169: error: Item ""None"" of ""Optional[Sequence[Any]]"" has no attribute ""__iter__"" (not iterable) [union-attr]"
o1-mini,user_topics_1dd5f1.py,success->fail,success,fail,,"user_topics_1dd5f1.py:204: error: Name ""TypedDict"" is not defined [name-defined]"
o1-mini,utils_3f6c97.py,success->fail,success,fail,,"utils_3f6c97.py:191: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
o1-mini,utils_71116c.py,fail->success,fail,success,"utils_71116c.py:28: error: Incompatible import of ""generate_password_hash"" (imported name has type ""Callable[[str, str, int], str]"", local name has type ""Callable[[Union[str, bytes]], str]"") [assignment]",
o1-mini,utils_a09b8c.py,success->fail,success,fail,,"utils_a09b8c.py:241: error: Incompatible types in assignment (expression has type ""MappingProxyType[str, Parameter]"", variable has type ""Dict[str, Parameter]"") [assignment]"
o1-mini,vagrant_71cd9c.py,success->fail,success,fail,,"vagrant_71cd9c.py:24: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
o1-mini,validators_1837b8.py,success->fail,success,fail,,"validators_1837b8.py:50: error: Name ""PARM_IS_LEAL"" is not defined [name-defined]"
o1-mini,voluntary_exits_96290c.py,success->fail,success,fail,,"voluntary_exits_96290c.py:9: error: Name ""Spec"" is not defined [name-defined]"
o1-mini,water_heater_44e018.py,fail->success,fail,success,"water_heater_44e018.py:63: error: Incompatible types in assignment (expression has type ""Optional[bool]"", variable has type ""bool"") [assignment]",
o1-mini,withdrawals_7e4651.py,fail->success,fail,success,"withdrawals_7e4651.py:5: error: Name ""Spec"" is not defined [name-defined]",
deepseek,PyTorchModelTrainer_91f360.py,success->fail,success,fail,,"PyTorchModelTrainer_91f360.py:61: error: ""SummaryWriter"" has no attribute ""log_scalar"" [attr-defined]"
deepseek,__init___3afdb9.py,fail->success,fail,success,"__init___3afdb9.py:38: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]",
deepseek,__init___49f91b.py,success->fail,success,fail,,"__init___49f91b.py:4: error: ""object"" has no attribute ""check"" [attr-defined]"
deepseek,__init___97fa7b.py,fail->success,fail,success,"__init___97fa7b.py:125: error: ""CodeType"" has no attribute ""errors"" [attr-defined]",
deepseek,__init___9a6f7a.py,fail->success,fail,success,"__init___9a6f7a.py:5: error: Module ""typing"" has no attribute ""NotRequired"" [attr-defined]",
deepseek,__init___a5a747.py,success->fail,success,fail,,"__init___a5a747.py:54: error: Argument 1 to ""MinioListener"" has incompatible type ""Queue[Optional[Dict[str, Any]]]""; expected ""Queue[Dict[str, Any]]"" [arg-type]"
deepseek,__init___cd0888.py,fail->success,fail,success,__init___cd0888.py:69: error: invalid syntax [syntax],
deepseek,_config_c8d42c.py,fail->success,fail,success,"_config_c8d42c.py:70: error: Cannot determine type of ""connect"" [has-type]",
deepseek,agents_3f7d1d.py,fail->success,fail,success,agents_3f7d1d.py:27: error: invalid syntax [syntax],
deepseek,alarm_control_panel_85f407.py,success->fail,success,fail,,alarm_control_panel_85f407.py:341: error: unexpected EOF while parsing [syntax]
deepseek,app_c89ec6.py,fail->success,fail,success,"app_c89ec6.py:129: error: Incompatible default for argument ""key_type"" (default has type ""None"", argument has type ""Type[Any]"") [assignment]",
deepseek,app_e5f00c.py,fail->success,fail,success,app_e5f00c.py:121: error: invalid syntax [syntax],
deepseek,attachment_scores_test_b605c1.py,success->fail,success,fail,,"attachment_scores_test_b605c1.py:26: error: Argument 1 to ""_send_tensors_to_device"" of ""AttachmentScoresTest"" has incompatible type ""str""; expected ""device"" [arg-type]"
deepseek,auth_0ecea0.py,fail->success,fail,success,"auth_0ecea0.py:77: error: Argument ""purpose"" to ""create_default_context"" has incompatible type ""Optional[Any]""; expected ""Purpose"" [arg-type]",
deepseek,base_d18b00.py,fail->success,fail,success,base_d18b00.py:48: error: Protocol members cannot be defined via assignment to self [misc],
deepseek,bias_direction_wrappers_2ab1fb.py,fail->success,fail,success,"bias_direction_wrappers_2ab1fb.py:92: error: ""Tensor"" not callable [operator]",
deepseek,bias_mitigator_wrappers_4e83be.py,success->fail,success,fail,,"bias_mitigator_wrappers_4e83be.py:78: error: Incompatible types in assignment (expression has type ""Tensor"", variable has type ""List[Tensor]"") [assignment]"
deepseek,bias_mitigators_adad59.py,success->fail,success,fail,,bias_mitigators_adad59.py:213: error: Missing return statement [return]
deepseek,binary_sensor_950ee8.py,success->fail,success,fail,,binary_sensor_950ee8.py:30: error: invalid syntax [syntax]
deepseek,binary_sensor_d63eaf.py,success->fail,success,fail,,binary_sensor_d63eaf.py:18: error: invalid syntax [syntax]
deepseek,bleu_test_22d7f9.py,success->fail,success,fail,,"bleu_test_22d7f9.py:27: error: ""Counter"" is not subscriptable, use ""typing.Counter"" instead [misc]"
deepseek,boxplot_f690b9.py,success->fail,success,fail,,"boxplot_f690b9.py:14: error: Name ""Optional"" is not defined [name-defined]"
deepseek,calendar_b5cdc9.py,success->fail,success,fail,,"calendar_b5cdc9.py:141: error: Function ""datetime.datetime.date"" is not valid as a type [valid-type]"
deepseek,classification_92cb06.py,fail->success,fail,success,classification_92cb06.py:211: error: closing parenthesis ']' does not match opening parenthesis '(' on line 194 [syntax],
deepseek,climate_588757.py,success->fail,success,fail,,"climate_588757.py:353: error: Incompatible return value type (got ""Optional[str]"", expected ""str"") [return-value]"
deepseek,common_285794.py,success->fail,success,fail,,"common_285794.py:5: error: Incompatible default for argument ""select"" (default has type ""None"", argument has type ""str"") [assignment]"
deepseek,common_dde807.py,fail->success,fail,success,common_dde807.py:24: error: invalid syntax [syntax],
deepseek,config_c41598.py,success->fail,success,fail,,config_c41598.py:208: error: invalid syntax [syntax]
deepseek,conftest_0f5d02.py,success->fail,success,fail,,"conftest_0f5d02.py:12: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
deepseek,conftest_823740.py,fail->success,fail,success,conftest_823740.py:369: error: Too few arguments [call-arg],
deepseek,conftest_fea4e8.py,success->fail,success,fail,,"conftest_fea4e8.py:97: error: Invalid index type ""str"" for ""str""; expected type ""Union[SupportsIndex, slice]"" [index]"
deepseek,console_aefea3.py,success->fail,success,fail,,"console_aefea3.py:75: error: Name ""List"" is not defined [name-defined]"
deepseek,coordinator_e4c72e.py,success->fail,success,fail,,coordinator_e4c72e.py:288: error: invalid syntax [syntax]
deepseek,core_6a4e49.py,success->fail,success,fail,,core_6a4e49.py:77: error: Too few arguments [call-arg]
deepseek,core_6bd602.py,success->fail,success,fail,,"core_6bd602.py:231: error: Item ""None"" of ""Optional[Any]"" has no attribute ""compute"" [union-attr]"
deepseek,core_b5776a.py,success->fail,success,fail,,core_b5776a.py:64: error: invalid syntax [syntax]
deepseek,cover_14aabc.py,success->fail,success,fail,,cover_14aabc.py:146: error: invalid syntax [syntax]
deepseek,cyclist_8fa926.py,fail->success,fail,success,"cyclist_8fa926.py:13: error: Name ""Event"" is not defined [name-defined]",
deepseek,data_catalog_8d7fcf.py,success->fail,success,fail,,"data_catalog_8d7fcf.py:213: error: Argument 1 to ""_FrozenDatasets"" has incompatible type ""Optional[_FrozenDatasets]""; expected ""Union[_FrozenDatasets, Dict[str, Any]]"" [arg-type]"
deepseek,diff_65255d.py,fail->success,fail,success,diff_65255d.py:4: error: EOF while scanning triple-quoted string literal [syntax],
deepseek,discovery_c67402.py,success->fail,success,fail,,discovery_c67402.py:35: error: closing parenthesis ')' does not match opening parenthesis '[' on line 33 [syntax]
deepseek,elmo_indexer_111385.py,fail->success,fail,success,elmo_indexer_111385.py:75: error: Invalid type comment or annotation [valid-type],
deepseek,entity_680502.py,success->fail,success,fail,,entity_680502.py:100: error: invalid syntax [syntax]
deepseek,entity_9725b3.py,success->fail,success,fail,,"entity_9725b3.py:54: error: Unsupported left operand type for + (""None"") [operator]"
deepseek,files_a4064b.py,success->fail,success,fail,,"files_a4064b.py:302: error: Argument 1 to ""gen_python_files"" has incompatible type ""Generator[Path, None, None]""; expected ""Sequence[Path]"" [arg-type]"
deepseek,filters_a79ada.py,success->fail,success,fail,,filters_a79ada.py:29: error: closing parenthesis '}' does not match opening parenthesis '(' on line 27 [syntax]
deepseek,formparsers_534d1c.py,fail->success,fail,success,formparsers_534d1c.py:192: error: invalid syntax [syntax],
deepseek,generate_868fef.py,fail->success,fail,success,"generate_868fef.py:157: error: Item ""None"" of ""Optional[List[Any]]"" has no attribute ""__iter__"" (not iterable) [union-attr]",
deepseek,geo_location_650a75.py,fail->success,fail,success,"geo_location_650a75.py:196: error: TypedDict key must be a string literal; expected one of (""external_id"", ""category"", ""publication_date"", ""updated_date"", ""status"") [literal-required]",
deepseek,helpers_062f96.py,fail->success,fail,success,helpers_062f96.py:154: error: invalid syntax [syntax],
deepseek,joinquant_follower_7b86fd.py,success->fail,success,fail,,"joinquant_follower_7b86fd.py:7: error: Library stubs not installed for ""requests"" [import]"
deepseek,light_3c0a4b.py,success->fail,success,fail,,light_3c0a4b.py:77: error: closing parenthesis ']' does not match opening parenthesis '(' [syntax]
deepseek,log_config_fb42e8.py,fail->success,fail,success,"log_config_fb42e8.py:245: error: Incompatible types (expression has type ""dict_keys[str, Dict[str, Any]]"", TypedDict item ""handlers"" has type ""Sequence[str]"") [typeddict-item]",
deepseek,manifest_87d3d1.py,success->fail,success,fail,,manifest_87d3d1.py:470: error: invalid syntax [syntax]
deepseek,media_player_468e90.py,success->fail,success,fail,,media_player_468e90.py:360: error: invalid syntax [syntax]
deepseek,media_player_846062.py,fail->success,fail,success,"media_player_846062.py:115: error: Incompatible types in assignment (expression has type ""None"", variable has type ""str"") [assignment]",
deepseek,media_player_8d1e5c.py,fail->success,fail,success,media_player_8d1e5c.py:29: error: invalid syntax [syntax],
deepseek,messages_bf1e5c.py,fail->success,fail,success,"messages_bf1e5c.py:99: error: Incompatible types in assignment (expression has type ""str"", base class ""Message"" defined the type as ""Tuple[Any, ...]"") [assignment]",
deepseek,meta_learners_cdb80e.py,success->fail,success,fail,,"meta_learners_cdb80e.py:47: error: Name ""Tuple"" is not defined [name-defined]"
deepseek,metastore_cache_b6b4a1.py,success->fail,success,fail,,"metastore_cache_b6b4a1.py:24: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
deepseek,mi_fgsm_09ba33.py,fail->success,fail,success,"mi_fgsm_09ba33.py:32: error: Incompatible types in assignment (expression has type ""float"", variable has type ""T"") [assignment]",
deepseek,misc_23de87.py,fail->success,fail,success,"misc_23de87.py:117: error: Incompatible types in assignment (expression has type ""List[List[<nothing>]]"", target has type ""Tuple[List[float], List[float]]"") [assignment]",
deepseek,module_b33ece.py,fail->success,fail,success,"module_b33ece.py:45: error: ""SubModuleDictMixin"" has no attribute ""is_package"" [attr-defined]",
deepseek,monitoring_service_7fc586.py,fail->success,fail,success,monitoring_service_7fc586.py:171: error: unexpected EOF while parsing [syntax],
deepseek,multitask_data_loader_4fc11f.py,success->fail,success,fail,,"multitask_data_loader_4fc11f.py:91: error: Incompatible types in assignment (expression has type ""Union[int, str, device]"", variable has type ""Optional[device]"") [assignment]"
deepseek,note_76679d.py,success->fail,success,fail,,"note_76679d.py:34: error: ""type"" expects no type arguments, but 1 given [type-arg]"
deepseek,notify_1817bd.py,fail->success,fail,success,"notify_1817bd.py:149: error: Incompatible types in assignment (expression has type ""Optional[str]"", variable has type ""str"") [assignment]",
deepseek,number_c8a6fb.py,success->fail,success,fail,,"number_c8a6fb.py:21: error: Module ""typing"" has no attribute ""NotRequired"" [attr-defined]"
deepseek,openapi_a5fc11.py,success->fail,success,fail,,openapi_a5fc11.py:29: error: closing parenthesis ')' does not match opening parenthesis '{' [syntax]
deepseek,param_cbed36.py,success->fail,success,fail,,"param_cbed36.py:46: error: Item ""Iterator[Any]"" of ""Union[Any, Iterator[Any]]"" has no attribute ""py__class__"" [union-attr]"
deepseek,parser_deb8f1.py,fail->success,fail,success,"parser_deb8f1.py:102: error: ""Tuple[Any, str, Tuple[int, int], str]"" has no attribute ""type"" [attr-defined]",
deepseek,period_85d698.py,fail->success,fail,success,"period_85d698.py:242: error: Incompatible return value type (got ""int"", expected ""PeriodIndex"") [return-value]",
deepseek,pin_fe5cb3.py,success->fail,success,fail,,"pin_fe5cb3.py:154: error: Function ""_forward_callback"" could always be true in boolean context [truthy-function]"
deepseek,pipeline_a41664.py,fail->success,fail,success,"pipeline_a41664.py:116: error: Argument ""directories"" to ""_echo_deletion_warning"" has incompatible type ""List[Path]""; expected ""Dict[str, List[Path]]"" [arg-type]",
deepseek,postgres_09c46c.py,success->fail,success,fail,,"postgres_09c46c.py:205: error: ""str"" has no attribute ""items"" [attr-defined]"
deepseek,presence_ce7e57.py,fail->success,fail,success,"presence_ce7e57.py:22: error: Incompatible types in assignment (expression has type ""Callable[[datetime, datetime], Dict[str, Dict[str, Any]]]"", variable has type ""Callable[[datetime, datetime], Dict[str, int]]"") [assignment]",
deepseek,pretrained_transformer_tokenizer_f82621.py,success->fail,success,fail,,pretrained_transformer_tokenizer_f82621.py:169: error: invalid syntax [syntax]
deepseek,profile_77bd4f.py,fail->success,fail,success,profile_77bd4f.py:137: error: invalid syntax [syntax],
deepseek,python_lint_handler_d8f325.py,fail->success,fail,success,"python_lint_handler_d8f325.py:117: error: Incompatible types in assignment (expression has type ""Optional[Any]"", variable has type ""str"") [assignment]",
deepseek,querysets_ea35a5.py,success->fail,success,fail,,"querysets_ea35a5.py:85: error: Item ""FunctionContext"" of ""Union[FunctionContext, MethodContext]"" has no attribute ""type"" [union-attr]"
deepseek,random_033806.py,success->fail,success,fail,,random_033806.py:20: error: invalid syntax [syntax]
deepseek,random_value_d2191f.py,fail->success,fail,success,"D:\python3.8\lib\site-packages\mypy\typeshed\stdlib\builtins.pyi:89: note: ""object"" defined here",
deepseek,realm_settings_e9d618.py,success->fail,success,fail,,realm_settings_e9d618.py:244: error: invalid syntax [syntax]
deepseek,request_4f1f32.py,fail->success,fail,success,"request_4f1f32.py:51: error: Argument ""fields"" to ""request_encode_body"" of ""RequestMethods"" has incompatible type ""Union[Dict[str, str], List[Tuple[str, str]], Tuple[Tuple[str, str], ...], None]""; expected ""Union[Dict[str, Union[str, Tuple[str, ...]]], List[Tuple[str, Union[str, Tuple[str, ...]]]], Tuple[Tuple[str, Union[str, Tuple[str, ...]]], ...], None]"" [arg-type]",
deepseek,resources_83f462.py,fail->success,fail,success,resources_83f462.py:100: error: invalid syntax [syntax],
deepseek,schema_ee7352.py,success->fail,success,fail,,schema_ee7352.py:94: error: invalid syntax [syntax]
deepseek,schemas_911003.py,fail->success,fail,success,schemas_911003.py:223: error: unexpected EOF while parsing [syntax],
deepseek,schemas_d6d78d.py,fail->success,fail,success,schemas_d6d78d.py:67: error: invalid syntax [syntax],
deepseek,secret_registry_13acaf.py,success->fail,success,fail,,secret_registry_13acaf.py:112: error: invalid syntax [syntax]
deepseek,sensor_2394c2.py,success->fail,success,fail,,sensor_2394c2.py:203: error: invalid syntax [syntax]
deepseek,sensor_48e774.py,fail->success,fail,success,"sensor_48e774.py:192: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]",
deepseek,sensor_51937f.py,fail->success,fail,success,"sensor_51937f.py:164: error: Incompatible types in assignment (expression has type ""Optional[str]"", variable has type ""str"") [assignment]",
deepseek,sensor_687ec5.py,success->fail,success,fail,,"sensor_687ec5.py:69: error: TypedDict key must be a string literal; expected one of (""data_group"", ""element"", ""icon"", ""invert"") [literal-required]"
deepseek,sensor_7d888f.py,fail->success,fail,success,sensor_7d888f.py:98: error: invalid syntax [syntax],
deepseek,sensor_875fbc.py,success->fail,success,fail,,"sensor_875fbc.py:124: error: TypedDict ""DepartureType"" has no key ""departures"" [typeddict-unknown-key]"
deepseek,sensor_b3b9e2.py,success->fail,success,fail,,sensor_b3b9e2.py:55: error: illegal target for annotation [syntax]
deepseek,sensor_c9d852.py,fail->success,fail,success,sensor_c9d852.py:148: error: invalid syntax [syntax],
deepseek,serializers_307391.py,success->fail,success,fail,,"serializers_307391.py:38: error: Name ""Type"" is not defined [name-defined]"
deepseek,shard_block_395422.py,success->fail,success,fail,,shard_block_395422.py:18: error: Type cannot be declared in assignment to non-self attribute [misc]
deepseek,single_id_token_indexer_c980de.py,fail->success,fail,success,"single_id_token_indexer_c980de.py:44: error: Argument 1 to ""append"" of ""list"" has incompatible type ""str""; expected ""int"" [arg-type]",
deepseek,sparse_a2c123.py,success->fail,success,fail,,"sparse_a2c123.py:32: error: Incompatible types in assignment (expression has type ""Tuple[List[float], List[Any], List[Any]]"", variable has type ""List[Any]"") [assignment]"
deepseek,splitters_9b6f18.py,fail->success,fail,success,splitters_9b6f18.py:343: error: invalid syntax [syntax],
deepseek,sql_parse_tests_ebc947.py,fail->success,fail,success,sql_parse_tests_ebc947.py:219: error: EOF while scanning triple-quoted string literal [syntax],
deepseek,stack_621148.py,fail->success,fail,success,"stack_621148.py:119: error: Item ""None"" of ""Optional[Any]"" has no attribute ""split"" [union-attr]",
deepseek,startup_7ab634.py,fail->success,fail,success,startup_7ab634.py:178: error: unexpected EOF while parsing [syntax],
deepseek,staticfiles_164434.py,success->fail,success,fail,,staticfiles_164434.py:47: error: closing parenthesis ')' does not match opening parenthesis '[' on line 46 [syntax]
deepseek,stream_subscription_0a3612.py,fail->success,fail,success,"D:\python3.8\lib\site-packages\mypy\typeshed\stdlib\builtins.pyi:89: note: ""SubInfo"" defined here",
deepseek,streams_a2a52b.py,success->fail,success,fail,,"streams_a2a52b.py:181: error: Name ""Iterator"" is not defined [name-defined]"
deepseek,strings_8fc975.py,success->fail,success,fail,,"strings_8fc975.py:381: error: Name ""DataFrame"" is not defined [name-defined]"
deepseek,swagger_c55f37.py,success->fail,success,fail,,"swagger_c55f37.py:65: error: Item ""None"" of ""Optional[Any]"" has no attribute ""items"" [union-attr]"
deepseek,switch_67758e.py,success->fail,success,fail,,"switch_67758e.py:118: error: Bracketed expression ""[...]"" is not valid as a type [valid-type]"
deepseek,sync_committee_b34f1b.py,fail->success,fail,success,sync_committee_b34f1b.py:79: error: invalid syntax [syntax],
deepseek,tcpclient_test_1d9a53.py,success->fail,success,fail,,tcpclient_test_1d9a53.py:364: error: unexpected EOF while parsing [syntax]
deepseek,test_align_09e7a1.py,fail->success,fail,success,test_align_09e7a1.py:9: error: closing parenthesis ')' does not match opening parenthesis '[' [syntax],
deepseek,test_backup_restore_171613.py,fail->success,fail,success,"test_backup_restore_171613.py:160: error: Incompatible return value type (got ""object"", expected ""bool"") [return-value]",
deepseek,test_base_fc0d64.py,success->fail,success,fail,,test_base_fc0d64.py:315: error: invalid syntax [syntax]
deepseek,test_callables_9ff673.py,success->fail,success,fail,,test_callables_9ff673.py:228: error: invalid syntax [syntax]
deepseek,test_cat_c39959.py,success->fail,success,fail,,"test_cat_c39959.py:21: error: ""List[str]"" not callable [operator]"
deepseek,test_categorical_e04b8e.py,success->fail,success,fail,,"test_categorical_e04b8e.py:109: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
deepseek,test_channel_622ed8.py,fail->success,fail,success,test_channel_622ed8.py:219: error: unexpected EOF while parsing [syntax],
deepseek,test_clip_1e0363.py,fail->success,fail,success,"test_clip_1e0363.py:58: error: Item ""None"" of ""Optional[Any]"" has no attribute ""loc"" [union-attr]",
deepseek,test_collections_4d5e21.py,success->fail,success,fail,,test_collections_4d5e21.py:14: error: invalid syntax [syntax]
deepseek,test_constructors_111932.py,success->fail,success,fail,,"test_constructors_111932.py:28: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
deepseek,test_constructors_c6bb5c.py,success->fail,success,fail,,test_constructors_c6bb5c.py:284: error: EOL while scanning string literal [syntax]
deepseek,test_cut_a5ac0a.py,success->fail,success,fail,,test_cut_a5ac0a.py:388: error: unexpected EOF while parsing [syntax]
deepseek,test_dtypes_c6ad71.py,success->fail,success,fail,,test_dtypes_c6ad71.py:379: error: invalid syntax [syntax]
deepseek,test_hashtable_89c8a4.py,fail->success,fail,success,test_hashtable_89c8a4.py:373: error: unexpected EOF while parsing [syntax],
deepseek,test_hist_box_by_07b6c3.py,fail->success,fail,success,"test_hist_box_by_07b6c3.py:96: error: Name ""result_xticklabels"" is not defined [name-defined]",
deepseek,test_img_util_826a0b.py,fail->success,fail,success,"test_img_util_826a0b.py:61: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]",
deepseek,test_include_router_defaults_overrides_afc221.py,fail->success,fail,success,"test_include_router_defaults_overrides_afc221.py:35: error: Name ""Response"" is not defined [name-defined]",
deepseek,test_incremental_on_schema_change_ffcc97.py,fail->success,fail,success,"test_incremental_on_schema_change_ffcc97.py:30: error: Name ""Any"" is not defined [name-defined]",
deepseek,test_index_503dc5.py,success->fail,success,fail,,"test_index_503dc5.py:36: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
deepseek,test_index_new_74deaa.py,fail->success,fail,success,"test_index_new_74deaa.py:44: error: Too many arguments for ""Iterable"" [call-arg]",
deepseek,test_inference_f5d827.py,success->fail,success,fail,,test_inference_f5d827.py:183: error: unexpected EOF while parsing [syntax]
deepseek,test_init_f7cb07.py,fail->success,fail,success,test_init_f7cb07.py:464: error: unexpected EOF while parsing [syntax],
deepseek,test_kraken_f9036a.py,success->fail,success,fail,,test_kraken_f9036a.py:17: error: Type cannot be declared in assignment to non-self attribute [misc]
deepseek,test_media_player_579798.py,fail->success,fail,success,test_media_player_579798.py:413: error: unexpected EOF while parsing [syntax],
deepseek,test_microbatch_124d73.py,fail->success,fail,success,test_microbatch_124d73.py:157: error: EOL while scanning string literal [syntax],
deepseek,test_nodes_c6ed78.py,success->fail,success,fail,,test_nodes_c6ed78.py:93: error: closing parenthesis ']' does not match opening parenthesis '(' [syntax]
deepseek,test_numba_246dfa.py,fail->success,fail,success,test_numba_246dfa.py:223: error: unexpected EOF while parsing [syntax],
deepseek,test_on_attestation_3db217.py,success->fail,success,fail,,"test_on_attestation_3db217.py:19: error: ""SpecObject"" has no attribute ""on_attestation"" [attr-defined]"
deepseek,test_pipeline_0fd84d.py,fail->success,fail,success,"test_pipeline_0fd84d.py:102: error: Need type annotation for ""template"" (hint: ""template: Dict[<type>, <type>] = ..."") [var-annotated]",
deepseek,test_project_1f989e.py,fail->success,fail,success,"test_project_1f989e.py:8: error: Name ""pytest_mock"" is not defined [name-defined]",
deepseek,test_prometheus_2a91bc.py,success->fail,success,fail,,"test_prometheus_2a91bc.py:59: error: Name ""pytest.MonkeyPatch"" is not defined [name-defined]"
deepseek,test_pythonapi_d455c1.py,success->fail,success,fail,,"test_pythonapi_d455c1.py:213: error: Name ""make"" is not defined [name-defined]"
deepseek,test_raidenservice_d5e26d.py,fail->success,fail,success,"test_raidenservice_d5e26d.py:81: error: Name ""Type"" is not defined [name-defined]",
deepseek,test_range_fc6fe9.py,fail->success,fail,success,test_range_fc6fe9.py:369: error: invalid syntax [syntax],
deepseek,test_recovery_2d8e5e.py,fail->success,fail,success,"test_recovery_2d8e5e.py:172: error: ""Counter"" is not subscriptable, use ""typing.Counter"" instead [misc]",
deepseek,test_replace_ac1a27.py,fail->success,fail,success,test_replace_ac1a27.py:15: error: invalid syntax [syntax],
deepseek,test_round_0a4ab4.py,success->fail,success,fail,,test_round_0a4ab4.py:66: error: Invalid type comment or annotation [valid-type]
deepseek,test_samplers_341888.py,success->fail,success,fail,,"test_samplers_341888.py:12: error: Name ""LOGS"" is not defined [name-defined]"
deepseek,test_sequential_runner_021190.py,fail->success,fail,success,"test_sequential_runner_021190.py:27: error: Name ""pytest.LogCaptureFixture"" is not defined [name-defined]",
deepseek,test_series_5f79c1.py,success->fail,success,fail,,test_series_5f79c1.py:299: error: EOL while scanning string literal [syntax]
deepseek,test_setops_dfaf2d.py,fail->success,fail,success,test_setops_dfaf2d.py:227: error: invalid syntax [syntax],
deepseek,test_settlement_0a3fe7.py,success->fail,success,fail,,test_settlement_0a3fe7.py:212: error: EOF while scanning triple-quoted string literal [syntax]
deepseek,test_sliceaware_classifier_1e31e5.py,success->fail,success,fail,,"test_sliceaware_classifier_1e31e5.py:76: error: ""Dataset[Any]"" has no attribute ""Y_dict"" [attr-defined]"
deepseek,test_stack_b5f4bd.py,success->fail,success,fail,,test_stack_b5f4bd.py:57: error: Too few arguments [call-arg]
deepseek,test_stat_reductions_69f5b2.py,success->fail,success,fail,,"test_stat_reductions_69f5b2.py:66: error: Unexpected keyword argument ""copy"" [call-arg]"
deepseek,test_stoploss_on_exchange_98cce5.py,fail->success,fail,success,test_stoploss_on_exchange_98cce5.py:226: error: invalid syntax [syntax],
deepseek,test_targetstate_85ad01.py,fail->success,fail,success,test_targetstate_85ad01.py:398: error: unexpected EOF while parsing [syntax],
deepseek,test_to_csv_c73ed7.py,success->fail,success,fail,,"test_to_csv_c73ed7.py:73: error: Argument 1 to ""read_csv"" of ""TestSeriesToCSV"" has incompatible type ""StringIO""; expected ""str"" [arg-type]"
deepseek,test_tone_convert_a42800.py,fail->success,fail,success,test_tone_convert_a42800.py:172: error: EOL while scanning string literal [syntax],
deepseek,test_transform_0bcea9.py,success->fail,success,fail,,"test_transform_0bcea9.py:32: error: List item 0 has incompatible type ""str""; expected ""int"" [list-item]"
deepseek,test_url_1ceabd.py,success->fail,success,fail,,"test_url_1ceabd.py:63: error: ""str"" has no attribute ""raw_path"" [attr-defined]"
deepseek,test_validator_417f9a.py,fail->success,fail,success,test_validator_417f9a.py:111: error: invalid syntax [syntax],
deepseek,test_wallets_fe5a94.py,success->fail,success,fail,,test_wallets_fe5a94.py:171: error: EOL while scanning string literal [syntax]
deepseek,test_webserver_68a1ed.py,fail->success,fail,success,"test_webserver_68a1ed.py:36: error: The return type of a generator function should be ""Generator"" or one of its supertypes [misc]",
deepseek,timedeltas_44fa81.py,fail->success,fail,success,"timedeltas_44fa81.py:68: error: Name ""np"" is not defined [name-defined]",
deepseek,timerange_d18ed2.py,fail->success,fail,success,"timerange_d18ed2.py:126: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]",
deepseek,token_network_registry_0d90a4.py,success->fail,success,fail,,"token_network_registry_0d90a4.py:46: error: Name ""typecheck"" is not defined [name-defined]"
deepseek,trainer_test_f0df2a.py,fail->success,fail,success,trainer_test_f0df2a.py:400: error: unexpected EOF while parsing [syntax],
deepseek,transactions_739961.py,success->fail,success,fail,,transactions_739961.py:69: error: closing parenthesis ')' does not match opening parenthesis '[' [syntax]
deepseek,transformer_layer_bf9c8e.py,success->fail,success,fail,,"transformer_layer_bf9c8e.py:106: error: Too many arguments for ""TransformerLayerOutput"" [call-arg]"
deepseek,transport_58bb8a.py,success->fail,success,fail,,transport_58bb8a.py:330: error: unexpected EOF while parsing [syntax]
deepseek,unit_system_a3b7c4.py,fail->success,fail,success,unit_system_a3b7c4.py:84: error: invalid syntax [syntax],
deepseek,unit_tests_627911.py,success->fail,success,fail,,unit_tests_627911.py:316: error: unexpected EOF while parsing [syntax]
deepseek,user_groups_977a0b.py,fail->success,fail,success,user_groups_977a0b.py:41: error: invalid syntax [syntax],
deepseek,util_e9973a.py,success->fail,success,fail,,util_e9973a.py:296: error: unexpected EOF while parsing [syntax]
deepseek,utils_3f6c97.py,fail->success,fail,success,"utils_3f6c97.py:73: error: ""SendSecretRequestInNode"" has no attribute ""node"" [attr-defined]",
deepseek,utils_b0aeeb.py,fail->success,fail,success,utils_b0aeeb.py:273: error: unexpected EOF while parsing [syntax],
deepseek,utils_f7b84e.py,fail->success,fail,success,"utils_f7b84e.py:191: error: Variable ""utils_f7b84e.X"" is not valid as a type [valid-type]",
deepseek,web_rtc_831f2f.py,fail->success,fail,success,web_rtc_831f2f.py:378: error: invalid syntax [syntax],
deepseek,websocket_api_e94b97.py,success->fail,success,fail,,websocket_api_e94b97.py:62: error: closing parenthesis ')' does not match opening parenthesis '[' [syntax]
deepseek,withdrawals_7e4651.py,success->fail,success,fail,,"withdrawals_7e4651.py:106: error: Item ""None"" of ""Optional[List[int]]"" has no attribute ""__iter__"" (not iterable) [union-attr]"
deepseek,withdrawals_8c07d5.py,fail->success,fail,success,"withdrawals_8c07d5.py:12: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]",
claude3_sonnet,0531_convert_most_ids_to_bigints_841260.py,success->fail,success,fail,,"0531_convert_most_ids_to_bigints_841260.py:18: error: Method ""state_forwards"" is marked as an override, but no base method was found with this name [misc]"
claude3_sonnet,__init___49b7e6.py,success->fail,success,fail,,"__init___49b7e6.py:24: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
claude3_sonnet,__init___54e0bc.py,success->fail,success,fail,,"__init___54e0bc.py:15: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
claude3_sonnet,__init___7dd003.py,success->fail,success,fail,,"__init___7dd003.py:130: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
claude3_sonnet,__init___97fa7b.py,success->fail,success,fail,,"__init___97fa7b.py:29: error: ""set"" is not subscriptable, use ""typing.Set"" instead [misc]"
claude3_sonnet,__init___ade613.py,success->fail,success,fail,,"__init___ade613.py:12: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
claude3_sonnet,__init___b92714.py,fail->success,fail,success,"__init___b92714.py:118: error: Incompatible types in assignment (expression has type ""MultiDictProxy[str | bytes | FileField]"", variable has type ""dict[str, Any]"") [assignment]",
claude3_sonnet,__init___d2d86c.py,success->fail,success,fail,,__init___d2d86c.py:313: error: Cast target is not a type [misc]
claude3_sonnet,_doctools_2a0387.py,fail->success,fail,success,"_doctools_2a0387.py:149: error: Argument ""labels"" to ""plot"" of ""TablePlotter"" has incompatible type ""list[str]""; expected ""tuple[str, ...]"" [arg-type]",
claude3_sonnet,_openpyxl_60b4ed.py,success->fail,success,fail,,"_openpyxl_60b4ed.py:463: error: Unsupported left operand type for | (""Dict[str, bool]"") [operator]"
claude3_sonnet,_types_6d212e.py,fail->success,fail,success,"_types_6d212e.py:105: error: Incompatible types in assignment (expression has type ""Callable[..., Any]"", variable has type ""_Wrapped[[VarArg(Any), KwArg(Any)], Any, [VarArg(Any), KwArg(Any)], Any]"") [assignment]",
claude3_sonnet,activity_5ae188.py,success->fail,success,fail,,"activity_5ae188.py:61: error: No overload variant of ""zip"" matches argument types ""Generator[Any, None, None]"", ""Any"", ""bool"" [call-overload]"
claude3_sonnet,alert_tests_e8cf0b.py,success->fail,success,fail,,"alert_tests_e8cf0b.py:52: error: ""object"" has no attribute ""__enter__"" [attr-defined]"
claude3_sonnet,base_c73d2b.py,fail->success,fail,success,"base_c73d2b.py:156: error: The return type of a generator function should be ""Generator"" or one of its supertypes [misc]",
claude3_sonnet,base_tests_a1e90e.py,success->fail,success,fail,,"base_tests_a1e90e.py:83: error: ""Type[T]"" has no attribute ""id"" [attr-defined]"
claude3_sonnet,bias_direction_wrappers_2ab1fb.py,fail->success,fail,success,"bias_direction_wrappers_2ab1fb.py:30: error: Item ""None"" of ""Any | None"" has no attribute ""requires_grad"" [union-attr]",
claude3_sonnet,bias_mitigator_applicator_311808.py,success->fail,success,fail,,"bias_mitigator_applicator_311808.py:64: error: Name ""torch"" is not defined [name-defined]"
claude3_sonnet,bias_mitigators_adad59.py,fail->success,fail,success,"bias_mitigators_adad59.py:266: error: Incompatible types in assignment (expression has type ""ndarray[Any, Any]"", variable has type ""Tensor"") [assignment]",
claude3_sonnet,binary_sensor_950ee8.py,success->fail,success,fail,,"binary_sensor_950ee8.py:108: error: Item ""None"" of ""Optional[str]"" has no attribute ""startswith"" [union-attr]"
claude3_sonnet,boxplot_f690b9.py,fail->success,fail,success,"boxplot_f690b9.py:63: error: Incompatible types in assignment (expression has type overloaded function, variable has type ""Callable[[Any], float]"") [assignment]",
claude3_sonnet,cache_053dd3.py,fail->success,fail,success,"cache_053dd3.py:138: error: ""_Wrapped[[VarArg(Any), KwArg(Any)], Any, [VarArg(Any), KwArg(Any)], Response]"" has no attribute ""make_cache_key"" [attr-defined]",
claude3_sonnet,cache_helpers_e012c1.py,success->fail,success,fail,,"cache_helpers_e012c1.py:76: error: Need type annotation for ""obj"" [var-annotated]"
claude3_sonnet,calendar_819d29.py,success->fail,success,fail,,"calendar_819d29.py:131: error: Argument 1 to ""strftime"" of ""date"" has incompatible type ""Optional[datetime]""; expected ""date"" [arg-type]"
claude3_sonnet,call_824067.py,success->fail,success,fail,,"call_824067.py:70: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
claude3_sonnet,camera_b201a1.py,success->fail,success,fail,,"camera_b201a1.py:28: error: Function ""builtins.any"" is not valid as a type [valid-type]"
claude3_sonnet,cli_d3e92b.py,success->fail,success,fail,,"cli_d3e92b.py:109: error: Argument 1 to ""open"" has incompatible type ""Optional[str]""; expected ""Union[int, Union[str, bytes, PathLike[str], PathLike[bytes]]]"" [arg-type]"
claude3_sonnet,common_1f9133.py,success->fail,success,fail,,"common_1f9133.py:14: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
claude3_sonnet,conftest_0f5d02.py,success->fail,success,fail,,"conftest_0f5d02.py:12: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
claude3_sonnet,conftest_4ecb9c.py,success->fail,success,fail,,"conftest_4ecb9c.py:10: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
claude3_sonnet,conftest_51ed26.py,success->fail,success,fail,,"conftest_51ed26.py:55: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
claude3_sonnet,conftest_bb7cf9.py,success->fail,success,fail,,"conftest_bb7cf9.py:24: error: Name ""pytest.MonkeyPatch"" is not defined [name-defined]"
claude3_sonnet,conftest_bc6db5.py,success->fail,success,fail,,"conftest_bc6db5.py:22: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
claude3_sonnet,core_06cca6.py,fail->success,fail,success,"core_06cca6.py:152: error: Argument 1 to ""ApplierMetadata"" has incompatible type ""defaultdict[str, int]""; expected ""Counter[str]"" [arg-type]",
claude3_sonnet,core_6bd602.py,fail->success,fail,success,"core_6bd602.py:232: error: No overload variant of ""min"" matches argument types ""float"", ""floating[Any]"" [call-overload]",
claude3_sonnet,data_collator_b6829a.py,success->fail,success,fail,,"data_collator_b6829a.py:51: error: ""tuple"" is not subscriptable, use ""typing.Tuple"" instead [misc]"
claude3_sonnet,decimalspace_eba8c8.py,fail->success,fail,success,"decimalspace_eba8c8.py:9: error: Incompatible default for argument ""dtype"" (default has type ""type[signedinteger[_64Bit]]"", argument has type ""dtype[Any]"") [assignment]",
claude3_sonnet,device_e3bccf.py,success->fail,success,fail,,"device_e3bccf.py:145: error: Incompatible return value type (got ""Optional[str]"", expected ""str"") [return-value]"
claude3_sonnet,drill_3ecdbc.py,fail->success,fail,success,"drill_3ecdbc.py:48: error: Argument 1 to ""unquote"" has incompatible type ""str | None""; expected ""str | bytes"" [arg-type]",
claude3_sonnet,ecs_3fb000.py,fail->success,fail,success,"ecs_3fb000.py:610: error: List item 1 has incompatible type ""Panel""; expected ""str"" [list-item]",
claude3_sonnet,email_mirror_590460.py,success->fail,success,fail,,"email_mirror_590460.py:202: error: Argument 3 to ""sub"" has incompatible type ""Optional[str]""; expected ""str"" [arg-type]"
claude3_sonnet,execution_855aa0.py,success->fail,success,fail,,"execution_855aa0.py:69: error: ""deque"" is not subscriptable, use ""typing.Deque"" instead [misc]"
claude3_sonnet,exposed_entities_a550ba.py,success->fail,success,fail,,"exposed_entities_a550ba.py:221: error: Unsupported left operand type for | (""Dict[str, Any]"") [operator]"
claude3_sonnet,extension_runtime_6679fc.py,success->fail,success,fail,,"extension_runtime_6679fc.py:47: error: Module has no attribute ""SIGKILL""; maybe ""SIGILL""? [attr-defined]"
claude3_sonnet,featureflags_544034.py,success->fail,success,fail,,"featureflags_544034.py:33: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
claude3_sonnet,fixtures_82d048.py,success->fail,success,fail,,"fixtures_82d048.py:3: error: Module ""typing"" has no attribute ""Random"" [attr-defined]"
claude3_sonnet,forms_6e49d8.py,success->fail,success,fail,,"forms_6e49d8.py:207: error: Method ""save"" is marked as an override, but no base method was found with this name [misc]"
claude3_sonnet,freshness_735399.py,success->fail,success,fail,,"freshness_735399.py:78: error: Value of type ""Optional[Dict[str, Any]]"" is not indexable [index]"
claude3_sonnet,gen_49c34e.py,success->fail,success,fail,,"gen_49c34e.py:24: error: Need type annotation for ""dct"" [var-annotated]"
claude3_sonnet,generate_868fef.py,success->fail,success,fail,,"generate_868fef.py:180: error: Argument 2 to ""_get_nodes_from_ids"" of ""GenerateTask"" has incompatible type ""Optional[Set[str]]""; expected ""Set[str]"" [arg-type]"
claude3_sonnet,header_990b83.py,success->fail,success,fail,,header_990b83.py:142: error: Missing return statement [return]
claude3_sonnet,helpers_062f96.py,success->fail,success,fail,,"helpers_062f96.py:67: error: Function ""entities_filter"" could always be true in boolean context [truthy-function]"
claude3_sonnet,helpers_b607a0.py,success->fail,success,fail,,"helpers_b607a0.py:51: error: No overload variant of ""zip"" matches argument types ""Tuple[Any, ...]"", ""Tuple[Any, ...]"", ""bool"" [call-overload]"
claude3_sonnet,home_349a7c.py,success->fail,success,fail,,"home_349a7c.py:78: error: ""tuple"" is not subscriptable, use ""typing.Tuple"" instead [misc]"
claude3_sonnet,humidifier_e2948a.py,success->fail,success,fail,,"humidifier_e2948a.py:72: error: Incompatible return value type (got ""Optional[int]"", expected ""Optional[str]"") [return-value]"
claude3_sonnet,hyperopt_optimizer_f9e1bd.py,success->fail,success,fail,,"hyperopt_optimizer_f9e1bd.py:99: error: No overload variant of ""zip"" matches argument types ""List[Any]"", ""List[Any]"", ""bool"" [call-overload]"
claude3_sonnet,image_91d679.py,fail->success,fail,success,"image_91d679.py:114: error: Incompatible types in assignment (expression has type ""tuple[Any | BaseException, Any | BaseException]"", variable has type ""list[Any]"") [assignment]",
claude3_sonnet,indexing_engines_bfb33a.py,fail->success,fail,success,"indexing_engines_bfb33a.py:20: error: List item 0 has incompatible type ""tuple[str, type[signedinteger[_64Bit]]]""; expected ""tuple[str, dtype[Any]]"" [list-item]",
claude3_sonnet,input_reduction_cfaaeb.py,fail->success,fail,success,"input_reduction_cfaaeb.py:136: error: Argument 1 to ""append"" of ""list"" has incompatible type ""tuple[Any, signedinteger[Any], list[int] | None]""; expected ""tuple[Any, int, list[int] | None]"" [arg-type]",
claude3_sonnet,internet_b02113.py,success->fail,success,fail,,"internet_b02113.py:244: error: Need type annotation for ""words"" (hint: ""words: Set[<type>] = ..."") [var-annotated]"
claude3_sonnet,kedro_data_catalog_148318.py,success->fail,success,fail,,"kedro_data_catalog_148318.py:113: error: Unsupported left operand type for | (""Dict[str, _LazyDataset]"") [operator]"
claude3_sonnet,kill_if_no_output_54c848.py,success->fail,success,fail,,"kill_if_no_output_54c848.py:10: error: Module has no attribute ""fcntl"" [attr-defined]"
claude3_sonnet,light_ae238e.py,success->fail,success,fail,,"light_ae238e.py:43: error: Argument 1 to ""write"" of ""TextIOBase"" has incompatible type ""Optional[str]""; expected ""str"" [arg-type]"
claude3_sonnet,local_b588b6.py,success->fail,success,fail,,"local_b588b6.py:63: error: Method ""get_public_upload_root_url"" is marked as an override, but no base method was found with this name [misc]"
claude3_sonnet,logger_f99b27.py,success->fail,success,fail,,"logger_f99b27.py:46: error: ""MetaLog"" has no attribute ""write"" [attr-defined]"
claude3_sonnet,makemessages_b575f4.py,success->fail,success,fail,,"makemessages_b575f4.py:67: error: Method ""add_arguments"" is marked as an override, but no base method was found with this name [misc]"
claude3_sonnet,media_player_6853b0.py,success->fail,success,fail,,media_player_6853b0.py:20: error: X | Y syntax for unions requires Python 3.10 [syntax]
claude3_sonnet,media_source_5cb2e6.py,success->fail,success,fail,,"media_source_5cb2e6.py:60: error: ""dict"" is not subscriptable [misc]"
claude3_sonnet,monitor_7b218d.py,success->fail,success,fail,,"monitor_7b218d.py:206: error: Incompatible return value type (got ""Dict[str, Dict[int, int]]"", expected ""MutableMapping[str, MutableMapping[int, int]]"") [return-value]"
claude3_sonnet,numeric_40361d.py,success->fail,success,fail,,"numeric_40361d.py:15: error: ""defaultdict"" is not subscriptable, use ""typing.DefaultDict"" instead [misc]"
claude3_sonnet,openapi_a5fc11.py,success->fail,success,fail,,"openapi_a5fc11.py:120: error: Value of type variable ""AnyStr"" of ""urljoin"" cannot be ""Optional[str]"" [type-var]"
claude3_sonnet,ops_698940.py,fail->success,fail,success,"ops_698940.py:202: error: Invalid index type ""Callable[[Any], Any]"" for ""dict[_UFunc_Nin1_Nout1[str, int, None], str]""; expected type ""_UFunc_Nin1_Nout1[str, int, None]"" [index]",
claude3_sonnet,prometheus_180961.py,success->fail,success,fail,,"prometheus_180961.py:98: error: Incompatible default for argument ""state"" (default has type ""None"", argument has type ""Dict[str, Any]"") [assignment]"
claude3_sonnet,raiden_network_f4d23c.py,success->fail,success,fail,,"raiden_network_f4d23c.py:162: error: Name ""pytest.MonkeyPatch"" is not defined [name-defined]"
claude3_sonnet,raiden_service_70320b.py,success->fail,success,fail,,"raiden_service_70320b.py:231: error: Argument 1 to ""join"" has incompatible type ""Optional[str]""; expected ""str"" [arg-type]"
claude3_sonnet,realm_settings_e9d618.py,success->fail,success,fail,,"realm_settings_e9d618.py:96: error: ""tuple"" is not subscriptable, use ""typing.Tuple"" instead [misc]"
claude3_sonnet,response_0a5943.py,success->fail,success,fail,,"response_0a5943.py:44: error: Method ""__iter__"" is marked as an override, but no base method was found with this name [misc]"
claude3_sonnet,rest_51609c.py,success->fail,success,fail,,"rest_51609c.py:76: error: Too many values to unpack (2 expected, 3 provided) [misc]"
claude3_sonnet,retention_81eb85.py,success->fail,success,fail,,"retention_81eb85.py:28: error: ""set"" is not subscriptable, use ""typing.Set"" instead [misc]"
claude3_sonnet,s3_e58a82.py,success->fail,success,fail,,"s3_e58a82.py:135: error: Method ""get_public_upload_root_url"" is marked as an override, but no base method was found with this name [misc]"
claude3_sonnet,send_custom_email_c1af50.py,success->fail,success,fail,,"send_custom_email_c1af50.py:19: error: Method ""add_arguments"" is marked as an override, but no base method was found with this name [misc]"
claude3_sonnet,send_to_email_mirror_634f31.py,success->fail,success,fail,,"send_to_email_mirror_634f31.py:23: error: Method ""add_arguments"" is marked as an override, but no base method was found with this name [misc]"
claude3_sonnet,sensor_82981a.py,fail->success,fail,success,"sensor_82981a.py:159: error: Unsupported operand types for in (""Any | None"" and ""str"") [operator]",
claude3_sonnet,sensor_d95271.py,fail->success,fail,success,"sensor_d95271.py:102: error: Need type annotation for ""new_entities"" (hint: ""new_entities: list[<type>] = ..."") [var-annotated]",
claude3_sonnet,sequences_74f8b6.py,fail->success,fail,success,"sequences_74f8b6.py:111: error: Need type annotation for ""fulllist"" [var-annotated]",
claude3_sonnet,server_057ee6.py,fail->success,fail,success,"server_057ee6.py:348: error: Module has no attribute ""CREATE_NEW_PROCESS_GROUP"" [attr-defined]",
claude3_sonnet,starrocks_a24cf8.py,fail->success,fail,success,"starrocks_a24cf8.py:55: error: Signature of ""python_type"" incompatible with supertype ""TypeEngine"" [override]",
claude3_sonnet,string__8c20b1.py,fail->success,fail,success,"string__8c20b1.py:468: error: Incompatible types in assignment (expression has type ""ndarray[Any, dtype[Any]]"", variable has type ""Sequence[Any]"") [assignment]",
claude3_sonnet,sum__a10910.py,fail->success,fail,success,"sum__a10910.py:83: error: Incompatible types in assignment (expression has type ""float"", variable has type ""int"") [assignment]",
claude3_sonnet,swagger_c55f37.py,fail->success,fail,success,"swagger_c55f37.py:117: error: Value of type variable ""AnyStr"" of ""urljoin"" cannot be ""str | None"" [type-var]",
claude3_sonnet,switch_813f86.py,success->fail,success,fail,,"switch_813f86.py:80: error: Unsupported left operand type for | (""Dict[str, Any]"") [operator]"
claude3_sonnet,switch_a354e7.py,success->fail,success,fail,,"switch_a354e7.py:25: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
claude3_sonnet,template_parser_ecf506.py,success->fail,success,fail,,"template_parser_ecf506.py:172: error: ""str"" has no attribute ""removeprefix"" [attr-defined]"
claude3_sonnet,test_arithmetics_2d6e2b.py,success->fail,success,fail,,"test_arithmetics_2d6e2b.py:12: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
claude3_sonnet,test_backup_restore_171613.py,success->fail,success,fail,,"test_backup_restore_171613.py:82: error: Incompatible return value type (got ""Union[Path, bool]"", expected ""bool"") [return-value]"
claude3_sonnet,test_base_397a75.py,success->fail,success,fail,,"test_base_397a75.py:94: error: Module has no attribute ""app"" [attr-defined]"
claude3_sonnet,test_callables_9ff673.py,success->fail,success,fail,,"test_callables_9ff673.py:464: error: ""int"" has no attribute ""model_dump_for_openapi"" [attr-defined]"
claude3_sonnet,test_category_67f90a.py,fail->success,fail,success,"test_category_67f90a.py:193: error: Invalid index type ""dtype[Any]"" for ""dict[type[object], int]""; expected type ""type[object]"" [index]",
claude3_sonnet,test_commands_1034dd.py,success->fail,success,fail,,"test_commands_1034dd.py:18: error: ""set"" is not subscriptable, use ""typing.Set"" instead [misc]"
claude3_sonnet,test_compression_21f3e4.py,success->fail,success,fail,,"test_compression_21f3e4.py:16: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
claude3_sonnet,test_construction_01d413.py,success->fail,success,fail,,"test_construction_01d413.py:11: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
claude3_sonnet,test_constructors_cc4293.py,success->fail,success,fail,,"test_constructors_cc4293.py:21: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
claude3_sonnet,test_conversion_928a39.py,fail->success,fail,success,"test_conversion_928a39.py:204: error: Incompatible types in assignment (expression has type ""ndarray[Any, dtype[Any]]"", variable has type ""list[Any]"") [assignment]",
claude3_sonnet,test_converter_orderflow_7dad6d.py,success->fail,success,fail,,"test_converter_orderflow_7dad6d.py:171: error: Unsupported left operand type for | (""Dict[str, Any]"") [operator]"
claude3_sonnet,test_cumulative_8df6e0.py,fail->success,fail,success,"test_cumulative_8df6e0.py:27: error: ""ndarray[Any, Any]"" has no attribute ""values"" [attr-defined]",
claude3_sonnet,test_datetimes_630624.py,success->fail,success,fail,,"test_datetimes_630624.py:20: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
claude3_sonnet,test_decorators_98d50d.py,fail->success,fail,success,"test_decorators_98d50d.py:32: error: Argument ""mode"" to ""inspect_validator"" has incompatible type ""str""; expected ""Literal['before', 'after', 'wrap', 'plain']"" [arg-type]",
claude3_sonnet,test_digest_a03eb9.py,success->fail,success,fail,,"test_digest_a03eb9.py:51: error: ""object"" has no attribute ""__enter__"" [attr-defined]"
claude3_sonnet,test_edge_d080a8.py,success->fail,success,fail,,"test_edge_d080a8.py:29: error: Name ""pytest.LogCaptureFixture"" is not defined [name-defined]"
claude3_sonnet,test_expressions_597e20.py,success->fail,success,fail,,"test_expressions_597e20.py:74: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
claude3_sonnet,test_flags_92e1da.py,success->fail,success,fail,,"test_flags_92e1da.py:60: error: Name ""pytest.MonkeyPatch"" is not defined [name-defined]"
claude3_sonnet,test_frame_plot_matplotlib_9669ca.py,fail->success,fail,success,"test_frame_plot_matplotlib_9669ca.py:46: error: Item ""SubFigure"" of ""Figure | SubFigure | None"" has no attribute ""savefig"" [union-attr]",
claude3_sonnet,test_graph_69fed4.py,success->fail,success,fail,,"test_graph_69fed4.py:37: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
claude3_sonnet,test_groupby_dropna_4126e9.py,fail->success,fail,success,"test_groupby_dropna_4126e9.py:197: error: Argument 1 to ""choice"" of ""Generator"" has incompatible type ""list[int | None]""; expected ""_SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]"" [arg-type]",
claude3_sonnet,test_helpers_38220e.py,success->fail,success,fail,,"test_helpers_38220e.py:272: error: Method ""get_host"" is marked as an override, but no base method was found with this name [misc]"
claude3_sonnet,test_history_818171.py,success->fail,success,fail,,"test_history_818171.py:114: error: Value of type ""Optional[List[List[float]]]"" is not indexable [index]"
claude3_sonnet,test_img_util_826a0b.py,success->fail,success,fail,,"test_img_util_826a0b.py:61: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
claude3_sonnet,test_incremental_schema_fd049d.py,success->fail,success,fail,,"test_incremental_schema_fd049d.py:20: error: Name ""Any"" is not defined [name-defined]"
claude3_sonnet,test_indexing_3e5a66.py,success->fail,success,fail,,"test_indexing_3e5a66.py:47: error: Name ""pytest.MonkeyPatch"" is not defined [name-defined]"
claude3_sonnet,test_indexing_8b3a8e.py,fail->success,fail,success,"test_indexing_8b3a8e.py:380: error: Slice index must be an integer, SupportsIndex or None [misc]",
claude3_sonnet,test_inference_f5d827.py,success->fail,success,fail,,"test_inference_f5d827.py:224: error: ""List[Any]"" has no attribute ""shape"" [attr-defined]"
claude3_sonnet,test_info_8bfc42.py,success->fail,success,fail,,"test_info_8bfc42.py:209: error: ""List[str]"" has no attribute ""values"" [attr-defined]"
claude3_sonnet,test_init_e32ce0.py,success->fail,success,fail,,"test_init_e32ce0.py:402: error: Name ""pytest.LogCaptureFixture"" is not defined [name-defined]"
claude3_sonnet,test_isin_243dba.py,success->fail,success,fail,,"test_isin_243dba.py:141: error: Name ""pytest.MonkeyPatch"" is not defined [name-defined]"
claude3_sonnet,test_json_7e4832.py,success->fail,success,fail,,"test_json_7e4832.py:213: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
claude3_sonnet,test_kedro_data_catalog_4cfadd.py,success->fail,success,fail,,"test_kedro_data_catalog_4cfadd.py:97: error: Name ""pytest.LogCaptureFixture"" is not defined [name-defined]"
claude3_sonnet,test_layers_95be9f.py,fail->success,fail,success,"test_layers_95be9f.py:178: error: Incompatible types in assignment (expression has type ""Tensor"", variable has type ""ndarray[Any, dtype[floating[Any]]]"") [assignment]",
claude3_sonnet,test_liboffsets_a4381d.py,success->fail,success,fail,,"test_liboffsets_a4381d.py:14: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
claude3_sonnet,test_logging_8b4caf.py,success->fail,success,fail,,"test_logging_8b4caf.py:81: error: Name ""pytest.CaptureFixture"" is not defined [name-defined]"
claude3_sonnet,test_mediation_fee_82ecfe.py,success->fail,success,fail,,"test_mediation_fee_82ecfe.py:216: error: The return type of a generator function should be ""Generator"" or one of its supertypes [misc]"
claude3_sonnet,test_monitor_31e01e.py,success->fail,success,fail,,"test_monitor_31e01e.py:354: error: ""tuple"" is not subscriptable, use ""typing.Tuple"" instead [misc]"
claude3_sonnet,test_mssql_35a1b8.py,fail->success,fail,success,"test_mssql_35a1b8.py:28: error: Need type annotation for ""str_col"" [var-annotated]",
claude3_sonnet,test_multi_209bc7.py,fail->success,fail,success,"test_multi_209bc7.py:108: error: Incompatible types in assignment (expression has type ""ndarray[Any, dtype[Any]]"", variable has type ""list[str]"") [assignment]",
claude3_sonnet,test_nth_cbbcbb.py,fail->success,fail,success,"test_nth_cbbcbb.py:56: error: Incompatible types in assignment (expression has type ""ndarray[Any, dtype[Any]]"", variable has type ""list[int]"") [assignment]",
claude3_sonnet,test_numeric_only_37163c.py,success->fail,success,fail,,"test_numeric_only_37163c.py:64: error: No overload variant of ""raises"" matches argument types ""object"", ""str"" [call-overload]"
claude3_sonnet,test_offsets_595cf3.py,fail->success,fail,success,"test_offsets_595cf3.py:152: error: Argument 3 to ""_check_offsetfunc_works"" of ""TestCommon"" has incompatible type ""object""; expected ""datetime | datetime64"" [arg-type]",
claude3_sonnet,test_overlaps_cda380.py,success->fail,success,fail,,"test_overlaps_cda380.py:10: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
claude3_sonnet,test_process_execution_payload_f9e9ad.py,success->fail,success,fail,,"test_process_execution_payload_f9e9ad.py:213: error: ""List[Any]"" has no attribute ""hash_tree_root"" [attr-defined]"
claude3_sonnet,test_process_sync_aggregate_c588af.py,success->fail,success,fail,,"test_process_sync_aggregate_c588af.py:112: error: The return type of a generator function should be ""Generator"" or one of its supertypes [misc]"
claude3_sonnet,test_raidenservice_d5e26d.py,fail->success,fail,success,"test_raidenservice_d5e26d.py:129: error: ""object"" has no attribute ""proxy_manager"" [attr-defined]",
claude3_sonnet,test_rank_d0371a.py,success->fail,success,fail,,"test_rank_d0371a.py:31: error: ""List[Any]"" has no attribute ""reindex""; maybe ""index""? [attr-defined]"
claude3_sonnet,test_reductions_ebf449.py,fail->success,fail,success,"test_reductions_ebf449.py:61: error: No overload variant of ""any"" matches argument types ""Any"", ""bool"" [call-overload]",
claude3_sonnet,test_rocksdb_e6756b.py,success->fail,success,fail,,"test_rocksdb_e6756b.py:70: error: The return type of a generator function should be ""Generator"" or one of its supertypes [misc]"
claude3_sonnet,test_round_0a4ab4.py,fail->success,fail,success,"test_round_0a4ab4.py:169: error: Incompatible types in assignment (expression has type ""signedinteger[_64Bit]"", variable has type ""int"") [assignment]",
claude3_sonnet,test_round_trip_b8b484.py,success->fail,success,fail,,"test_round_trip_b8b484.py:303: error: ""dict"" is not subscriptable, use ""typing.Dict"" instead [misc]"
claude3_sonnet,test_series_5f79c1.py,success->fail,success,fail,,test_series_5f79c1.py:373: error: X | Y syntax for unions requires Python 3.10 [syntax]
claude3_sonnet,test_sort_index_efa5b2.py,success->fail,success,fail,,"test_sort_index_efa5b2.py:118: error: No overload variant of ""zip"" matches argument type ""List[object]"" [call-overload]"
claude3_sonnet,test_sparse_d759ae.py,fail->success,fail,success,"test_sparse_d759ae.py:15: error: Incompatible types in assignment (expression has type ""ndarray[Any, dtype[signedinteger[Any]]]"", variable has type ""ndarray[Any, dtype[floating[_64Bit]]]"") [assignment]",
claude3_sonnet,test_stoploss_on_exchange_98cce5.py,success->fail,success,fail,,"test_stoploss_on_exchange_98cce5.py:42: error: Name ""pytest.LogCaptureFixture"" is not defined [name-defined]"
claude3_sonnet,test_strategy_helpers_2175ad.py,fail->success,fail,success,"test_strategy_helpers_2175ad.py:154: error: No overload variant of ""linspace"" matches argument type ""list[float]"" [call-overload]",
claude3_sonnet,test_string_c0dad8.py,success->fail,success,fail,,"D:\python3.8\lib\site-packages\_pytest\outcomes.py:119: note: ""skip"" defined here"
claude3_sonnet,test_to_csv_2a1c22.py,success->fail,success,fail,,"test_to_csv_2a1c22.py:274: error: Name ""pytest.CaptureFixture"" is not defined [name-defined]"
claude3_sonnet,test_utils_121373.py,fail->success,fail,success,test_utils_121373.py:61: error: List comprehension has incompatible type List[TextIOWrapper[_WrappedBuffer]]; expected List[list[str]] [misc],
claude3_sonnet,test_web_websocket_389e12.py,fail->success,fail,success,"test_web_websocket_389e12.py:11: error: Module ""aiohttp.http_websocket"" has no attribute ""WSMessageClose""; maybe ""WSMessage""? [attr-defined]",
claude3_sonnet,test_websocket_parser_3e2e83.py,fail->success,fail,success,"test_websocket_parser_3e2e83.py:14: error: Module ""aiohttp.http_websocket"" has no attribute ""WSMessageBinary"" [attr-defined]",
claude3_sonnet,test_win_type_fcca97.py,success->fail,success,fail,,"test_win_type_fcca97.py:9: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
claude3_sonnet,test_wrap_modes_beed23.py,success->fail,success,fail,,"test_wrap_modes_beed23.py:4: error: Module ""typing"" has no attribute ""NotRequired"" [attr-defined]"
claude3_sonnet,tools_6a9569.py,fail->success,fail,success,"tools_6a9569.py:182: error: Item ""Axes"" of ""Axes | list[Axes] | ndarray[Any, dtype[Any]] | ndarray[Any, Any]"" has no attribute ""size"" [union-attr]",
claude3_sonnet,topic_6b7f8d.py,success->fail,success,fail,,"topic_6b7f8d.py:132: error: ""str"" has no attribute ""removeprefix"" [attr-defined]"
claude3_sonnet,tracing_fe42d6.py,success->fail,success,fail,,"tracing_fe42d6.py:100: error: Incompatible types in assignment (expression has type ""Optional[FrameType]"", variable has type ""FrameType"") [assignment]"
claude3_sonnet,transactions_dad89f.py,success->fail,success,fail,,"transactions_dad89f.py:42: error: Unsupported operand types for * (""int"" and ""None"") [operator]"
claude3_sonnet,type_cameras_3d7c68.py,fail->success,fail,success,"type_cameras_3d7c68.py:143: error: Name ""datetime"" is not defined [name-defined]",
claude3_sonnet,upnp_cf635d.py,success->fail,success,fail,,"upnp_cf635d.py:92: error: Module has no attribute ""SO_REUSEPORT"" [attr-defined]"
claude3_sonnet,views_61a9fc.py,fail->success,fail,success,"views_61a9fc.py:134: error: Incompatible types in assignment (expression has type ""int"", variable has type ""str | None"") [assignment]",
gpt35,__init___49f91b.py,fail->success,fail,success,"__init___49f91b.py:6: error: ""Callable[[Any], None]"" has no attribute ""check"" [attr-defined]",
gpt35,__init___4ea406.py,fail->success,fail,success,"__init___4ea406.py:62: error: Invalid statement in TypedDict definition; expected ""field_name: field_type"" [misc]",
gpt35,__init___7ab01a.py,fail->success,fail,success,"__init___7ab01a.py:4: error: Incompatible default for argument ""pattern"" (default has type ""None"", argument has type ""str"") [assignment]",
gpt35,__init___93171f.py,fail->success,fail,success,"__init___93171f.py:17: error: Name ""List"" is not defined [name-defined]",
gpt35,__init___db92f1.py,success->fail,success,fail,,__init___db92f1.py:338: error: unexpected EOF while parsing [syntax]
gpt35,attachment_scores_test_b605c1.py,fail->success,fail,success,attachment_scores_test_b605c1.py:1: error: unexpected indent [syntax],
gpt35,attester_slashings_270ad2.py,fail->success,fail,success,"attester_slashings_270ad2.py:28: error: Name ""List"" is not defined [name-defined]",
gpt35,base_a0b3af.py,fail->success,fail,success,"base_a0b3af.py:21: error: Missing positional arguments ""numbers"", ""vip"" in call to ""Contact"" [call-arg]",
gpt35,call_824067.py,success->fail,success,fail,,call_824067.py:22: error: Missing return statement [empty-body]
gpt35,collections_5f4a3a.py,fail->success,fail,success,collections_5f4a3a.py:5: error: invalid syntax [syntax],
gpt35,conftest_4ecb9c.py,fail->success,fail,success,conftest_4ecb9c.py:24: error: Missing return statement [empty-body],
gpt35,coordinator_04d05c.py,fail->success,fail,success,"coordinator_04d05c.py:22: error: Incompatible types in assignment (expression has type ""None"", variable has type ""Callable[..., Any]"") [assignment]",
gpt35,encoding_c1153a.py,fail->success,fail,success,"encoding_c1153a.py:1: error: Name ""Union"" is not defined [name-defined]",
gpt35,entities_19afaa.py,success->fail,success,fail,,entities_19afaa.py:11: error: invalid syntax [syntax]
gpt35,entity_3c2299.py,success->fail,success,fail,,entity_3c2299.py:59: error: invalid syntax [syntax]
gpt35,entity_86b8a0.py,fail->success,fail,success,"entity_86b8a0.py:87: error: Unsupported target for indexed assignment (""Mapping[str, Any]"") [index]",
gpt35,execution_payload_94f3fe.py,fail->success,fail,success,"execution_payload_94f3fe.py:9: error: Name ""ExecutionPayload"" is not defined [name-defined]",
gpt35,fan_7d4617.py,success->fail,success,fail,,"fan_7d4617.py:48: error: Incompatible return value type (got ""Optional[str]"", expected ""str"") [return-value]"
gpt35,file_name_dac33e.py,success->fail,success,fail,,file_name_dac33e.py:186: error: invalid syntax [syntax]
gpt35,helpers_e73aba.py,success->fail,success,fail,,helpers_e73aba.py:29: error: Missing return statement [empty-body]
gpt35,humidifier_e2948a.py,fail->success,fail,success,"humidifier_e2948a.py:10: error: Name ""XiaomiCoordinatedMiioEntity"" is not defined [name-defined]",
gpt35,image_91d679.py,success->fail,success,fail,,"image_91d679.py:23: error: Name ""Callable"" is not defined [name-defined]"
gpt35,json_7c2407.py,success->fail,success,fail,,"json_7c2407.py:3: error: Name ""json"" is not defined [name-defined]"
gpt35,light_client_9189e8.py,fail->success,fail,success,"light_client_9189e8.py:35: error: Incompatible default for argument ""num_participants"" (default has type ""None"", argument has type ""int"") [assignment]",
gpt35,light_d31785.py,fail->success,fail,success,"light_d31785.py:1: error: Name ""HomeAssistant"" is not defined [name-defined]",
gpt35,makemessages_b575f4.py,success->fail,success,fail,,"makemessages_b575f4.py:17: error: ""list"" is not subscriptable, use ""typing.List"" instead [misc]"
gpt35,numpy__844898.py,fail->success,fail,success,"numpy__844898.py:269: error: Incompatible return value type (got ""Tuple[NumpyExtensionArray, NumpyExtensionArray]"", expected ""NumpyExtensionArray"") [return-value]",
gpt35,pipeline_a41664.py,success->fail,success,fail,,pipeline_a41664.py:32: error: invalid syntax [syntax]
gpt35,responses_7e84ca.py,fail->success,fail,success,"responses_7e84ca.py:74: error: Name ""datetime"" is not defined [name-defined]",
gpt35,run_f6671c.py,success->fail,success,fail,,"run_f6671c.py:67: error: Name ""List"" is not defined [name-defined]"
gpt35,scheduler_tests_223cad.py,fail->success,fail,success,"scheduler_tests_223cad.py:14: error: Function ""builtins.callable"" is not valid as a type [valid-type]",
gpt35,schemas_156b3c.py,success->fail,success,fail,,schemas_156b3c.py:15: error: non-default argument follows default argument [syntax]
gpt35,schemas_911003.py,fail->success,fail,success,schemas_911003.py:276: error: EOL while scanning string literal [syntax],
gpt35,steps_1f3861.py,fail->success,fail,success,steps_1f3861.py:3: error: invalid syntax [syntax],
gpt35,streams_a2a52b.py,fail->success,fail,success,"streams_a2a52b.py:156: error: Name ""AsyncIterator"" is not defined [name-defined]",
gpt35,string_arrow_ce4e9d.py,success->fail,success,fail,,string_arrow_ce4e9d.py:27: error: Missing return statement [empty-body]
gpt35,superset_factory_util_7e174c.py,fail->success,fail,success,superset_factory_util_7e174c.py:10: error: invalid syntax [syntax],
gpt35,test_appgraph_6f35e2.py,fail->success,fail,success,"test_appgraph_6f35e2.py:10: error: Incompatible default for argument ""iam_role_arn"" (default has type ""None"", argument has type ""str"") [assignment]",
gpt35,test_base_7e51af.py,success->fail,success,fail,,"test_base_7e51af.py:37: error: Name ""List"" is not defined [name-defined]"
gpt35,test_btanalysis_4aed6c.py,fail->success,fail,success,test_btanalysis_4aed6c.py:18: error: invalid syntax [syntax],
gpt35,test_cat_c39959.py,success->fail,success,fail,,test_cat_c39959.py:4: error: invalid syntax [syntax]
gpt35,test_ccxt_compat_f96503.py,success->fail,success,fail,,test_ccxt_compat_f96503.py:13: error: invalid syntax [syntax]
gpt35,test_common_27891c.py,success->fail,success,fail,,test_common_27891c.py:7: error: Missing return statement [empty-body]
gpt35,test_compression_21f3e4.py,fail->success,fail,success,test_compression_21f3e4.py:4: error: invalid syntax [syntax],
gpt35,test_config_flow_a5fd81.py,success->fail,success,fail,,test_config_flow_a5fd81.py:289: error: EOL while scanning string literal [syntax]
gpt35,test_conversion_928a39.py,success->fail,success,fail,,test_conversion_928a39.py:4: error: invalid syntax [syntax]
gpt35,test_converter_orderflow_7dad6d.py,success->fail,success,fail,,"test_converter_orderflow_7dad6d.py:32: error: Argument 1 to ""read_csv"" has incompatible type ""Path""; expected ""str"" [arg-type]"
gpt35,test_coop_settle_fd62d3.py,success->fail,success,fail,,"test_coop_settle_fd62d3.py:15: error: Name ""random"" is not defined [name-defined]"
gpt35,test_denodo_4cd030.py,success->fail,success,fail,,test_denodo_4cd030.py:3: error: invalid syntax [syntax]
gpt35,test_deposit_transition_1d40b5.py,fail->success,fail,success,"test_deposit_transition_1d40b5.py:47: error: Incompatible default for argument ""deposit_requests_start_index"" (default has type ""None"", argument has type ""int"") [assignment]",
gpt35,test_drop_537b51.py,fail->success,fail,success,test_drop_537b51.py:51: error: invalid syntax [syntax],
gpt35,test_dtypes_e2af21.py,fail->success,fail,success,test_dtypes_e2af21.py:41: error: invalid syntax [syntax],
gpt35,test_eth1_chaindb_433a8a.py,success->fail,success,fail,,test_eth1_chaindb_433a8a.py:25: error: Invalid type comment or annotation [valid-type]
gpt35,test_file_buffer_url_2ebfea.py,fail->success,fail,success,test_file_buffer_url_2ebfea.py:16: error: invalid syntax [syntax],
gpt35,test_find_replace_bc2ab9.py,fail->success,fail,success,"test_find_replace_bc2ab9.py:14: error: Name ""Union"" is not defined [name-defined]",
gpt35,test_floats_b22095.py,fail->success,fail,success,test_floats_b22095.py:280: error: unexpected EOF while parsing [syntax],
gpt35,test_frame_subplots_be5b29.py,success->fail,success,fail,,test_frame_subplots_be5b29.py:100: error: Missing return statement [empty-body]
gpt35,test_freqai_interface_ca78dd.py,success->fail,success,fail,,"test_freqai_interface_ca78dd.py:16: error: Name ""pytest"" is not defined [name-defined]"
gpt35,test_hist_box_by_07b6c3.py,success->fail,success,fail,,test_hist_box_by_07b6c3.py:87: error: closing parenthesis ')' does not match opening parenthesis '[' [syntax]
gpt35,test_indexing_e492e0.py,success->fail,success,fail,,test_indexing_e492e0.py:5: error: invalid syntax [syntax]
gpt35,test_init_e32ce0.py,fail->success,fail,success,test_init_e32ce0.py:33: error: invalid syntax [syntax],
gpt35,test_interval_e04786.py,fail->success,fail,success,test_interval_e04786.py:12: error: invalid syntax [syntax],
gpt35,test_meta_learners_15283b.py,success->fail,success,fail,,test_meta_learners_15283b.py:36: error: Missing return statement [empty-body]
gpt35,test_mysql_b75555.py,fail->success,fail,success,"test_mysql_b75555.py:73: error: Name ""List"" is not defined [name-defined]",
gpt35,test_nodes_c6ed78.py,success->fail,success,fail,,test_nodes_c6ed78.py:1: error: unexpected indent [syntax]
gpt35,test_notifications_endpoint_08d1aa.py,success->fail,success,fail,,test_notifications_endpoint_08d1aa.py:8: error: invalid syntax [syntax]
gpt35,test_notify_74a852.py,success->fail,success,fail,,test_notify_74a852.py:23: error: Missing return statement [empty-body]
gpt35,test_numba_a7df98.py,success->fail,success,fail,,test_numba_a7df98.py:315: error: invalid syntax [syntax]
gpt35,test_operations_088d14.py,fail->success,fail,success,test_operations_088d14.py:6: error: Missing return statement [empty-body],
gpt35,test_process_pending_consolidations_a9c6ec.py,fail->success,fail,success,"test_process_pending_consolidations_a9c6ec.py:9: error: The return type of a generator function should be ""Generator"" or one of its supertypes [misc]",
gpt35,test_process_withdrawal_request_9f973e.py,fail->success,fail,success,"test_process_withdrawal_request_9f973e.py:19: error: Name ""expect_assertion_error"" is not defined [name-defined]",
gpt35,test_pythonapi_d455c1.py,success->fail,success,fail,,test_pythonapi_d455c1.py:342: error: invalid syntax [syntax]
gpt35,test_raidenservice_d5e26d.py,success->fail,success,fail,,"test_raidenservice_d5e26d.py:26: error: Name ""pytest"" is not defined [name-defined]"
gpt35,test_raises_891508.py,fail->success,fail,success,"test_raises_891508.py:22: error: Argument 1 to ""raises"" has incompatible type ""Tuple[type, str]""; expected ""Union[Type[<nothing>], Tuple[Type[<nothing>], ...]]"" [arg-type]",
gpt35,test_reductions_ebf449.py,fail->success,fail,success,test_reductions_ebf449.py:37: error: invalid syntax [syntax],
gpt35,test_runner_4222e5.py,success->fail,success,fail,,test_runner_4222e5.py:20: error: Missing return statement [empty-body]
gpt35,test_setops_3892f2.py,success->fail,success,fail,,test_setops_3892f2.py:17: error: invalid syntax [syntax]
gpt35,test_sorting_c07df0.py,fail->success,fail,success,"test_sorting_c07df0.py:216: error: No overload variant of ""raises"" matches argument types ""Exception"", ""str"" [call-overload]",
gpt35,test_sparse_d759ae.py,success->fail,success,fail,,"test_sparse_d759ae.py:20: error: Name ""pytest.FixtureRequest"" is not defined [name-defined]"
gpt35,test_style_48cf89.py,success->fail,success,fail,,"test_style_48cf89.py:13: error: ""object"" has no attribute ""alignment"" [attr-defined]"
gpt35,test_task_e78dda.py,success->fail,success,fail,,"test_task_e78dda.py:8: error: The return type of a generator function should be ""Generator"" or one of its supertypes [misc]"
gpt35,test_tone_convert_a42800.py,fail->success,fail,success,"test_tone_convert_a42800.py:168: error: Name ""to_final"" is not defined [name-defined]",
gpt35,test_validator_417f9a.py,success->fail,success,fail,,"test_validator_417f9a.py:13: error: Name ""SyncCommittee"" is not defined [name-defined]"
gpt35,test_validator_unittest_4d4a84.py,success->fail,success,fail,,"test_validator_unittest_4d4a84.py:141: error: Name ""PHASE0"" is not defined [name-defined]"
gpt35,test_websocket_parser_3e2e83.py,success->fail,success,fail,,test_websocket_parser_3e2e83.py:19: error: Missing return statement [empty-body]
gpt35,timedeltas_44fa81.py,fail->success,fail,success,"timedeltas_44fa81.py:57: error: Name ""ndarray"" is not defined [name-defined]",
gpt35,timeout_e854c4.py,success->fail,success,fail,,timeout_e854c4.py:1: error: unexpected indent [syntax]
gpt35,token_49945a.py,success->fail,success,fail,,token_49945a.py:1: error: unexpected indent [syntax]
gpt35,transport_58bb8a.py,success->fail,success,fail,,"transport_58bb8a.py:1: error: Module ""typing"" has no attribute ""Address"" [attr-defined]"
gpt35,update_96e467.py,success->fail,success,fail,,"update_96e467.py:4: error: Name ""HomeAssistant"" is not defined [name-defined]"
o3_mini,BaseEnvironment_875d27.py,success->fail,success,fail,,BaseEnvironment_875d27.py:223: error: Return value expected [return-value]
o3_mini,__init___417be1.py,success->fail,success,fail,,"__init___417be1.py:125: error: Incompatible return value type (got ""tuple[Any, str | Any | bytes]"", expected ""tuple[Any, str]"") [return-value]"
o3_mini,__init___4c124d.py,success->fail,success,fail,,"__init___4c124d.py:86: error: ""AsyncMock"" expects no type arguments, but 1 given [type-arg]"
o3_mini,__init___54e0bc.py,success->fail,success,fail,,"__init___54e0bc.py:143: error: Variable ""unittest.mock.patch"" is not valid as a type [valid-type]"
o3_mini,__init___886e1c.py,fail->success,fail,success,"__init___886e1c.py:136: error: Argument 2 to ""Refactoring"" has incompatible type ""dict[str, dict[Any, str]]""; expected ""dict[Path, dict[Any, str]]"" [arg-type]",
o3_mini,__init___ade613.py,fail->success,fail,success,"__init___ade613.py:47: error: Incompatible default for argument ""thrown_error"" (default has type ""None"", argument has type ""Exception"") [assignment]",
o3_mini,__init___c981d8.py,fail->success,fail,success,"__init___c981d8.py:176: error: Name ""Optional"" is not defined [name-defined]",
o3_mini,__init___cd0888.py,fail->success,fail,success,__init___cd0888.py:48: error: Unexpected type declaration [misc],
o3_mini,__init___db92f1.py,fail->success,fail,success,__init___db92f1.py:71: error: Type cannot be declared in assignment to non-self attribute [misc],
o3_mini,_decorators_cfdb34.py,fail->success,fail,success,"_decorators_cfdb34.py:14: error: Cannot redefine ""F"" as a type variable [misc]",
o3_mini,_parser_ad554d.py,fail->success,fail,success,"_parser_ad554d.py:219: error: Argument ""error_on"" to ""skip_until"" has incompatible type ""frozenset[str]""; expected ""set[str]"" [arg-type]",
o3_mini,_xlsxwriter_8ba0cd.py,fail->success,fail,success,"_xlsxwriter_8ba0cd.py:6: error: Name ""TYPE_CHECKING"" is not defined [name-defined]",
o3_mini,accessories_b90bda.py,fail->success,fail,success,"accessories_b90bda.py:222: error: Incompatible types in assignment (expression has type ""None"", variable has type ""str"") [assignment]",
o3_mini,api_test_5baf5c.py,fail->success,fail,success,api_test_5baf5c.py:1148: error: closing parenthesis '}' does not match opening parenthesis '[' [syntax],
o3_mini,base_7f1c49.py,success->fail,success,fail,,base_7f1c49.py:26: error: Invalid type comment or annotation [valid-type]
o3_mini,base_949c11.py,fail->success,fail,success,base_949c11.py:63: error: Missing return statement [empty-body],
o3_mini,base_9c14fc.py,fail->success,fail,success,"base_9c14fc.py:294: error: ""Mapping[tuple[int, float], set[Any]]"" has no attribute ""pop"" [attr-defined]",
o3_mini,base_a0b3af.py,success->fail,success,fail,,"base_a0b3af.py:57: error: Item ""None"" of ""Any | None"" has no attribute ""get_all_name_numbers"" [union-attr]"
o3_mini,base_c73d2b.py,success->fail,success,fail,,"base_c73d2b.py:161: error: The return type of a generator function should be ""Generator"" or one of its supertypes [misc]"
o3_mini,bias_mitigator_wrappers_4e83be.py,fail->success,fail,success,"bias_mitigator_wrappers_4e83be.py:85: error: Incompatible types in assignment (expression has type ""Tensor"", variable has type ""list[Tensor]"") [assignment]",
o3_mini,binary_sensor_c09c5d.py,success->fail,success,fail,,"binary_sensor_c09c5d.py:19: error: Name ""Final"" is not defined [name-defined]"
o3_mini,binding_d7e1a8.py,success->fail,success,fail,,"binding_d7e1a8.py:118: error: Name ""self"" is used before definition [used-before-def]"
o3_mini,blueprints_a0a4a9.py,success->fail,success,fail,,"blueprints_a0a4a9.py:61: error: Name ""Union"" is not defined [name-defined]"
o3_mini,boxplot_f690b9.py,success->fail,success,fail,,"boxplot_f690b9.py:73: error: Incompatible types in assignment (expression has type overloaded function, variable has type ""Callable[[Any], float]"") [assignment]"
o3_mini,browser_8130a6.py,success->fail,success,fail,,"browser_8130a6.py:190: error: Incompatible types in assignment (expression has type ""Any | None"", variable has type ""str"") [assignment]"
o3_mini,cache_7cc469.py,fail->success,fail,success,"cache_7cc469.py:19: error: Name ""ClassVar"" is not defined [name-defined]",
o3_mini,cache_policies_2cc3d9.py,success->fail,success,fail,,"cache_policies_2cc3d9.py:101: error: Argument 2 has incompatible type ""dict[str, Any] | None""; expected ""dict[str, Any]"" [arg-type]"
o3_mini,camera_cb6050.py,fail->success,fail,success,"camera_cb6050.py:86: error: Incompatible types in assignment (expression has type ""Image"", variable has type ""ImageFile"") [assignment]",
o3_mini,channel_771f46.py,success->fail,success,fail,,"channel_771f46.py:151: error: Argument 1 to ""create_task"" has incompatible type ""Awaitable[Any]""; expected ""Generator[Any, None, Any] | Coroutine[Any, Any, Any]"" [arg-type]"
o3_mini,client_aeeaee.py,fail->success,fail,success,client_aeeaee.py:104: error: List comprehension has incompatible type List[str]; expected List[UUID] [misc],
o3_mini,climate_588757.py,success->fail,success,fail,,climate_588757.py:361: error: invalid syntax [syntax]
o3_mini,climate_9e8de7.py,fail->success,fail,success,"climate_9e8de7.py:136: error: Incompatible types in assignment (expression has type ""float"", variable has type ""int | None"") [assignment]",
o3_mini,collection_a8ceb1.py,fail->success,fail,success,"collection_a8ceb1.py:10: error: Type variable ""collection_a8ceb1.T"" is unbound [valid-type]",
o3_mini,common_4a17c0.py,success->fail,success,fail,,"common_4a17c0.py:102: error: Incompatible types in assignment (expression has type ""str"", target has type ""bool"") [assignment]"
o3_mini,common_888838.py,fail->success,fail,success,"common_888838.py:61: error: Argument 1 has incompatible type ""T@__init__""; expected ""T@delegate"" [arg-type]",
o3_mini,common_bbc0b0.py,success->fail,success,fail,,common_bbc0b0.py:152: error: Type cannot be declared in assignment to non-self attribute [misc]
o3_mini,compression_utils_d50545.py,success->fail,success,fail,,"compression_utils_d50545.py:47: error: Function ""zlib.compressobj"" is not valid as a type [valid-type]"
o3_mini,conftest_dc3d22.py,success->fail,success,fail,,"conftest_dc3d22.py:218: error: Incompatible return value type (got ""Callable[[str, int, int], MagicMock]"", expected ""Callable[[str, int, int | None], MagicMock]"") [return-value]"
o3_mini,construction_4e8f89.py,success->fail,success,fail,,"construction_4e8f89.py:52: error: Name ""TYPE_CHECKING"" is not defined [name-defined]"
o3_mini,copartitioned_assignor_d68f8c.py,fail->success,fail,success,"copartitioned_assignor_d68f8c.py:180: error: Item ""None"" of ""Any | None"" has no attribute ""assign_partition"" [union-attr]",
o3_mini,cover_c586a7.py,fail->success,fail,success,cover_c586a7.py:24: error: expected an indented block after 'for' statement on line 23 [syntax],
o3_mini,csvs_0376ba.py,success->fail,success,fail,,"csvs_0376ba.py:95: error: Incompatible return value type (got ""Any | Literal[False] | tuple[Any, ...] | list[Any]"", expected ""bool | list[Hashable] | None"") [return-value]"
o3_mini,datetimelike_f48bd1.py,fail->success,fail,success,"datetimelike_f48bd1.py:410: error: Item ""ndarray[Any, Any]"" of ""ndarray[Any, Any] | Any"" has no attribute ""values"" [union-attr]",
o3_mini,discovery_c67402.py,fail->success,fail,success,"discovery_c67402.py:16: error: Unexpected keyword argument ""total"" for ""__init_subclass__"" of ""object"" [call-arg]",
o3_mini,document_48bf0e.py,success->fail,success,fail,,"document_48bf0e.py:150: error: Item ""None"" of ""Any | None"" has no attribute ""properties"" [union-attr]"
o3_mini,dynamic_params_5296db.py,fail->success,fail,success,"dynamic_params_5296db.py:74: error: The return type of a generator function should be ""Generator"" or one of its supertypes [misc]",
o3_mini,email_mirror_590460.py,fail->success,fail,success,"email_mirror_590460.py:97: error: Incompatible return value type (got ""str | None"", expected ""str"") [return-value]",
o3_mini,entities_19afaa.py,fail->success,fail,success,"entities_19afaa.py:37: error: Name ""Any"" is not defined [name-defined]",
o3_mini,entity_369eaa.py,success->fail,success,fail,,"entity_369eaa.py:30: error: Incompatible types in assignment (expression has type ""Any | None"", variable has type ""str"") [assignment]"
o3_mini,entity_a0478b.py,fail->success,fail,success,"entity_a0478b.py:60: error: Need type annotation for ""_attr_extra_state_attributes"" (hint: ""_attr_extra_state_attributes: dict[<type>, <type>] = ..."") [var-annotated]",
o3_mini,execution_855aa0.py,success->fail,success,fail,,"execution_855aa0.py:23: error: ""MockedTimedExecutor"" has no attribute ""time"" [attr-defined]"
o3_mini,exposed_entities_a550ba.py,fail->success,fail,success,"exposed_entities_a550ba.py:45: error: Unexpected keyword argument ""total"" for ""__init_subclass__"" of ""object"" [call-arg]",
o3_mini,fan_63b94a.py,success->fail,success,fail,,fan_63b94a.py:158: error: No parent module -- cannot perform relative import
o3_mini,fbeta_verbose_measure_test_a08d84.py,fail->success,fail,success,fbeta_verbose_measure_test_a08d84.py:68: error: List comprehension has incompatible type List[float | list[float]]; expected List[float] [misc],
o3_mini,fork_transition_eab473.py,success->fail,success,fail,,"fork_transition_eab473.py:362: error: List item 0 has incompatible type ""int | None""; expected ""int"" [list-item]"
o3_mini,forms_6e49d8.py,fail->success,fail,success,forms_6e49d8.py:411: error: unmatched ']' [syntax],
o3_mini,freqai_test_strat_0dc220.py,fail->success,fail,success,"freqai_test_strat_0dc220.py:19: error: Dict entry 0 has incompatible type ""str"": ""dict[str, str]""; expected ""str"": ""str"" [dict-item]",
o3_mini,geo_location_9da493.py,fail->success,fail,success,geo_location_9da493.py:66: error: invalid syntax [syntax],
o3_mini,geo_location_c37acf.py,fail->success,fail,success,"geo_location_c37acf.py:125: error: Name ""UsgsEarthquakesFeedEntry"" is not defined [name-defined]",
o3_mini,git_90c119.py,fail->success,fail,success,"git_90c119.py:280: error: Need type annotation for ""committers"" [var-annotated]",
o3_mini,helpers_062f96.py,fail->success,fail,success,helpers_062f96.py:101: error: invalid syntax [syntax],
o3_mini,hooks_bd685b.py,fail->success,fail,success,"hooks_bd685b.py:113: error: Cannot instantiate abstract class ""HookSearcher"" with abstract attribute ""__next__"" [abstract]",
o3_mini,httpclient_e36adc.py,success->fail,success,fail,,"httpclient_e36adc.py:146: error: Unexpected keyword argument ""url"" for ""HTTPRequest"" [call-arg]"
o3_mini,humidifier_e2948a.py,success->fail,success,fail,,"humidifier_e2948a.py:40: error: Argument 3 to ""XiaomiAirHumidifierMiot"" has incompatible type ""str | None""; expected ""str"" [arg-type]"
o3_mini,image_91d679.py,success->fail,success,fail,,"image_91d679.py:129: error: Incompatible types in assignment (expression has type ""tuple[Any | BaseException, Any | BaseException]"", variable has type ""list[Any]"") [assignment]"
o3_mini,influence_interpreter_a2577a.py,fail->success,fail,success,"influence_interpreter_a2577a.py:168: error: Incompatible types in assignment (expression has type ""tuple[Tensor, ...]"", variable has type ""list[Tensor]"") [assignment]",
o3_mini,input_reduction_cfaaeb.py,fail->success,fail,success,"input_reduction_cfaaeb.py:86: error: Item ""None"" of ""list[int] | None"" has no attribute ""__delitem__"" [union-attr]",
o3_mini,instrumentations_examples_d8ae97.py,fail->success,fail,success,"instrumentations_examples_d8ae97.py:125: error: Argument 3 to ""testing_domain_and_loss_and_budget"" has incompatible type ""signedinteger[_64Bit | Any]""; expected ""int"" [arg-type]",
o3_mini,iresolver_51e6b1.py,fail->success,fail,success,"iresolver_51e6b1.py:130: error: ""type"" has no attribute ""__file__"" [attr-defined]",
o3_mini,kill_if_no_output_54c848.py,fail->success,fail,success,"kill_if_no_output_54c848.py:60: error: Incompatible return value type (got ""int | None"", expected ""int"") [return-value]",
o3_mini,light_7346d9.py,fail->success,fail,success,"light_7346d9.py:442: error: Unsupported right operand type for in (""list[str] | None"") [operator]",
o3_mini,light_client_sync_2b8d7f.py,success->fail,success,fail,,"light_client_sync_2b8d7f.py:47: error: ""LightClientSyncTest"" has no attribute ""store"" [attr-defined]"
o3_mini,log_config_fb42e8.py,success->fail,success,fail,,"log_config_fb42e8.py:168: error: List item 2 has incompatible type ""Callable[[Any, str, dict[str, Any]], dict[str, Any]]""; expected ""Callable[[Any], Any]"" [list-item]"
o3_mini,manager_37b184.py,success->fail,success,fail,,"manager_37b184.py:48: error: Trying to assign name ""_debug"" that is not in ""__slots__"" of type ""manager_37b184.HomeAssistantBluetoothManager"" [misc]"
o3_mini,media_player_846062.py,success->fail,success,fail,,"media_player_846062.py:158: error: Incompatible types in assignment (expression has type ""str"", variable has type ""int"") [assignment]"
o3_mini,mediation_fee_f1a080.py,success->fail,success,fail,,"mediation_fee_f1a080.py:157: error: No overload variant of ""Fraction"" matches argument type ""object"" [call-overload]"
o3_mini,meta_learners_cdb80e.py,success->fail,success,fail,,"meta_learners_cdb80e.py:229: error: ""Callable[[Any], Any]"" object is not iterable [misc]"
o3_mini,metrics_edd6bd.py,fail->success,fail,success,"metrics_edd6bd.py:311: error: Argument ""starting_balance"" to ""calculate_max_drawdown"" has incompatible type ""float""; expected ""int"" [arg-type]",
o3_mini,mocks_d2ab6d.py,success->fail,success,fail,,"mocks_d2ab6d.py:289: error: Variable ""mocks_d2ab6d.RoutesDict"" is not valid as a type [valid-type]"
o3_mini,model_test_case_905237.py,success->fail,success,fail,,"model_test_case_905237.py:111: error: Unsupported left operand type for / (""PathLike[Any]"") [operator]"
o3_mini,network_7ec1c6.py,success->fail,success,fail,,"network_7ec1c6.py:245: error: Unsupported operand types for < (""int"" and ""object"") [operator]"
o3_mini,notification_data_d3e584.py,fail->success,fail,success,"notification_data_d3e584.py:305: error: Incompatible types in assignment (expression has type ""float"", variable has type ""int"") [assignment]",
o3_mini,number_c8a6fb.py,fail->success,fail,success,"number_c8a6fb.py:211: error: ""dict[str, Any]"" has no attribute ""event_info"" [attr-defined]",
o3_mini,numeric_b9721d.py,fail->success,fail,success,"numeric_b9721d.py:89: error: ""type"" has no attribute ""_checker"" [attr-defined]",
o3_mini,parallel_runner_14dbef.py,success->fail,success,fail,,"parallel_runner_14dbef.py:9: error: Name ""TYPE_CHECKING"" is not defined [name-defined]"
o3_mini,param_cbed36.py,success->fail,success,fail,,"param_cbed36.py:73: error: Name ""Dict"" is not defined [name-defined]"
o3_mini,params_226a6a.py,success->fail,success,fail,,"params_226a6a.py:86: error: Incompatible types in assignment (expression has type ""dict[Never, Never]"", variable has type ""list[Any]"") [assignment]"
o3_mini,parquet_a441a6.py,fail->success,fail,success,"parquet_a441a6.py:128: error: Argument 1 to ""_get_path_or_handle"" has incompatible type ""str | PathLike[str] | IO[Any]""; expected ""str | PathLike[str]"" [arg-type]",
o3_mini,parser_deb8f1.py,success->fail,success,fail,,"parser_deb8f1.py:131: error: ""int"" has no attribute ""name"" [attr-defined]"
o3_mini,predictor_2dde66.py,success->fail,success,fail,,"predictor_2dde66.py:176: error: Argument 1 to ""register_backward_hook"" of ""Module"" has incompatible type ""Callable[[Module, tuple[Tensor | None, ...], tuple[Tensor | None, ...]], None]""; expected ""Callable[[Module, tuple[Tensor, ...] | Tensor, tuple[Tensor, ...] | Tensor], tuple[Tensor, ...] | Tensor | None]"" [arg-type]"
o3_mini,presence_ce7e57.py,fail->success,fail,success,"presence_ce7e57.py:175: error: Incompatible return value type (got ""tuple[dict[str, dict[str, Any]], int]"", expected ""tuple[defaultdict[Any, Any], int]"") [return-value]",
o3_mini,project_2d0af1.py,success->fail,success,fail,,"project_2d0af1.py:40: error: ""T"" has no attribute ""_name"" [attr-defined]"
o3_mini,py2md_98a5cb.py,success->fail,success,fail,,"py2md_98a5cb.py:140: error: Incompatible types in assignment (expression has type ""None"", variable has type ""dict[str, Param]"") [assignment]"
o3_mini,pystone_d804b9.py,success->fail,success,fail,,"pystone_d804b9.py:119: error: Name ""Int"" is not defined [name-defined]"
o3_mini,query_render_80e011.py,fail->success,fail,success,"query_render_80e011.py:30: error: Unexpected keyword argument ""database"" [call-arg]",
o3_mini,random_033806.py,success->fail,success,fail,,"random_033806.py:125: error: Argument 4 to ""randomize_epoch_participation"" has incompatible type ""Random | None""; expected ""Random"" [arg-type]"
o3_mini,random_value_d2191f.py,fail->success,fail,success,"random_value_d2191f.py:87: error: ""type[T]"" has no attribute ""element_cls"" [attr-defined]",
o3_mini,recorder_650626.py,fail->success,fail,success,"recorder_650626.py:44: error: No overload variant of ""reversed"" matches argument type ""Iterable[Any]"" [call-overload]",
o3_mini,references_c4be98.py,success->fail,success,fail,,"references_c4be98.py:27: error: Argument 2 to ""_resolve_names"" has incompatible type ""Iterable[Any]""; expected ""tuple[Any, ...]"" [arg-type]"
o3_mini,registry_e23820.py,fail->success,fail,success,"registry_e23820.py:82: error: Argument 1 to ""_serializer"" of ""Registry"" has incompatible type ""type[Any] | None""; expected ""type[Any]"" [arg-type]",
o3_mini,regression_5b5987.py,success->fail,success,fail,,"regression_5b5987.py:206: error: Incompatible types in assignment (expression has type ""Any | str | float | int"", variable has type ""float"") [assignment]"
o3_mini,reporter_4f7bfa.py,fail->success,fail,success,"reporter_4f7bfa.py:60: error: Name ""pyflakes"" is not defined [name-defined]",
o3_mini,runner_7722d1.py,fail->success,fail,success,"runner_7722d1.py:23: error: Name ""TYPE_CHECKING"" is not defined [name-defined]",
o3_mini,s3_e58a82.py,fail->success,fail,success,"s3_e58a82.py:23: error: Name ""TYPE_CHECKING"" is not defined [name-defined]",
o3_mini,select_d2495d.py,fail->success,fail,success,"select_d2495d.py:158: error: ""dict[str, Any]"" has no attribute ""event_info"" [attr-defined]",
o3_mini,selector_62ee5d.py,success->fail,success,fail,,"selector_62ee5d.py:126: error: Item ""list[Any]"" of ""Any | Any | list[Any]"" has no attribute ""combined"" [union-attr]"
o3_mini,sensor_2394c2.py,success->fail,success,fail,,sensor_2394c2.py:165: error: invalid syntax [syntax]
o3_mini,sensor_393e9c.py,fail->success,fail,success,"sensor_393e9c.py:90: error: ""Callable[[Any], Any]"" has no attribute ""__iter__"" (not iterable) [attr-defined]",
o3_mini,sensor_677086.py,fail->success,fail,success,"sensor_677086.py:21: error: Name ""OmniLogicTemperatureSensor"" is used before definition [used-before-def]",
o3_mini,sensor_687ec5.py,fail->success,fail,success,"sensor_687ec5.py:71: error: Argument 4 to ""NetdataSensor"" has incompatible type ""str | None""; expected ""str"" [arg-type]",
o3_mini,sensor_7d888f.py,success->fail,success,fail,,"sensor_7d888f.py:67: error: Incompatible types in assignment (expression has type ""MultiMapping[str]"", variable has type ""dict[str, Any]"") [assignment]"
o3_mini,sensor_e47032.py,fail->success,fail,success,"sensor_e47032.py:103: error: Value of type ""dict[str, Any] | None"" is not indexable [index]",
o3_mini,sensor_e99c97.py,fail->success,fail,success,"sensor_e99c97.py:265: error: Incompatible types in assignment (expression has type ""Callable[[Iterable[object]], bool]"", variable has type ""Callable[[object], bool]"") [assignment]",
o3_mini,sensor_f004b2.py,success->fail,success,fail,,"sensor_f004b2.py:233: error: Name ""cast"" is not defined [name-defined]"
o3_mini,sentiment_analysis_suite_5e67f5.py,success->fail,success,fail,,"sentiment_analysis_suite_5e67f5.py:18: error: Argument 1 to ""len"" has incompatible type ""Iterable[str]""; expected ""Sized"" [arg-type]"
o3_mini,sequence_accuracy_test_b352af.py,success->fail,success,fail,,"sequence_accuracy_test_b352af.py:86: error: Incompatible types in assignment (expression has type ""list[Tensor]"", variable has type ""Tensor"") [assignment]"
o3_mini,sequences_74f8b6.py,fail->success,fail,success,"sequences_74f8b6.py:176: error: Return type ""list[float]"" of ""_internal_sampler"" incompatible with return type ""ndarray[Any, Any]"" in supertype ""Sampler"" [override]",
o3_mini,simple_httpclient_5928fa.py,success->fail,success,fail,,"simple_httpclient_5928fa.py:424: error: ""None"" not callable [misc]"
o3_mini,specs_7c250e.py,success->fail,success,fail,,"specs_7c250e.py:5: error: Name ""TYPE_CHECKING"" is not defined [name-defined]"
o3_mini,splitters_9b6f18.py,success->fail,success,fail,,"splitters_9b6f18.py:495: error: Incompatible return value type (got ""tuple[list[tuple[Any, list[Any]]], list[dict[str, Any | int]]]"", expected ""tuple[list[tuple[Any, list[Any]]], list[dict[str, list[Any | int]]]]"") [return-value]"
o3_mini,steps_1f3861.py,fail->success,fail,success,"steps_1f3861.py:303: error: Incompatible types in assignment (expression has type ""dict[str, Any]"", variable has type ""list[dict[str, Any]]"") [assignment]",
o3_mini,steps_6793e6.py,fail->success,fail,success,"steps_6793e6.py:82: error: Extra keys (""bucket"", ""folder"") for TypedDict ""PushToS3Output"" [typeddict-unknown-key]",
o3_mini,stream_info_00b540.py,success->fail,success,fail,,"stream_info_00b540.py:71: error: Incompatible return value type (got ""Literal[False] | Any | None"", expected ""bool"") [return-value]"
o3_mini,streams_748e41.py,fail->success,fail,success,"streams_748e41.py:740: error: Incompatible default for argument ""setting_groups_dict"" (default has type ""None"", argument has type ""dict[Any, Any]"") [assignment]",
o3_mini,stubs_b63ee1.py,fail->success,fail,success,"stubs_b63ee1.py:542: error: ""Stub"" has no attribute ""name"" [attr-defined]",
o3_mini,subscription_info_2fc87f.py,success->fail,success,fail,,"subscription_info_2fc87f.py:475: error: Unsupported target for indexed assignment (""Mapping[str, Any]"") [index]"
o3_mini,sum__a10910.py,fail->success,fail,success,"sum__a10910.py:75: error: Incompatible types in assignment (expression has type ""float"", variable has type ""int"") [assignment]",
o3_mini,switch_24834b.py,fail->success,fail,success,switch_24834b.py:247: error: invalid syntax [syntax],
o3_mini,task_suite_e75451.py,success->fail,success,fail,,"task_suite_e75451.py:83: error: Incompatible return value type (got ""type[NotImplementedError]"", expected ""Callable[[Any], tuple[Any, ndarray[Any, Any]]]"") [return-value]"
o3_mini,tensorboard_c446d9.py,success->fail,success,fail,,"tensorboard_c446d9.py:38: error: Item ""None"" of ""Any | None"" has no attribute ""close"" [union-attr]"
o3_mini,test_2a092a.py,success->fail,success,fail,,"test_2a092a.py:69: error: Incompatible types in assignment (expression has type ""dict[str, str]"", variable has type ""_Environ[str]"") [assignment]"
o3_mini,test_alt_backend_8ffa2d.py,fail->success,fail,success,"test_alt_backend_8ffa2d.py:51: error: Unsupported operand types for - (""None"" and ""int"") [operator]",
o3_mini,test_arithmetic_ef3dfe.py,fail->success,fail,success,test_arithmetic_ef3dfe.py:95: error: Cannot infer type of lambda [misc],
o3_mini,test_arithmetics_2d6e2b.py,success->fail,success,fail,,"test_arithmetics_2d6e2b.py:244: error: Incompatible types in assignment (expression has type ""type[signedinteger[_64Bit]]"", variable has type ""dtype[Any]"") [assignment]"
o3_mini,test_arrays_9fefe1.py,success->fail,success,fail,,test_arrays_9fefe1.py:213: error: invalid syntax [syntax]
o3_mini,test_assert_frame_equal_d9bb56.py,success->fail,success,fail,,"test_assert_frame_equal_d9bb56.py:235: error: Unexpected keyword argument ""dtype"" [call-arg]"
o3_mini,test_backup_restore_171613.py,fail->success,fail,success,test_backup_restore_171613.py:62: error: Invalid type comment or annotation [valid-type],
o3_mini,test_business_hour_6b0e7b.py,fail->success,fail,success,"test_business_hour_6b0e7b.py:598: error: Dict entry 1 has incompatible type ""datetime"": ""None""; expected ""datetime"": ""datetime"" [dict-item]",
o3_mini,test_case_e8713f.py,fail->success,fail,success,test_case_e8713f.py:147: error: invalid syntax [syntax],
o3_mini,test_categorical_c93963.py,success->fail,success,fail,,"test_categorical_c93963.py:665: error: Name ""Optional"" is not defined [name-defined]"
o3_mini,test_ccxt_compat_f96503.py,fail->success,fail,success,"test_ccxt_compat_f96503.py:332: error: Argument ""hours"" to ""timedelta"" has incompatible type ""int | None""; expected ""float"" [arg-type]",
o3_mini,test_channel_622ed8.py,success->fail,success,fail,,test_channel_622ed8.py:622: error: only single target (not tuple) can be annotated [syntax]
o3_mini,test_clickhouse_fb8fef.py,fail->success,fail,success,test_clickhouse_fb8fef.py:21: error: invalid syntax [syntax],
o3_mini,test_clipboard_d0a3e6.py,success->fail,success,fail,,test_clipboard_d0a3e6.py:11: error: Invalid type comment or annotation [valid-type]
o3_mini,test_construction_01d413.py,fail->success,fail,success,test_construction_01d413.py:132: error: Too few arguments [call-arg],
o3_mini,test_conversion_928a39.py,fail->success,fail,success,"test_conversion_928a39.py:124: error: Incompatible types in assignment (expression has type ""tuple[type]"", variable has type ""type"") [assignment]",
o3_mini,test_core_08030e.py,success->fail,success,fail,,test_core_08030e.py:25: error: Implicit return in function which does not return [misc]
o3_mini,test_dependencies_3dbf6b.py,fail->success,fail,success,"test_dependencies_3dbf6b.py:168: error: ""Callable[..., Any]"" has no attribute ""__self__"" [attr-defined]",
o3_mini,test_discovery_ability_c49e14.py,success->fail,success,fail,,"test_discovery_ability_c49e14.py:64: error: Incompatible types in assignment (expression has type ""Callable[[Any], bool]"", variable has type ""Callable[[Arg(Any, 'x')], bool]"") [assignment]"
o3_mini,test_events_5e747c.py,fail->success,fail,success,test_events_5e747c.py:183: error: invalid syntax [syntax],
o3_mini,test_expanding_5d3564.py,fail->success,fail,success,"test_expanding_5d3564.py:49: error: List item 0 has incompatible type ""float""; expected ""int"" [list-item]",
o3_mini,test_fields_216131.py,fail->success,fail,success,test_fields_216131.py:127: error: Exception must be derived from BaseException [misc],
o3_mini,test_fillna_057fac.py,fail->success,fail,success,"test_fillna_057fac.py:485: error: List item 1 has incompatible type ""float""; expected ""str | None"" [list-item]",
o3_mini,test_frame_60c296.py,success->fail,success,fail,,"test_frame_60c296.py:1086: error: Function ""builtins.callable"" is not valid as a type [valid-type]"
o3_mini,test_frame_apply_391b73.py,fail->success,fail,success,"test_frame_apply_391b73.py:799: error: Name ""zip_frames"" is not defined [name-defined]",
o3_mini,test_frame_plot_matplotlib_9669ca.py,fail->success,fail,success,"test_frame_plot_matplotlib_9669ca.py:22: error: Argument 2 for ""super"" not an instance of argument 1 [misc]",
o3_mini,test_frame_subplots_be5b29.py,fail->success,fail,success,"test_frame_subplots_be5b29.py:32: error: Item ""list[Axes]"" of ""ndarray[Any, Any] | list[Axes]"" has no attribute ""shape"" [union-attr]",
o3_mini,test_freqai_datakitchen_145f2f.py,success->fail,success,fail,,test_freqai_datakitchen_145f2f.py:132: error: only single target (not tuple) can be annotated [syntax]
o3_mini,test_helpers_38220e.py,fail->success,fail,success,"test_helpers_38220e.py:49: error: Name ""TYPE_CHECKING"" is not defined [name-defined]",
o3_mini,test_hist_method_862ac9.py,fail->success,fail,success,"test_hist_method_862ac9.py:395: error: List item 0 has incompatible type ""list[str]""; expected ""str"" [list-item]",
o3_mini,test_history_818171.py,fail->success,fail,success,"test_history_818171.py:356: error: Name ""PropertyMock"" is not defined [name-defined]",
o3_mini,test_hyperopt_ac1e12.py,fail->success,fail,success,"test_hyperopt_ac1e12.py:116: error: Name ""MagicMock"" is not defined [name-defined]",
o3_mini,test_incremental_unique_id_a93cab.py,success->fail,success,fail,,"test_incremental_unique_id_a93cab.py:56: error: The return type of a generator function should be ""Generator"" or one of its supertypes [misc]"
o3_mini,test_indexing_slow_364644.py,success->fail,success,fail,,"test_indexing_slow_364644.py:30: error: Argument 1 to ""map"" has incompatible type ""type[tuple[_T_co, ...]]""; expected ""Callable[[tuple[Any, ...]], ndarray[Any, Any]]"" [arg-type]"
o3_mini,test_indices_7db737.py,success->fail,success,fail,,test_indices_7db737.py:8: error: Invalid type alias: expression is not a valid type [valid-type]
o3_mini,test_init_5dede4.py,success->fail,success,fail,,"test_init_5dede4.py:69: error: Incompatible types in assignment (expression has type ""None"", variable has type ""int"") [assignment]"
o3_mini,test_init_f7cb07.py,fail->success,fail,success,"test_init_f7cb07.py:530: error: Parameter 1 of Literal[...] cannot be of type ""Any"" [valid-type]",
o3_mini,test_layers_95be9f.py,success->fail,success,fail,,"test_layers_95be9f.py:68: error: No overload variant of ""__getitem__"" of ""tuple"" matches argument type ""tuple[int, int]"" [call-overload]"
o3_mini,test_logical_ops_b270a9.py,success->fail,success,fail,,"test_logical_ops_b270a9.py:69: error: ""dict[str, dict[str, bool]]"" has no attribute ""index"" [attr-defined]"
o3_mini,test_masked_a94e75.py,success->fail,success,fail,,"test_masked_a94e75.py:200: error: Incompatible types in assignment (expression has type ""type[object]"", variable has type ""str"") [assignment]"
o3_mini,test_matrix_transport_fc1c06.py,success->fail,success,fail,,"test_matrix_transport_fc1c06.py:227: error: Item ""None"" of ""Any | None"" has no attribute ""enqueue_unordered"" [union-attr]"
o3_mini,test_multi_209bc7.py,fail->success,fail,success,"test_multi_209bc7.py:141: error: Incompatible types in assignment (expression has type ""ndarray[Any, dtype[Any]]"", variable has type ""list[str]"") [assignment]",
o3_mini,test_notify_74a852.py,fail->success,fail,success,"test_notify_74a852.py:123: error: Incompatible types in assignment (expression has type ""str"", variable has type ""list[str]"") [assignment]",
o3_mini,test_numba_c3554f.py,success->fail,success,fail,,"test_numba_c3554f.py:137: error: ""list[list[float]]"" has no attribute ""T"" [attr-defined]"
o3_mini,test_on_attestation_3db217.py,fail->success,fail,success,"test_on_attestation_3db217.py:14: error: Name ""ALL_PHASES"" is not defined [name-defined]",
o3_mini,test_ops_on_diff_frames_1c24fd.py,success->fail,success,fail,,"test_ops_on_diff_frames_1c24fd.py:18: error: Argument 2 for ""super"" not an instance of argument 1 [misc]"
o3_mini,test_pairlist_c95c81.py,fail->success,fail,success,"test_pairlist_c95c81.py:403: error: Name ""MagicMock"" is not defined [name-defined]",
o3_mini,test_parallel_runner_4ae0f2.py,success->fail,success,fail,,test_parallel_runner_4ae0f2.py:26: error: Missing return statement [empty-body]
o3_mini,test_parse_dates_206fdc.py,fail->success,fail,success,"test_parse_dates_206fdc.py:349: error: Incompatible types in assignment (expression has type ""type[UserWarning]"", variable has type ""Exception | tuple[Any, ...]"") [assignment]",
o3_mini,test_payments_dde789.py,fail->success,fail,success,"test_payments_dde789.py:24: error: Library stubs not installed for ""requests"" [import-untyped]",
o3_mini,test_period_c61bbd.py,success->fail,success,fail,,"test_period_c61bbd.py:705: error: Argument 1 to ""datetime"" has incompatible type ""*tuple[int, ...]""; expected ""tzinfo | None"" [arg-type]"
o3_mini,test_pivot_62e6c1.py,success->fail,success,fail,,"test_pivot_62e6c1.py:968: error: List item 0 has incompatible type ""float""; expected ""str | None"" [list-item]"
o3_mini,test_process_block_header_67cc9f.py,fail->success,fail,success,test_process_block_header_67cc9f.py:31: error: invalid syntax [syntax],
o3_mini,test_process_pending_consolidations_a9c6ec.py,fail->success,fail,success,"test_process_pending_consolidations_a9c6ec.py:391: error: Argument 1 to ""append"" of ""list"" has incompatible type ""tuple[Literal['eth1'], str, str, str]""; expected ""tuple[Literal['eth1', 'comp'], Literal['<', '=', '>'], Literal['<', '='], Literal['<', '=']]"" [arg-type]",
o3_mini,test_proxies_b2ba05.py,fail->success,fail,success,"test_proxies_b2ba05.py:18: error: Incompatible types in assignment (expression has type ""BaseTransport"", variable has type ""HTTPTransport"") [assignment]",
o3_mini,test_rank_c4ccb1.py,fail->success,fail,success,"test_rank_c4ccb1.py:241: error: List item 0 has incompatible type ""float""; expected ""int"" [list-item]",
o3_mini,test_reindex_54a65d.py,success->fail,success,fail,,"test_reindex_54a65d.py:708: error: Incompatible types in assignment (expression has type ""datetime64"", variable has type ""timedelta64"") [assignment]"
o3_mini,test_rest_9e5773.py,fail->success,fail,success,"test_rest_9e5773.py:541: error: Name ""patch"" is not defined [name-defined]",
o3_mini,test_rpc_0215ce.py,fail->success,fail,success,test_rpc_0215ce.py:634: error: invalid syntax [syntax],
o3_mini,test_rpc_telegram_deaea2.py,fail->success,fail,success,"test_rpc_telegram_deaea2.py:102: error: Name ""AsyncMock"" is not defined [name-defined]",
o3_mini,test_s3_fad4be.py,fail->success,fail,success,test_s3_fad4be.py:160: error: Missing return statement [return],
o3_mini,test_selector_bbc47d.py,success->fail,success,fail,,"test_selector_bbc47d.py:48: error: ""None"" not callable [misc]"
o3_mini,test_settlement_0a3fe7.py,fail->success,fail,success,"test_settlement_0a3fe7.py:706: error: ""None"" has no attribute ""to_balanceproof"" [attr-defined]",
o3_mini,test_shrinker_1f54e0.py,fail->success,fail,success,"test_shrinker_1f54e0.py:358: error: Module has no attribute ""freeze"" [attr-defined]",
o3_mini,test_stat_reductions_69f5b2.py,success->fail,success,fail,,test_stat_reductions_69f5b2.py:21: error: Too few arguments [call-arg]
o3_mini,test_stoploss_on_exchange_98cce5.py,fail->success,fail,success,test_stoploss_on_exchange_98cce5.py:604: error: Type cannot be declared in assignment to non-self attribute [misc],
o3_mini,test_string_c0dad8.py,success->fail,success,fail,,"test_string_c0dad8.py:149: error: Name ""cast"" is not defined [name-defined]"
o3_mini,test_targetstate_85ad01.py,fail->success,fail,success,"test_targetstate_85ad01.py:77: error: ""list[Any]"" has no attribute ""get_hop"" [attr-defined]",
o3_mini,test_to_csv_e7f2e8.py,fail->success,fail,success,"test_to_csv_e7f2e8.py:485: error: Name ""ParserError"" is not defined [name-defined]",
o3_mini,test_to_numeric_199e51.py,success->fail,success,fail,,"test_to_numeric_199e51.py:204: error: Incompatible types in assignment (expression has type ""type[object]"", variable has type ""type[float]"") [assignment]"
o3_mini,test_value_counts_77b3d1.py,success->fail,success,fail,,"test_value_counts_77b3d1.py:563: error: Argument 1 to ""list"" has incompatible type ""list[str | None]""; expected ""Iterable[str]"" [arg-type]"
o3_mini,test_wallets_fe5a94.py,fail->success,fail,success,"test_wallets_fe5a94.py:409: error: Unsupported operand types for - (""str"" and ""float"") [operator]",
o3_mini,test_webserver_68a1ed.py,success->fail,success,fail,,"test_webserver_68a1ed.py:104: error: ""Callable[..., Any]"" has no attribute ""return_value"" [attr-defined]"
o3_mini,test_websockets_059343.py,fail->success,fail,success,"test_websockets_059343.py:86: error: ""Exception"" has no attribute ""original_error"" [attr-defined]",
o3_mini,textual_entailment_suite_19763e.py,fail->success,fail,success,"textual_entailment_suite_19763e.py:28: error: List item 0 has incompatible type ""str | list[str]""; expected ""str"" [list-item]",
o3_mini,token_network_registry_0d90a4.py,success->fail,success,fail,,"token_network_registry_0d90a4.py:68: error: Name ""typecheck"" is not defined [name-defined]"
o3_mini,tools_6a9569.py,success->fail,success,fail,,"tools_6a9569.py:120: error: Item ""Iterable[Axes]"" of ""Axes | Iterable[Axes]"" has no attribute ""get_figure"" [union-attr]"
o3_mini,topic_6b7f8d.py,success->fail,success,fail,,"topic_6b7f8d.py:123: error: Unsupported operand type for unary - (""str | int"") [operator]"
o3_mini,train_test_b790e4.py,success->fail,success,fail,,"train_test_b790e4.py:468: error: Unsupported operand types for * (""None"" and ""int"") [operator]"
o3_mini,trainer_test_f0df2a.py,success->fail,success,fail,,"trainer_test_f0df2a.py:1130: error: Item ""None"" of ""Tensor | None"" has no attribute ""is_sparse"" [union-attr]"
o3_mini,transactions_739961.py,success->fail,success,fail,,"transactions_739961.py:14: error: Name ""GAS_TXDatanonzero"" is not defined [name-defined]"
o3_mini,transfers_b8ecf0.py,fail->success,fail,success,transfers_b8ecf0.py:141: error: Attributes without a default cannot follow attributes with one [misc],
o3_mini,transformer_embeddings_test_676185.py,success->fail,success,fail,,"transformer_embeddings_test_676185.py:58: error: Incompatible default for argument ""input_ids"" (default has type ""None"", argument has type ""Tensor"") [assignment]"
o3_mini,transport_58bb8a.py,fail->success,fail,success,"transport_58bb8a.py:165: error: Name ""_metadata_key_func"" is not defined [name-defined]",
o3_mini,tts_72d912.py,success->fail,success,fail,,"tts_72d912.py:18: error: Name ""Final"" is not defined [name-defined]"
o3_mini,unit_system_a3b7c4.py,success->fail,success,fail,,"unit_system_a3b7c4.py:31: error: Name ""Final"" is not defined [name-defined]"
o3_mini,upnp_cf635d.py,fail->success,fail,success,"upnp_cf635d.py:73: error: Argument 1 of ""connection_made"" is incompatible with supertype ""BaseProtocol""; supertype defines the argument type as ""BaseTransport"" [override]",
o3_mini,users_e38fbd.py,success->fail,success,fail,,"users_e38fbd.py:257: error: Unsupported operand types for | (""set[int]"" and ""list[int]"") [operator]"
o3_mini,util_d92a2e.py,fail->success,fail,success,"util_d92a2e.py:12: error: Incompatible return value type (got ""FrameType | None"", expected ""FrameType"") [return-value]",
o3_mini,util_e9973a.py,success->fail,success,fail,,"util_e9973a.py:99: error: Name ""VIDEO_CODEC_LIBX264"" is not defined [name-defined]"
o3_mini,utils_3f6c97.py,success->fail,success,fail,,"utils_3f6c97.py:162: error: Invalid index type ""T"" for ""dict[str, Any]""; expected type ""str"" [index]"
o3_mini,utils_71116c.py,success->fail,success,fail,,"utils_71116c.py:19: error: Incompatible types in assignment (expression has type ""bytes"", variable has type ""str"") [assignment]"
o3_mini,utils_a09b8c.py,success->fail,success,fail,,"utils_a09b8c.py:522: error: Incompatible types in assignment (expression has type ""tuple[Any, Any]"", variable has type ""tuple[Any]"") [assignment]"
o3_mini,views_61a9fc.py,fail->success,fail,success,"views_61a9fc.py:275: error: Incompatible return value type (got ""StreamResponse"", expected ""Response"") [return-value]",
o3_mini,voip_c111eb.py,fail->success,fail,success,"voip_c111eb.py:75: error: ""Event"" expects no type arguments, but 1 given [type-arg]",
o3_mini,weather_26d8e5.py,fail->success,fail,success,"weather_26d8e5.py:64: error: Name ""TYPE_CHECKING"" is not defined [name-defined]",
o3_mini,withdrawals_7e4651.py,fail->success,fail,success,withdrawals_7e4651.py:199: error: Return value expected [return-value],
o3_mini,wrappers_34ca66.py,fail->success,fail,success,wrappers_34ca66.py:28: error: Free type variable expected in Generic[...] [misc],
